Questions or feedback  to admin email
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #107
Opened 2023-06-29 21:01 UTC by KonstKorn

Для проверки работы отправки и получения электронного письма, нужно:
1. Заполнить в settings актуальные данные для почтового ящика отправки и получения:
# Organization data
ORGANIZATIONS_EMAIL: str = "procharity@yandex.ru"

# Настройки отправки сообщений через электронную почту
MAIL_SERVER: str = "smtp.yandex.ru"  # адрес почтового сервиса
MAIL_PORT: int = 465  # порт для подключения к почтовому сервису
MAIL_LOGIN: str = ""  # логин для подключения к почтовому сервису
MAIL_PASSWORD: str = ""  # пароль для подключения к почтовому сервису
MAIL_STARTTLS: bool = False  # использовать STARTTLS или нет
MAIL_SSL_TLS: bool = True  # использовать SSL/TLS или нет
USE_CREDENTIALS: bool = True  # использовать логин/пароль для подключения к почтовому серверу или нет
VALIDATE_CERTS: bool = True  # проверять SSL сертификат почтового сервера или нет

# Адреса электронной почты администраторов
EMAIL_ADMIN = ["procharity.admin_1@yandex.ru"] - адрес получателя администартора

2. Запустить бот и нажать на кнопку "включить/выключить подписку на задания" (в качестве теста в хэндлерах menu.py для set_mailing добавлена send_question_feedback).

2023-07-06 12:32 UTC, NiKuma0 requested changes

2023-07-06 12:32 UTC, NiKuma0 commented on src/bot/handlers/menu.py
> +        text = "Отлично! Теперь я буду присылать тебе уведомления о новых " "заданиях на почту."
```suggestion
        text = "Отлично! Теперь я буду присылать тебе уведомления о новых заданиях на почту."
```

2023-07-06 12:32 UTC, NiKuma0 commented on src/bot/handlers/menu.py
> +    await EmailProvider.send_question_feedback(EmailProvider, telegram_id, text, settings.EMAIL_ADMIN)
Зачем тут такой кастыль, не будет проще создать экземпляр класса, а затем обратится к его методу? 
```suggestion
    email_provider = EmailProvider()
    await email_provider.send_question_feedback(telegram_id, text, settings.EMAIL_ADMIN)
```

2023-07-06 12:32 UTC, NiKuma0 commented on src/core/services/email.py
> +        fastmail = FastMail(conf)
Давай это перенесем в конструктор `__init__`

2023-07-06 12:32 UTC, NiKuma0 commented on src/settings.py
> +    VALIDATE_CERTS: bool = True  # проверять SSL сертификат почтового сервера или нет
Комментарии не нужны. Добавь их в .env.example

2023-07-08 13:22 UTC, KonstKorn commented
@NiKuma0 Привет! Не могу понять почему ошибка возникает. Как будто памяти не хватает.

2023-07-08 13:42 UTC, KonstKorn commented
@NiKuma0 все ок, разобрался)

2023-07-14 21:30 UTC, NiKuma0 requested changes

2023-07-15 09:19 UTC, KonstKorn commented on src/bot/handlers/menu.py
> +    await email_provider.send_question_feedback(telegram_id, text, settings.EMAIL_ADMIN)
@NiKuma0  Я тут писал, чтобы проверить отправку писем. Уже дописали куда можно добавить отправку именно отзывов/вопросов, чтобы проверить работу кода?

2023-07-15 15:05 UTC, NiKuma0 commented on src/bot/handlers/menu.py
> +    await email_provider.send_question_feedback(telegram_id, text, settings.EMAIL_ADMIN)
Пока нет. Создай отдельный хендлер, в рабочий код не надо.

2023-07-16 11:48 UTC, NiKuma0 reviewed
В целом все хорошо)

2023-07-16 11:48 UTC, NiKuma0 commented on src/core/services/email.py
> +            user = None
Тут точно нужен `try, except`? `get_by_telegram_id` возвращает пользователя либо `None`. Также ниже идёт `user.email` если `user = None`, работать не будет...

2023-07-16 11:48 UTC, NiKuma0 commented on src/core/services/email.py
> +            subject=f"Сообщение от пользователя {user.username}(email: {user.email})",
Тут лучше использовать полное имя
```suggestion
            subject=f"Сообщение от пользователя {user.full_name} ({user.email or 'пользователь не указал свой email'})",
```

2023-07-16 12:15 UTC, KonstKorn commented on src/core/services/email.py
> +            user = None
Try, except  тут точно не нужен.  Это я сначала, когда начинал писать и написал эту конструкцию, а потом забыл убрать(думал, что убрал ее).

2023-07-16 12:15 UTC, KonstKorn commented on src/core/services/email.py
> +            subject=f"Сообщение от пользователя {user.username}(email: {user.email})",
Исправлю

2023-07-16 12:27 UTC, KonstKorn commented on src/core/services/email.py
> +            subject=f"Сообщение от пользователя {user.username}(email: {user.email})",
@NiKuma0 а зачем такая конструкция  - {user.email or 'пользователь не указал свой email'})"? у меня пишет сообщение, если почта не указана и при старой.  И еще одно уточнение - full_name это чтобы выводилось имя и фамилия? Я поля full_name не вижу у User.

2023-07-16 12:59 UTC, NiKuma0 commented on src/core/services/email.py
> +            subject=f"Сообщение от пользователя {user.username}(email: {user.email})",
> Я поля full_name не вижу у User.

Если того поля нет, оставь просто `user.first_name`, потом добавим.

> а зачем такая конструкция - {user.email or 'пользователь не указал свой email'})"?

Это конструкция не то чтобы "нужна", так будет меньше вложенности, и, на мой взгляд ,проще будет читатся.

2023-07-16 19:19 UTC, KonstKorn commented on src/core/services/email.py
> +            subject=f"Сообщение от пользователя {user.username}(email: {user.email})",
Понял. Спасибо за разъяснения!

2023-07-17 09:14 UTC, NiKuma0 approved these changes

2023-07-17 11:36 UTC, merged