Feature/send telegram message to user
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #108
Opened 2023-06-30 05:55 UTC by ArtemBalandin81

1. изменил схему для отправки сообщений пользователям, наследовав ее от схемы для 1го пользователя;
2. добавил метод send_message_to_user в TelegramNotificationService, использовав скрытый метод send_message класса TelegramNotification
3. изменил название рутера на более универсальное - notification_router, т.к. он же используется для отправки сообщения одному пользователю
4. при отправке сообщения пользователю в схеме ответа-апи использую str

2023-07-02 10:53 UTC, NiKuma0 requested changes

2023-07-02 10:53 UTC, NiKuma0 commented on src/api/services/messages.py
> +        await self.telegram_notification._TelegramNotification__send_message(
Так делать не нужно. Создай отдельный метод `send_message`

2023-07-02 10:53 UTC, NiKuma0 commented on src/core/services/notification.py
> +        return message
Давай без дублирования кода)

2023-07-11 10:05 UTC, NiKuma0 commented on src/core/services/notification.py
> +        return True
И зачем тут возврощать булевое значение? Посмотри внимательнее, эта функция будет всегда возвращать `True`.

2023-07-11 10:05 UTC, NiKuma0 approved these changes
В целом все хорошо, только один комментарий

2023-07-11 11:01 UTC, ArtemBalandin81 commented on src/core/services/notification.py
> +        return True
а в методе send_messages выше - аналогично, также получается возврат булевого зазря делается?
Зачем в них вообще был сделан возврат "return True"? Они же и без них работают.

Эх, Никита, сделать бы задач 30-40 - тогда возможно, пришло бы понимание (осознание)...

2023-07-12 10:55 UTC, NiKuma0 commented on src/core/services/notification.py
> +        return True
Хорошо что заметил). Там тоже поправь.

Вообще, подобное делается чтобы можно было отследить прошла ли успешно отправка сообщений. Функция `__send_message` тупо логирует ошибку, не возвращая ничего. Поэтому возвращать `True` бесполезно - помимо того, что это нигде не используется так еще в случае ошибки всё равно вернёт `True`... 

Надо тут полностью класс переработать, а пока убери `return True`

2023-07-14 04:11 UTC, ArtemBalandin81 commented on src/core/services/notification.py
> +        return True
Поправил, и если я правильно понял, то они обе также ничего не возвращают -> None

2023-07-14 14:32 UTC, merged