ExternalSiteUser model and endpoint
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #114
Opened 2023-07-05 01:12 UTC by Ander-dog

2023-07-06 13:51 UTC, NiKuma0 requested changes

2023-07-06 13:51 UTC, NiKuma0 commented on src/core/db/repository/external_site_user.py
> +        return site_user.scalars().first()
```suggestion
        return await self._session.scalar(
            select(ExternalSiteUser).where(ExternalSiteUser.external_id == external_id)  # noqa
        )
```

2023-07-06 13:51 UTC, NiKuma0 commented on src/api/services/external_site_user.py
> +class ExternalSiteUserService(ContentService):
Зачем наследовать от `ContentService`?

2023-07-06 13:51 UTC, NiKuma0 commented on src/api/services/external_site_user.py
> +    async def registrate(self, site_user_schema: ExternalSiteUserRequest) -> None:
```suggestion
    async def register(self, site_user_schema: ExternalSiteUserRequest) -> None:
```

2023-07-06 13:51 UTC, NiKuma0 commented on src/api/services/external_site_user.py
> +            await self._repository.create(ExternalSiteUser(**site_user_schema.dict()))
Лучше создай у модели `ExternalSieteUserRequest` метод `to_orm`, посмотри [как это сделано в ламая барьеры](https://github.com/Studio-Yandex-Practicum/lomaya_baryery_backend/blob/develop/src/api/request_models/user.py#L53C4-L53C4).

2023-07-07 10:55 UTC, NiKuma0 commented on src/api/schemas.py
> +            site_user.specializations = self.specializations
Зачем тут if else?

2023-07-07 10:55 UTC, NiKuma0 commented on src/api/services/external_site_user.py
> +            await self._repository.update(None, site_user_schema.to_orm(site_user))
Этот не будет работать. Первый аргумент нужен не просто так, а ты просто в него `None` суёшь. Поменяй метод в `ExternalSiteUserRepository` чтобы вместо `id` был `external_id`.

2023-07-08 11:44 UTC, NiKuma0 requested changes

2023-07-08 11:44 UTC, NiKuma0 commented on src/core/db/models.py
> +    external_id: Mapped[int] = mapped_column(Integer, primary_key=True)
Я тут подумал, а в чем разница между `ExternalSiteUser.external_id` и `ExternalSiteUser.id`? Чисто логически, эти поля означают одно и тоже - предлагаю отказаться от поля `external_id` в пользу `id`.

2023-07-09 08:06 UTC, Ander-dog commented on src/core/db/models.py
> +    external_id: Mapped[int] = mapped_column(Integer, primary_key=True)
Может тогда и external_id_hash в просто id_hash переименовать?

2023-07-09 10:25 UTC, NiKuma0 commented on src/core/db/models.py
> +    external_id: Mapped[int] = mapped_column(Integer, primary_key=True)
Да, можно.

2023-07-09 10:33 UTC, NiKuma0 approved these changes
Все хорошо.

2023-07-09 10:33 UTC, merged