Добавлены причины отписки
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #116
Opened 2023-07-06 22:05 UTC by Ander-dog

2023-07-07 19:58 UTC, NiKuma0 commented
Давай удалять/изменять старое сообщение, чтобы нельзя было его нажимать по нескольку раз 
![image](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/78080842/e2656ecb-4af4-46a5-ba5b-46e10974e44e)


P.S. Привяжи ПР к issue (задаче)

2023-07-09 10:46 UTC, NiKuma0 requested changes

2023-07-09 10:46 UTC, NiKuma0 commented on src/core/logging/utils.py
> +    await log.ainfo(info, args=args, kwargs=kwargs)
Зачем эта функция? Проще использовать `log.ainfo`

2023-07-09 10:46 UTC, NiKuma0 commented on src/bot/keyboards.py
> +]
Давай сделаем REASONS в формате `enum`.

2023-07-09 10:59 UTC, Ander-dog commented on src/core/logging/utils.py
> +    await log.ainfo(info, args=args, kwargs=kwargs)
А `log = structlog.get_logger()` лучше написать в функции reason() или вне неё?

2023-07-10 12:29 UTC, NiKuma0 commented on src/api/schemas.py
> +        return site_user
Думаю лучше использовать init метод - 
```python
def to_orm(self) -> ExternalSiteUser:
    return ExternalSiteUser(
        id=self.id,
        id_hash=self.id_hash,
        ...
    )
```

2023-07-10 12:32 UTC, NiKuma0 commented on src/bot/keyboards.py
> +class REASONS(enum.StrEnum):
Перенеси класс в отдельный файл `enums`

2023-07-10 12:35 UTC, NiKuma0 commented on src/core/db/models.py
> +    specializations: Mapped[str] = mapped_column(String(), nullable=False)
Насколько я знаю `nullable=False` стоит по умлачению, так что в этой стороке (и в некоторых других) смысла нет: 

```suggestion
    specializations: Mapped[str]
```

2023-07-10 12:38 UTC, NiKuma0 commented on src/core/db/models.py
> +    source: Mapped[str] = mapped_column(String(), nullable=True)
Тут нет смысла указывать тип, он и так автоматом ставится. 
```suggestion
    source: Mapped[str] = mapped_column(nullable=True)
```

2023-07-10 12:39 UTC, Ander-dog commented on src/bot/keyboards.py
> +class REASONS(enum.StrEnum):
Файл сделать в папке с константами?

2023-07-11 10:09 UTC, NiKuma0 commented on src/core/logging/utils.py
> +    await log.ainfo(info, args=args, kwargs=kwargs)
Да, там будет логично.

2023-07-11 10:13 UTC, NiKuma0 approved these changes

2023-07-11 10:13 UTC, NiKuma0 commented
Поправь конфликт.

2023-07-11 12:54 UTC, merged