fix/removing-messages-once-pushed
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #124
Opened 2023-07-13 11:59 UTC by thesupercalifragilisticexpialidocious

Тикет №121 https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/issues/121

Реализовано удаление сообщений с кнопками при вызове хэндлеров этих кнопок.

Добавлен файл src.bot.utils.py, где добавлен декоратор для оборачивания функций, в которых реализуется отправка новых сообщений с инлайн-клавиатурами.

Для хэндлеров форм обратной связи декоратор пока не довлен, так как их работа не может быть завершена корректно.

2023-07-13 12:02 UTC, NiKuma0 requested changes

2023-07-13 12:02 UTC, NiKuma0 commented on src/bot/utils.py
> +def delete_previous(coroutine):
Посмотри как сделан прошлый декоратор - `log_decor`. Там используются тайпинги и functools - это важно)

2023-07-13 12:02 UTC, NiKuma0 commented on src/bot/utils.py
> +        result = await coroutine(*args, **kwargs)
```suggestion
        result = await coroutine(update: Update, *args, **kwargs)
```
Не нужно тут использовать цикл...

2023-07-13 15:44 UTC, thesupercalifragilisticexpialidocious commented on src/bot/utils.py
> +def delete_previous(coroutine):
в лог_декоре не было тайпингов и фанктулзов :) я посмотрел документы, надеюсь правильно понял запрос.
я аналогичным способом изменил лог_декор, ок?

2023-07-13 15:46 UTC, thesupercalifragilisticexpialidocious commented
Добавлены аннотации и @wraps декоратор для bot/utils.py и core/logging/utils.py

2023-07-14 14:29 UTC, NiKuma0 requested changes
В целом все отлично, хорошо поправил logger_decor.

2023-07-17 14:14 UTC, NiKuma0 approved these changes

2023-07-17 14:14 UTC, NiKuma0 commented on src/bot/utils.py
> +def delete_previous(
Переименую на `delete_previous_message`

2023-07-17 16:22 UTC, merged