add static
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #125
Opened 2023-07-13 20:39 UTC by supersidr

2023-07-14 14:34 UTC, NiKuma0 requested changes

2023-07-14 14:34 UTC, NiKuma0 commented on src/settings.py
> +    STATIC_URL: str = "../templates"
```suggestion
    STATIC_URL: str = "/static/"
```

2023-07-14 14:54 UTC, NiKuma0 requested changes

2023-07-14 14:54 UTC, NiKuma0 commented on src/settings.py
>      def feedback_form_template(self) -> Path:
Кажется эта функция больше не нужна.

2023-07-14 14:54 UTC, NiKuma0 commented on src/settings.py
> +        return urljoin(self.api_url, settings.STATIC_URL)
Тут получается ссылка на статику, а не на форму. `feedback_form/feedback_form.html`

2023-07-14 14:57 UTC, supersidr commented on src/settings.py
> +        return urljoin(self.api_url, settings.STATIC_URL)
Ревертнуть изменения?

2023-07-14 20:34 UTC, NiKuma0 commented on src/settings.py
> +        return urljoin(self.api_url, settings.STATIC_URL)
Подтестируй работу функции, она возвращает `localhost/static/`, а должна быть ссылка на форму - 'localhost/feedback_form/feedback_form.html'

2023-07-16 11:49 UTC, NiKuma0 commented on src/settings.py
> +        return urljoin(self.api_url, f"{settings.STATIC_URL}feedback_form/feedback_form.html")
Давай тут использовать urljoin а не f-string

2023-07-16 15:38 UTC, NiKuma0 approved these changes

2023-07-16 15:38 UTC, merged