Feature/categories api
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #13
Opened 2023-04-12 17:16 UTC by Etozheigor

Задача: https://www.notion.so/API-Procharity-99c19efb948e43659c0f6491c60d3ca5?pvs=4

2023-04-12 21:04 UTC, elych-ru commented on src/core/services/category_service.py
> +    async def actualize_categories(self, new_categories_request: list[CaregoryRequest]) -> Category:  # noqa: C901
Функция вроде ничего не возвращает?

2023-04-13 17:23 UTC, NiKuma0 requested changes
Код не рабочий, в следующий раз подтестируй и опиши как именно тестил.

2023-04-13 17:23 UTC, NiKuma0 commented on src/core/services/category_service.py
> +            new_category = Category(**new_category_data)
Сделай проще: 
```suggestion
            new_categories.append(
                Category(**category.dict(), archive=False)
            )
```

2023-04-13 17:23 UTC, NiKuma0 commented on src/core/services/category_service.py
> +        for id in unarchive_categories_id_db:
Такое имя не подходить, `id` - уже есть (это стандартная функия постовляймое python), ты его переопределяешь.

2023-04-13 17:23 UTC, NiKuma0 commented on src/core/services/category_service.py
> +            for category_to_update in categories_to_update:
Кажется этому место в `repository`.

2023-04-13 17:23 UTC, NiKuma0 commented on src/core/services/category_service.py
> +    async def get_all_categories(self) -> list[Category]:
Зачем эта функция?

2023-04-13 17:23 UTC, NiKuma0 commented on src/core/db/repository/category_repository.py
> +            self._session.add(category)
Кажется есть функция `add_all`. Используй циклы в крайнем случае, сначала загугли можно ли обойтись одним запросом.

2023-04-13 17:23 UTC, NiKuma0 commented on src/core/db/repository/category_repository.py
> +        for id in categories_to_archive_id:
Не используй имя `id`. ТУт можно сделать одним запросом без цикла.

2023-04-14 08:59 UTC, Etozheigor commented on src/core/services/category_service.py
> +    async def get_all_categories(self) -> list[Category]:
для эндпоинта GET /api/v1/categories/, чтобы тестировать POST-запросы. Убрать эту функцию и эндпоинт?

2023-04-14 09:45 UTC, NiKuma0 commented on src/core/services/category_service.py
> +    async def get_all_categories(self) -> list[Category]:
Понял, можно оставить.

2023-04-15 10:59 UTC, NiKuma0 commented on src/core/db/repository/category.py
> +    async def create_all(self, new_categories: list[Category]) -> None:
Думаю эта функция пригодилась бы в других классах, перениси ее в базовый класс

2023-04-15 10:59 UTC, NiKuma0 commented on src/core/db/repository/category.py
> +        """Получает из базы id всех незаархивированных категорий."""
```suggestion
        """Получает из базы id всех не заархивированных категорий."""
```

2023-04-15 10:59 UTC, NiKuma0 commented on src/core/db/repository/category.py
> +    async def archive_categories(self, categories_to_archive_id: list[int]) -> None:
Зачем тут такое сложное название? Без него и так понятно - `repository.archive_categories(categories=categories)`.

2023-04-15 10:59 UTC, NiKuma0 commented on src/core/services/category.py
> +    async def archive_categories(self, categories_to_archive_id):
Зачем ты оборочиваешь эти функции?

2023-04-16 10:10 UTC, NiKuma0 reviewed
Мне не очень нравятся как выглядят логика, буду думать как сделать по лучше. Пока исправь эти комментарии...

2023-04-16 10:10 UTC, NiKuma0 commented on src/core/services/category.py
> +        unarchive_categories_id_db = await self.__category_repository.get_unarchive_categories_id()
Это используется один раз, поэтому переменая тут не нужна.

2023-04-16 10:10 UTC, NiKuma0 commented on src/core/services/category.py
> +            if category.id not in categories_id_db:
Кажется мы можем сделать так `if category not in categories_db` - чтобы не создовать доп лист `categories_id_db`.

2023-04-16 18:42 UTC, Etozheigor commented on src/core/services/category.py
> +class CategoryService:
ты имеешь ввиду, что нужно в папке `api` создать папку `services` и туда добавить файл `categories.py`  с этим классом?

2023-04-16 18:49 UTC, Etozheigor commented on src/core/services/category.py
> +            elif (
Не очень понял. Если не проверять на изменение, то как узнать, что объект вообще надо обновлять?

2023-04-16 18:52 UTC, Etozheigor commented on src/core/services/category.py
> +        categories_to_add, categories_to_update = await self.get_categories_to_add_or_update(
Ок, поменял

2023-04-16 18:59 UTC, Etozheigor commented on src/core/services/category.py
> +            if category.id not in categories_id_db:
Тут тоже не очень понял. Допустим, в запросе от сайта пришла категория, у которой изменилось поле `name`. Тогда `if category not in categories_db` даст `True` и категория будет добавлена как новая, хотя она уже была и у нее нужно просто обновить поле `name`. Либо я не так понял комментарий?

2023-04-16 19:06 UTC, Etozheigor commented on src/core/services/category.py
> +        unarchive_categories_id_db = await self.__category_repository.get_unarchive_categories_id()
categories_db используется дважды. Эту переменную оставляю, правильно? Остальное убрал.

2023-04-17 07:28 UTC, NiKuma0 commented on src/core/services/category.py
> +class CategoryService:
Да

2023-04-17 07:33 UTC, NiKuma0 commented on src/core/services/category.py
> +            elif (
Зачем нам это узнавать? Просто запихни все в `update`, если откажется работать с не обновлённой датой, тогда оставь как есть.

2023-04-17 07:39 UTC, NiKuma0 commented on src/core/services/category.py
> +            if category.id not in categories_id_db:
А, ну да)

2023-04-17 08:25 UTC, NiKuma0 commented
Подумал как можно улучшить запросы, пришел к такой структуре:
```python
    async def actualize_categories(self, categories: list[CaregoryRequest]) -> None:
        categories = [Category(**category.dict(), archive=False) for category in categories]
        to_create = []
        to_update = []
        # Архивируем все категории, актуальные мы потом обновим и разархивируем. 
        # Этот шаг мы можем запустить только будучи уверены что другие сработают.
        # Поэтому нужно добавить транзакции, и в случае ошибки делать откат.
        await self.__category_repository.archive_all()
        # Тут мы получаем только id-шки
        already_have = await self.__category_repository.get_all_ids()
        for category in categories:
            if category.id not in already_have:
                to_create.append(category)
            else:
                # Нам в любом случае нужно делать обновление, т.к. эти категории нужно разархивировать.
                to_update.append(category)
        await self.__category_repository.create_all(to_create)
        await self.__category_repository.update_all(to_update)
```
Это примерный код, и, наверное, точно так как описал работать не будет, но я хочу видеть что-то подомное.

2023-04-21 15:46 UTC, NiKuma0 commented on src/api/services/category.py
> +                to_update.append(category_dict)
```suggestion
                to_update.append(Category(**category.dict(), archive=False))
```

2023-04-21 15:48 UTC, NiKuma0 commented on src/core/db/models.py
> +from sqlalchemy import BigInteger, Boolean, Column, Date, ForeignKey, Integer, String, Table
Мы уже починили этот файл. Оставь как в ветке `develop`

2023-04-21 15:50 UTC, NiKuma0 commented on src/core/db/repository/category.py
> +        """Добавляет несколько категорий в архив."""
```suggestion
        """Добавляет все категорий в архив."""
```

2023-04-21 15:50 UTC, NiKuma0 commented on src/core/services/category.py
> +from fastapi import Depends
Кажется это старый класс

2023-04-21 15:58 UTC, Etozheigor commented on src/api/services/category.py
> +                to_update.append(category_dict)
Тут нужен не объект типа Category, а именно словарь, потому что я переписал метод update_all базового класса репозитория. В новом синтаксисе для обновления нужны словари и я подумал, что проще сразу в метод передавать список словарей, чем список объектов, которые потом преобразовывать в словарь. Вот из этой доки пример брал:
https://docs.sqlalchemy.org/en/20/orm/queryguide/dml.html#orm-queryguide-bulk-update

2023-04-22 09:36 UTC, NiKuma0 commented on src/api/services/category.py
> +                to_update.append(category_dict)
Ну тогда так: 
```suggestion
                to_update.append(**category.dict(), archive=False)
```

2023-04-22 09:52 UTC, Etozheigor commented on src/api/services/category.py
> +                to_update.append(category_dict)
Так тоже не получается. Append принимает только один аргумент. Нужно сначала добавить в словарь ключ 'archive', а уже потом добавить этот словарь в список to_update. Я думал передавать сразу Pydantic-модель, но в ней тоже нет поля archive, его в любом случае нужно будет отдельно добавлять.

2023-04-22 10:36 UTC, NiKuma0 commented on src/api/services/category.py
> +                to_update.append(category_dict)
Ну сам мог бы додумать) 
```suggestion
                to_update.append({**category.dict(), archive=False})
```

2023-04-22 10:38 UTC, NiKuma0 approved these changes

2023-04-23 09:03 UTC, merged