Add_variables_to_deploy
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #135
Opened 2023-07-17 21:48 UTC by KonstKorn

2023-07-18 10:44 UTC, NiKuma0 requested changes

2023-07-18 10:44 UTC, NiKuma0 commented on .github/workflows/deploy_stage.yaml
> +            ORGANIZATIONS_EMAIL=${{ secrets.ORGANIZATIONS_EMAIL }}
А где `EMAIL_ADMIN`?

2023-07-18 13:56 UTC, KonstKorn commented on .github/workflows/deploy_stage.yaml
> +            ORGANIZATIONS_EMAIL=${{ secrets.ORGANIZATIONS_EMAIL }}
Я пробовал добавить (EMAIL_ADMIN=${{ secrets.EMAIL_ADMIN }}), но у меня валится тогда start application.

2023-07-18 14:27 UTC, KonstKorn commented on .github/workflows/deploy_stage.yaml
> +            ORGANIZATIONS_EMAIL=${{ secrets.ORGANIZATIONS_EMAIL }}
@NiKuma0 Исправил settings и добавил EMAIL_ADMIN. Похоже в secrets был не список и строка почты.

2023-07-20 11:26 UTC, NiKuma0 commented on src/settings.py
> +    EMAIL_ADMIN: EmailStr
Так работать будет?)
```suggestion
    EMAIL_ADMIN: list[EmailStr] | EmailStr = []
```

2023-07-20 12:09 UTC, NiKuma0 commented
Теперь валидатор `EmailSchema` ругается) 
![image](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/78080842/f2cbb316-d3bc-41e1-a81c-b37c2ea50051)

2023-07-20 15:05 UTC, KonstKorn commented on src/settings.py
> +    EMAIL_ADMIN: EmailStr
EMAIL_ADMIN: list[EmailStr] | EmailStr = [] - я так пробовал, у меня не работало. Вечером посмотрю и попробую еще не сколько вариантов)

2023-07-20 15:10 UTC, KonstKorn commented on src/settings.py
> +    EMAIL_ADMIN: EmailStr
Похоже теперь норм должно работать) Обновил)

2023-07-20 23:04 UTC, KonstKorn commented
@NiKuma0 вроде все получилось, у меня локально работает и со списком и со строкой. Проверь, пожалуйста, у  себя

2023-07-24 20:39 UTC, NiKuma0 approved these changes

2023-07-24 20:39 UTC, NiKuma0 commented on src/settings.py
> +    EMAIL_ADMIN: str | list[str]
У нас везде `EmailStr` а тут просто `str`, почему?)

2023-07-24 21:24 UTC, KonstKorn commented on src/settings.py
> +    EMAIL_ADMIN: str | list[str]
Не понимаю почему, но Start application проходит без ошибок только в таком написании. В любом другом выходит ошибка.

2023-07-26 11:10 UTC, NiKuma0 commented on src/settings.py
> +    EMAIL_ADMIN: str | list[str]
[Вот тут описана ошибка](https://github.com/pydantic/pydantic/issues/5739). Похоже нужно обновить `email-validator` и вместе с ним `fastapi_mail`

2023-07-26 11:22 UTC, NiKuma0 commented on src/settings.py
> +    EMAIL_ADMIN: str | list[str]
Тут весь `fast-api` нужно обновить) Сделаю отдельный ПР на обновления либ

2023-07-26 21:20 UTC, NiKuma0 commented on src/settings.py
> +    EMAIL_ADMIN: str | list[str]
@KonstKorn ПР сделан, можно смело оставлять `list[EmailStr]` - пусть будет листом, оператор "|" немного странно работает.

2023-07-26 21:56 UTC, NiKuma0 requested changes

2023-07-26 21:56 UTC, NiKuma0 commented on src/settings.py
> +    EMAIL_ADMIN: list[EmailStr]
Похоже лист не парсится(
![image](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/78080842/8e309aad-4137-4249-b472-3003ce40d96b)
Оставь просто `EmailStr`

2023-07-26 21:59 UTC, KonstKorn commented on src/settings.py
> +    EMAIL_ADMIN: list[EmailStr]
Поставил

2023-07-26 22:01 UTC, KonstKorn commented on src/settings.py
> +    EMAIL_ADMIN: list[EmailStr]
У меня все прошло с EmailStr

2023-07-27 10:03 UTC, NiKuma0 approved these changes
Отлично, все работает!

2023-07-27 10:03 UTC, merged