fix/move categories from tasks.py to categories.py
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #136
Opened 2023-07-18 03:54 UTC by supersidr

2023-07-18 10:41 UTC, NiKuma0 requested changes
В следующий раз

2023-07-18 10:41 UTC, NiKuma0 commented on src/bot/handlers/categories.py
> +async def select_subcategory_callback(update: Update, context: ContextTypes.DEFAULT_TYPE):
А где  регистрируются эти хендлеры?

2023-07-18 10:41 UTC, NiKuma0 commented on src/bot/handlers/tasks.py
> +from src.bot.handlers.categories import back_subcategory_callback, select_subcategory_callback, subcategories_callback
Этого не надо. Регистрируй хендлеры там же где объявляешь.

2023-07-20 11:17 UTC, NiKuma0 requested changes

2023-07-20 11:17 UTC, NiKuma0 commented on src/bot/handlers/categories.py
> +def registration_handlers(app: Application):
У нас теперь две одинаковые функции в одном файле? Давай их объединим.

2023-07-23 10:21 UTC, NiKuma0 approved these changes

2023-07-23 10:22 UTC, NiKuma0 commented
Поправь ошибки `pre-commit`, и можно мержить.

2023-07-23 18:30 UTC, igor-sidorov commented
> Поправь ошибки `pre-commit`, и можно мержить.

Поправил

2023-07-24 16:48 UTC, merged