Добавлена информация о проекте, окружении и боте ТГ
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #14
Opened 2023-04-12 19:16 UTC by albaranovsky

2023-04-12 19:59 UTC, NiKuma0 commented on README.md
> +> Необходимы для дальнейшей разработки приложения.
Ну давай так и назовём этот блок - Зависимости для разработки

2023-04-12 20:01 UTC, NiKuma0 commented on README.md
> +2. Изменить конфигурацию Poetry (опционально).
Это на любителя, оставь в документации, здесь не надо.

2023-04-12 20:01 UTC, NiKuma0 commented on README.md
> +> Необходимы для дальнейшей разработки приложения.
Ну давай так и назовём этот блок - Установка зависимостей для разработки

2023-04-12 20:04 UTC, NiKuma0 commented on README.md
> +1. Установить, следуя официальным инструкциям.
Слишком большой блок получается. Думаю лучше описать как установить зависимости с помощью `poetry`, где первым делом кидаем ссылку на документацию по установке.

2023-04-12 20:08 UTC, NiKuma0 commented on README.md
> +#### Регистрация бота Telegram
Оставь ссылку на оф документацию по созданию бота.

2023-04-13 19:15 UTC, albaranovsky commented
Поменял структуру, сильно сократить не получилось ... Возможно, имеет смысл убрать раздел Работа с БД? Там по сути базовые вещи про  Alembic.

2023-04-14 09:43 UTC, NiKuma0 requested changes
Не исправил артефакты.

2023-04-14 09:43 UTC, NiKuma0 commented on README.md
> +    > Необходимо доменное имя с установленным SSL-сертификатом.
Можно без ssl и нгрок

2023-04-15 19:06 UTC, NiKuma0 approved these changes
lgtm

2023-04-15 19:06 UTC, merged