Feature/add filter for user tasks by category
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #140
Opened 2023-07-19 13:05 UTC by VadimVolkovsky

Таска #128 

Изменения:
view_task_callback - добавлен параметр user_telegram_id
TaskService - добавлен параметр user_telegram_id
TaskRepository - добавлена фильтрация по пользователю и is_archived==False
fill_db.py - исправлен баг с заливкой id категорий в tasks (заливались parrent_id вместо id сабкатегорий)

2023-07-20 11:14 UTC, NiKuma0 requested changes
Расскажи как тестировал.

2023-07-20 11:14 UTC, NiKuma0 commented on src/core/db/repository/task.py
> +            .where(and_(Category.users.any(id=user_id)), Task.is_archived == false())
Давай вместо `and_` использовать дополнительный `where`
```suggestion
            .where(Category.users.any(id=user_id))
            .where(Task.is_archived == false())
```

2023-07-20 11:14 UTC, NiKuma0 commented on src/core/db/repository/task.py
> +            .where(and_(Category.users.any(id=user_id)), Task.is_archived == false())
```suggestion
            .where(Category.users.any(id=user_id)) 
            .where(Task.is_archived == false())
```

2023-07-20 11:14 UTC, NiKuma0 commented on src/core/db/repository/task.py
> +            .options(joinedload(Task.category))
А зачем тут join и joinload?

2023-07-20 11:14 UTC, NiKuma0 commented on src/core/db/repository/task.py
> +        user_id = await self._session.scalar((select(User.id).where(User.telegram_id == user_telegram_id)))
Что-то подобное есть уже в `UserRepository`. Предлагаю в сервисе вызвать `UserRepository.get_by_telegram_id`, а этот метод будет принимать уже объект `User`, не `telegram_id`.

2023-07-20 11:14 UTC, NiKuma0 commented on src/core/db/repository/task.py
>          return len(tasks.all())
Давай будет считать кол-во тасков на стороне БД.

2023-07-21 12:26 UTC, VadimVolkovsky commented on src/core/db/repository/task.py
> +            .options(joinedload(Task.category))
Без них у меня никак не получается реализовать:

Если убрать `.join(Category)`, то не работает фильтрация по категориям (возвращаются таски всех категорий)
Если убрать `joinedload(Task.category)`, то выпадает ошибка при запросе заданий (на скрине). Как ее обойти так и не смог разобраться.

![image](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/103027888/d033494b-62bb-4e09-b7dc-a085e247b9f1)

2023-07-21 13:56 UTC, VadimVolkovsky commented
> Расскажи как тестировал.

Тестировал через телегу и DBeaver
Набрал себе заданий из разных категорий, и проверял что при запросе в телеге и по api отображаются только задания соответствующие моим выбранным категориям.
+ тестил пагинацию в телеге, там теперь тоже отображается корректное кол-во оставшихся задач с учетом показанных.

2023-07-23 09:40 UTC, NiKuma0 approved these changes

2023-07-23 09:40 UTC, NiKuma0 commented on src/bot/handlers/tasks.py
Вообще `show_next_tasks` - должна заниматься исключительно отрисовкой тасков, а она еще и неожиданно вызывает сервис... Передай сюда сразу все нужные аргументы - `remaining_tasks`, `page_number` а все остальное оставь сервисам либо хендлерам.

2023-07-24 16:46 UTC, merged