feature/task_mailing_notification_to_users
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #142
Opened 2023-07-20 05:35 UTC by ArtemBalandin81

2023-07-20 11:24 UTC, NiKuma0 requested changes

2023-07-20 11:24 UTC, NiKuma0 commented on src/api/endpoints/tasks.py
> +        await telegram_notification_service.send_messages_to_all_users(message)
Оберни это в отдельный сервис.

2023-07-20 11:24 UTC, NiKuma0 commented on src/api/endpoints/tasks.py
> +        await telegram_notification_service.send_messages_to_all_users(message)
Нужно не просто всем пользователям отправить сообщения, а только тем кто подписан на категорию - `Task.category.users`

2023-07-24 04:14 UTC, ArtemBalandin81 commented on src/api/endpoints/tasks.py
> +        await telegram_notification_service.send_messages_to_all_users(message)
Пока не упаковал в отдельный сервис, но работаю над этим.
Правильно понимаю - что лучше упаковать в api TaskService?
Делаю разолв, чтобы запушить то, что удалось реализовать с уведомлением "подписанных пользователей"

2023-07-24 20:50 UTC, NiKuma0 requested changes

2023-07-24 20:50 UTC, NiKuma0 commented on src/api/endpoints/tasks.py
> +        added_task = await task_service.get_task_category_by_id(task.id)
А если у нас 1000 тасков, сколько будет запросов в БД?

2023-07-24 20:50 UTC, NiKuma0 commented on src/api/endpoints/tasks.py
> +        await telegram_notification_service.send_messages_to_subscribed_users(message, task.category_id)
Я не уверен что тут будут отправляться **новые** таски, т.к. от клиента мы получаем сразу все задачи что есть на сайте. Какие задачи новые а какие старые узнаем через `task_service.actualize_objcets` - метод можно поправить, чтобы он возвращал их.

2023-07-25 03:57 UTC, ArtemBalandin81 commented on src/api/endpoints/tasks.py
> +        added_task = await task_service.get_task_category_by_id(task.id)
Никита, я понимаю о чем речь и действительно упустил этот момент.
Вопрос: если в качестве tasks мы берем не все таски, а только новые из метода task_service.actualize_objects можно ли оставить такую реализацию? Клиент (сайт) не будет ведь тысячами новых тасков спамить и потому несколько даже десятков запросов (если будет одновременно несколько новых десятков тасков) не критично?

2023-07-25 03:59 UTC, ArtemBalandin81 commented on src/api/endpoints/tasks.py
> +        added_task = await task_service.get_task_category_by_id(task.id)
Поправил таски на task_service.actualize_objects и зашлю на ревью, для полноты картины.
А если нужно все же поправить эту часть, займусь ей дополнительно. Пока снимаю резолв для пула

2023-07-27 15:40 UTC, NiKuma0 requested changes

2023-07-27 15:40 UTC, NiKuma0 commented on src/api/endpoints/tasks.py
>          added_task = await task_service.get_task_category_by_id(task.id)
Лучше сразу все категории подгружать, чтобы не было 100+ запросов в БД, а один.

2023-07-28 16:30 UTC, NiKuma0 commented on src/core/db/repository/task.py
> +        return task.first()
```suggestion
        return await self._session.scalar(select(Task).options(joinedload(Task.category)).where(Task.id == task_id))
```

2023-07-29 02:31 UTC, ArtemBalandin81 commented on src/core/db/repository/task.py
> +        return task.first()
Тут мы пытаемся избавиться от лишней константы?
Если так сделать то вылетает в ошибку:
AttributeError: 'ScalarResult' object has no attribute 'deadline'

Теряется return task.first()

2023-07-29 03:19 UTC, ArtemBalandin81 commented on src/api/endpoints/tasks.py
>          added_task = await task_service.get_task_category_by_id(task.id)
Кажется, решение намного проще, чем думалось:
.options(joinedload(Task.category))
            .where(Task.id.in_(ids))

2023-07-30 11:36 UTC, NiKuma0 approved these changes

2023-07-30 11:36 UTC, merged