Feature/inline form
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #144
Opened 2023-07-20 18:48 UTC by thesupercalifragilisticexpialidocious

closes #134

2023-07-23 10:09 UTC, NiKuma0 requested changes

2023-07-23 10:09 UTC, NiKuma0 commented on src/bot/keyboards.py
>      user_service = UserService()
Давай тут без сервиса, пусть эта функция вместо `telegram_id` будет принимать `user: User`. Тогда даже можно отказаться от `UserService.get_mailing()`

2023-07-23 17:44 UTC, thesupercalifragilisticexpialidocious commented
Убрал юзерсервис из клавиатуры

2023-07-24 11:36 UTC, NiKuma0 approved these changes

2023-07-24 11:36 UTC, merged