add_details_for_tasks
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #145
Opened 2023-07-22 18:53 UTC by KonstKorn

2023-07-23 10:03 UTC, NiKuma0 requested changes

2023-07-23 10:03 UTC, NiKuma0 commented on src/bot/handlers/tasks.py
> +    task_id = int(query.data.split("_")[2])
Посмотри как это сделано в других частях проекта. Используй объект `match`

2023-07-23 10:03 UTC, NiKuma0 commented on src/bot/handlers/tasks.py
> +    description = task.description
Зачем тут отдельная переменная?

2023-07-23 10:03 UTC, NiKuma0 commented on src/bot/handlers/tasks.py
> +        text=f"{description} для {task.name_organization}",
Посмотри как выглядеть `display_task` - тебе нужно тоже самое, только чтобы внизу был `description`

2023-07-23 13:31 UTC, KonstKorn commented
@NiKuma0 привел код в соответствие согласно комментариям

2023-07-24 20:38 UTC, NiKuma0 commented on src/bot/handlers/tasks.py
> +    detailed_text = f"{current_text}\n\n{task.description}"
Не думаю что это хорошая идея... Лучше создай отдельную функцию `display_task_verbosely` и там формируй текст с нуля, как в `display_task`

2023-07-24 20:38 UTC, NiKuma0 commented on src/core/db/repository/task.py
> +    async def get_task_by_id(self, task_id: int) -> Task:
Разве нет подобной функции в `AbstractRepository`?

2023-07-24 21:26 UTC, KonstKorn commented on src/bot/handlers/tasks.py
> +    detailed_text = f"{current_text}\n\n{task.description}"
Но если писать display_task_verbosely с таким же текстом как display_task, то эти  функции будут дублироваться (за исключением всего одно строки).

2023-07-24 21:37 UTC, KonstKorn commented on src/core/db/repository/task.py
> +    async def get_task_by_id(self, task_id: int) -> Task:
Увлекся) заменил на get_or_none)

2023-07-26 10:46 UTC, NiKuma0 commented on src/bot/handlers/tasks.py
> +    detailed_text = f"{current_text}\n\n{task.description}"
Сейчас да. Скорее всего у заказчика появится идея как лучше сделать подробный вид, тогда функция сильно изменится.

2023-07-26 19:20 UTC, KonstKorn commented on src/core/db/repository/task.py
> +    async def get_task_by_id(self, task_id: int) -> Task:
Тут все же пришлось писать новую функцию. get_or_none не подходит)

2023-07-26 19:20 UTC, KonstKorn commented on src/bot/handlers/tasks.py
> +    detailed_text = f"{current_text}\n\n{task.description}"
Понял. Сделал.

2023-07-26 21:18 UTC, NiKuma0 approved these changes

2023-07-26 21:18 UTC, merged