Feature/external sire user spicializations
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #157
Opened 2023-08-01 14:24 UTC by VadimVolkovsky

Замеченные баги: не подтягивается email и external_id пользователя из таблицы external_site_user в таблицу users (при регистрации через телегу)

2023-08-01 15:11 UTC, VadimVolkovsky commented
Почему-то деплой не прошел, непонятно =/
Stage backend build and deploy / Start application (push)  - Failing after 34s

2023-08-01 18:35 UTC, NiKuma0 requested changes

2023-08-01 18:35 UTC, NiKuma0 commented on src/api/schemas.py
> +    specializations: Optional[list[int]] | None
Конструкция `Optional[...]` и `... | None` обозначают одно и тоже. Ты их как то объединил...
```suggestion
    specializations: list[int] | None
```

Также, как я описал в задаче, мы будем принимать от клиента строку, примерно как: `"1, 2, 3"` . Нужно добавить валидатор, чтобы с ней также работала.

2023-08-01 18:39 UTC, NiKuma0 commented
> Замеченные баги: не подтягиваются email и external_id пользователя из таблицы external_site_user в таблицу users (при регистрации через телегу по id_hash)

Можешь пофиксить? Вроде не сложно, просто добавить пару строк) 

> Почему-то запуск приложения на тестах не прошел, непонятно =/
Stage backend build and deploy / Start application (push) - Failing after 34s

Уже думаю над этим - по всей видимости у нас не хватает RAM на сервере...

2023-08-02 13:42 UTC, VadimVolkovsky commented
> > Замеченные баги: не подтягиваются email и external_id пользователя из таблицы external_site_user в таблицу users (при регистрации через телегу по id_hash)
> 
> Можешь пофиксить? Вроде не сложно, просто добавить пару строк)

Поправил

2023-08-02 13:42 UTC, VadimVolkovsky commented on src/api/schemas.py
> +    specializations: Optional[list[int]] | None
Добавил валидатор строки через регулярку

2023-08-02 21:54 UTC, NiKuma0 commented on src/api/schemas.py
> +    specializations: list[int] | str = Field(None)
Я так понимаю тут `Field(None)` потому что линтер ругаеться)
Добавь `... | None = None`. Также, в идеале чтобы тут был именно `list[int]` а не `list[int] | str` - насколько знаю, это можно обойти с помощью валидатора, нужно его настроить чтобы он срабатывал до стандартных `mode="before"`

2023-08-02 21:54 UTC, NiKuma0 commented on src/api/schemas.py
> +        if isinstance(value, str):
Как то много вложенности - попробуй `not`: 
```suggestion
        if not isinstance(value, str):
            return value
```

2023-08-04 11:20 UTC, VadimVolkovsky commented on src/api/schemas.py
> +    specializations: list[int] | str = Field(None)
добавил mode='before'
Получается теперь так:
Явно мы можем передать в поле specializations только list[int].
Не явно можем передать еще строку, и если она была передана, то регуляркой валидируется содержание этой строки (например чтобы нельзя было передать "1, asd, 2, 3")

2023-08-04 18:40 UTC, NiKuma0 approved these changes

2023-08-04 18:40 UTC, merged