Bot services: notifications sending
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #16
Opened 2023-04-14 16:14 UTC by elych-ru

[Задача](https://www.notion.so/18196298bc204a7cbad854d9dfaa449a?pvs=4)
Класс рассылки уведомлений в телеграм.

Изменил pyproject.toml: добавил установку rate limiter в PTB - вещь однозначно нужная, имеет смысл встроить сразу. Ограничивает рассылку сообщений сверх лимита ТГ. В "барьерах" аналогично.

Класс TelegramNotification написан в соответствии с заданием.
Класс пока простой, потом можно добавить функционал.
Протестирован: всё работает, сообщения отправляются, и ошибки обрабатываются именно так, как предполагается (пока их две: id юзера не найден - BadRequest и юзер заблокировал бота - Forbidden).
Логгинг добавлен пока "чтобы был" (и чтобы не забыть о выводимых ошибках), потом надо импортировать наш, который потом появится.
Ориентируясь на принципы SOLID, класс не делает лишнего (как у соседей - старого бота или "барьеров") - т.е. не пытается записать в БД признак того, что юзер заблокировал бота или не найден: делать это должен вызывающий код, а сам класс только шлёт сообщения в ТГ. У функции отправки сообщений есть параметр "mark_user_for_banned_flag" (по умолчанию False) - если установлен в True, то при ошибке отправки он выставит у объекта пользователя признак "banned" в True, и вызвавший код сможет это сохранить в БД при желании.
Функция отправки возвращает True (в задании было вернуть bool), но можно переписать и возвращать что-то более осмысленное.
В init нужно передавать инстанс бота, т.е. объект app.state.bot_instance (см. application.py).

2023-04-14 18:54 UTC, NiKuma0 requested changes

2023-04-14 18:54 UTC, NiKuma0 commented on src/bot/services.py
> +        self.__bot_application = telegram_bot
Кажется это нигде не используется.

2023-04-14 18:54 UTC, NiKuma0 commented on src/bot/services.py
> +        mark_user_for_banned_flag: bool = False,
Не вижу тут смысла. А если бота разбанили, как это понять? Проще вообще этот флаг не использовать, поэтому убери.

2023-04-14 18:54 UTC, NiKuma0 commented on src/bot/services.py
> +                await self.__bot.send_message(chat_id=user.telegram_id, text=message)
тут давай использовать `asyncio.gather`, [как в ломая барьеры](https://github.com/Studio-Yandex-Practicum/lomaya_baryery_backend/blob/develop/src/bot/services.py#L104)

2023-04-15 12:26 UTC, elych-ru commented on src/bot/services.py
> +        mark_user_for_banned_flag: bool = False,
Юзер может снова запустить /start в боте. А так получится, что будем всегда всем рассылать, игнорируя ошибки.
Ну ок, убрал.

2023-04-15 13:29 UTC, elych-ru commented on src/bot/services.py
> +        self.__bot_application = telegram_bot
Пригодилось в новой версии для вызова 
self.__bot_application.create_task(asyncio.gather(*send_message_tasks))

2023-04-15 13:43 UTC, elych-ru commented
@NiKuma0, я закоммитил изменения по замечаниям ревью.

2023-04-16 09:04 UTC, NiKuma0 approved these changes

2023-04-16 09:04 UTC, NiKuma0 commented on src/bot/services.py
> +class TelegramNotification:
Давай переместим этот класс в `core`. Это общий класс, он будет использоваться и в API и в боте.

2023-04-16 15:49 UTC, elych-ru commented on src/bot/services.py
> +class TelegramNotification:
src/core/services?
как назвать модуль?

2023-04-17 07:41 UTC, merged