Добавление фронта
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #164
Opened 2023-08-05 05:58 UTC by thesupercalifragilisticexpialidocious

closes #147 
- Репо фронта привязано как субмодуль
- Конфигурация nginx для фронта
- Новый докерфайл для фронта
- Добавления фронта в докер-композ
- Новый воркфлоу для сборки и пуша образа фронта
- Корректировки в основной воркфлоу

2023-08-06 13:04 UTC, NiKuma0 requested changes
Поправь конфликт.

2023-08-06 13:04 UTC, NiKuma0 requested changes
Поправь конфликт.

2023-08-07 03:39 UTC, thesupercalifragilisticexpialidocious commented on .github/workflows/deploy_stage.yaml
> +            REACT_APP_API_URL=https://procharity.duckdns.org/
попробую без этого. было в .env фронта

2023-08-07 11:01 UTC, NiKuma0 requested changes
Попробуй подключиться к `/docs/` и `/static/feedback_form/feedback_form.html` в следующих тестах.

2023-08-07 11:52 UTC, thesupercalifragilisticexpialidocious commented on infra/nginx/swag.conf
> +'"$http_referer" "$http_user_agent" "$gzip_ratio"';
токены нас учили для безопасности отключать.
дальше формат логирование, этот шаблон из фронтовых конфигов. полагаю, этот формат был усмотрен оптимальным.

2023-08-07 12:01 UTC, thesupercalifragilisticexpialidocious commented on infra/nginx/swag.conf
> +    location /api/ {
админка вроде должна из ```/``` запускаться

2023-08-07 13:01 UTC, thesupercalifragilisticexpialidocious commented on infra/nginx/swag.conf
> +        try_files /var/html$uri /usr/share/nginx/html$uri =404;
это конструкция должна проверять статик-файлы сразу в двух местах.
/var/html
и
/usr/share/nginx/html

https://procharity.duckdns.org/static/feedback_form/feedback_form.html открывается

2023-08-07 13:03 UTC, thesupercalifragilisticexpialidocious commented on infra/nginx/swag.conf
> +'"$http_referer" "$http_user_agent" "$gzip_ratio"';
там ниже еще одна директива server_tokens off; была, поэтому бэк падал.
убрал свою строчку.

2023-08-10 12:28 UTC, NiKuma0 commented on .github/workflows/deploy_stage.yaml
> +      - feature/deployment-of-admin-tools
Убери свою ветку. Этот воркфлоу можно запускать вручную, где можно указать нужную ветку.

2023-08-10 12:28 UTC, NiKuma0 commented on .github/workflows/push_front.yaml
> +      - feature/deployment-of-admin-tools
Тут также, убери ветку.

2023-08-10 12:28 UTC, NiKuma0 commented on .github/workflows/push_front.yaml
> +  DEPLOY_PATH: /code
Кажется эта переменная нигде не используется. Удали все использующейся переменные.

2023-08-10 12:28 UTC, NiKuma0 commented on infra/docker-compose.swag.yml
>        - static:/var/html/static/:ro
Почему у нас `frontend_build` и `static` в разных папках? Укажи одну `/usr/share/nginx/html/` или `/var/html`

2023-08-10 12:28 UTC, NiKuma0 commented on infra/nginx/swag.conf
> +'"$http_referer" "$http_user_agent" "$gzip_ratio"';
Вот это зачем? Если есть причина, добавь комментарий зачем и ссылку где можно об этом почитать.

2023-08-13 06:14 UTC, thesupercalifragilisticexpialidocious commented on infra/nginx/swag.conf
> +'"$http_referer" "$http_user_agent" "$gzip_ratio"';
Это форматирование из фронт-докера. Видимо коллегам показалось, что такой формат логов особо удачен. Я удалю, если ты не видишь в нем смысла.

2023-08-13 10:41 UTC, NiKuma0 approved these changes

2023-08-13 10:41 UTC, merged