feature/add_webhook_ERRORS
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #168
Opened 2023-08-08 19:45 UTC by ArtemBalandin81

1.  Подготовил эндпоинт api.
2. Проверил работу ngrok с webhook - работает автоматом, вручную ничего не нужно посылать в телеграм.
3. Уперся в request_json_data = await request.json()
!!! возникает ошибка "пустой первой строки": jsondecodeerror: expecting value: line 1 column 1 (char 0):
- на форумах отмечают следующие причины: попытка парсить пустую строку; одинарные кавычки, вместо ожидаемых двойных; наличие лишних символов в строке; нарушенная структура и пр.
Если сделать запрос print(request.scope) - то вывод в терминал вполне рабочий, данные имеются, тип - словарь.
Попытка сериализовать словарь request.scope в json - также упирается в TypeError: Object of type bytes is not JSON serializable

2023-08-13 10:12 UTC, NiKuma0 requested changes

2023-08-13 10:12 UTC, NiKuma0 commented on src/api/endpoints/telegram_webhook.py
> +if settings.BOT_WEBHOOK_MODE:
Вот этого точно не надо. Мы стараемся писать функциональный-объектный код, а не процедурный - убери логику. Проверяй в самой функции эту переменную, если там будет `BOT_WEBHOOK_MODE=False` возвращай ошибку.

2023-08-13 10:12 UTC, NiKuma0 commented on src/settings.py
> +    BOT_WEBHOOK_MODE: bool = True
Оставь по дефолту - False

2023-08-13 10:20 UTC, NiKuma0 commented
> * что должен отдавать апи вебхука при прямом обращении к нему? Или он служит техническим адресом для получения обновлений от телеграм и передачи их в бот? Однако, эндпоинт подразумевает отдачу этого ответа: return request_json_data, но как и где это предполагается использоваться? Сейчас при обращении вызывается исключение.

Он не должен ничего возвращать, он только принимает Update от телеграма. [Вот тут](https://core.telegram.org/bots/webhooks) очень хорошо про это описано.

> * несмотря на то, что бот работает и все функционирует, в логах появляются ошибки:
>   при открытии меню - AttributeError: 'NoneType' object has no attribute 'message' (меню при этом открывается)
>   посмотреть откр. задания - BadRequest: Message to delete not found (задания при этом отображаются)

Это возьму на заметку, кажется знаю где ошибка. Это только с вебхуками так?

2023-08-13 14:16 UTC, ArtemBalandin81 commented on src/api/endpoints/telegram_webhook.py
> +if settings.BOT_WEBHOOK_MODE:
Принято. Но подобная реализация позволяет скрывать/отображать в апи наличие этого эндпоинта. Думал - так задумано)

2023-08-15 08:40 UTC, NiKuma0 approved these changes

2023-08-15 08:40 UTC, merged