Feature/add di in bot
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #179
Opened 2023-08-19 16:25 UTC by VadimVolkovsky

драфт версия внедрения Dependency injector

апишка и БД запускается, но с моим ботом пока не работает (он не видит сообщения) 
разбираюсь в причинах.

2023-08-21 14:01 UTC, NiKuma0 requested changes

2023-08-21 14:01 UTC, NiKuma0 commented on src/main.py
> +            fastapi_app.state.bot_instance = await startup_bot()
Вот тут ошибка. Функцию `startup_bot` не обновил. Сделаяй так чтобы она принимала бот и запускала его.

2023-08-21 14:16 UTC, NiKuma0 requested changes

2023-08-21 14:16 UTC, NiKuma0 commented on pyproject.toml
> +dependency-injector = "^4.41.0"
Добавь в `requirements.txt`

2023-08-21 14:16 UTC, NiKuma0 commented on src/application.py
Этот файл можно спокойно удалять.

2023-08-21 14:16 UTC, NiKuma0 commented on src/depends.py
> +    session = providers.Resource(get_session)
По хорошему `get_session` должна принимать `sessionmaker`.

2023-08-21 14:16 UTC, NiKuma0 commented on src/depends.py
> +    sessionmaker = providers.Singleton(async_sessionmaker)
Этот `sessionmaker` не будет работать - не хватает аргументов. Нужен `engine` и `expire_on_commit`

2023-08-21 14:16 UTC, NiKuma0 commented on src/main.py
> +def init_app(fastpi_app: FastAPI) -> FastAPI:
Это перенеси в `src/api`

2023-08-21 14:16 UTC, NiKuma0 commented on src/main.py
> +def init_bot(telegram_bot: Application) -> Application:
Это перенеси в `src/bot/`

2023-08-21 14:16 UTC, NiKuma0 commented on src/bot/bot.py
>  from src.settings import settings
Теперь когда есть DI, от такой глобальной переменной можно отказаться - пока оставь чтобы работал старый код, но в новом используй DI контейнер.

2023-08-21 14:16 UTC, NiKuma0 commented on src/main.py
> +from src.settings import settings
Тут также - откажись от этой переменной, используй DI контейнер.

2023-08-23 09:58 UTC, VadimVolkovsky commented on src/bot/bot.py
>  from src.settings import settings
А как правильно использовать контейнер settings ? Сделал по доке, но тогда возникает циклический импорт, не могу придумать как его обойти. 

![image](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/103027888/e36b2deb-7018-4122-b7ad-222c265d8b67)

2023-08-23 10:05 UTC, VadimVolkovsky commented on src/depends.py
> +    session = providers.Resource(get_session)
Тут не пойму почему при создании контейнера session не передается аргумент sessionmaker


![image](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/103027888/5b9896e9-d0d5-4db9-9fa0-ae1859865b21)

![image](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/103027888/6cd6e3d6-0411-46cf-853d-a216c4eeb8fb)

2023-08-23 10:27 UTC, VadimVolkovsky commented on src/bot/bot.py
>  from src.settings import settings
Тогда вопрос, нужно ли `start_bot` избавлять от settings :)) я поэтому и хотел всех сеттинги передать

![image](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/103027888/5d983a6f-e740-4ff2-80c9-1ce9e41b09fc)

2023-08-23 11:20 UTC, NiKuma0 commented on src/bot/bot.py
>  from src.settings import settings
Да, также избавь. Также будет логичнее, если не весь сетиинг передавать, а только `webhook_mode`

2023-08-23 11:27 UTC, NiKuma0 commented on src/main.py
> +from src.settings import settings
Попробуй использовать wiring:
```python
@inject
async def on_startup(use_ngrok: bool = Provide[Container.settings.USE_NGROK]): ...
```
Возможно что так работать не будет, тогда твое решение приемлемо.

P.S. Поменяй местами запуск ngrok (`seet_ngrok`) и запуск бота. Это давний баг, ты мне его напомнил)

2023-08-23 12:04 UTC, NiKuma0 commented on src/depends.py
> +    session = providers.Resource(get_session)
Это ошибка со стороны FastAPI - добавь дефолтное значение sessionmaker.

2023-08-23 12:22 UTC, VadimVolkovsky commented on src/main.py
> +from src.settings import settings
> ```python
> @inject
> async def on_startup(use_ngrok: bool = Provide[Container.settings.
> ```

так вылетает с ошибкой:
`AttributeError: 'dependency_injector.providers.Singleton' object has no attribute 'USE_NGROK'
`

а если так:
` async def on_startup(use_ngrok: bool = Provide[Container.settings.provided.USE_NGROK]):`

то возвращает объект Provide:
`use_ngrok: <dependency_injector.wiring.Provide object at 0x000002A791194890>`
Пока не понял как получить значение этого объекта. 

[В доке](https://python-dependency-injector.ets-labs.org/wiring.html) все настройки проекта видимо хранят в config.ini и к их значениям обращаются вот так:
`(value1: int = Provide[Container.config.value1])`

2023-08-23 12:39 UTC, NiKuma0 commented on src/main.py
> +from src.settings import settings
Хорошо, можно оставить как есть. Но если есть время, можешь попробовать использовать Configuration провайдер (он [поддерживает pydantic](https://python-dependency-injector.ets-labs.org/providers/configuration.html#loading-from-a-pydantic-settings), поэтому проблем быть не должно), может он именно для такой конструкции и был предназначен)

2023-08-23 13:12 UTC, VadimVolkovsky commented on src/depends.py
> +    session = providers.Resource(get_session)
Дефолтное значение `async_sessionmaker` добавил

```
async def get_session(sessionmaker=async_sessionmaker) -> Generator[AsyncSession, None, None]:
    async with sessionmaker() as session:
        yield session
```

Но почему-то таким образом async_sessionmaker нельзя прогнать через асинхронный контекстный менеджер:
 `TypeError: 'async_sessionmaker' object does not support the asynchronous context manager protocol
`
Видимо потому что он дефолтное значение `sessionmaker` вызывает, т.е. получается`sessionmaker` все равно не передается в `get_session`

2023-08-23 14:03 UTC, VadimVolkovsky commented on src/bot/bot.py
>  from src.settings import settings
Вроде получилось. Но, есть сомнения, что эта штука `if BOT_WEBHOOK_MODE is True:` работает:

```
async def start_bot(
        bot: Application,
        BOT_WEBHOOK_MODE: bool,
        telegram_webhook_url: str,
        SECRET_KEY: str
) -> Application:
    """Запуск бота в `Background` режиме."""
    await bot.initialize()
    if BOT_WEBHOOK_MODE is True:
```

2023-08-23 14:44 UTC, VadimVolkovsky commented on src/main.py
> +from src.settings import settings
> Хорошо, можно оставить как есть. Но если есть время, можешь попробовать использовать Configuration провайдер (он [поддерживает pydantic](https://python-dependency-injector.ets-labs.org/providers/configuration.html#loading-from-a-pydantic-settings), поэтому проблем быть не должно), может он именно для такой конструкции и был предназначен)

Похоже это то, что нужно...

```
class Container(containers.DeclarativeContainer):
    config = providers.Configuration(pydantic_settings=get_settings())
```

Но он почему-то не хочет дружить с нами, хотя у нас вроде актуальная версия pydantic
```

 File "C:\Dev\ProCharity_back_2.0\src\main.py", line 11, in main
    container = Container()
                ^^^^^^^^^^^
  File "src/dependency_injector/containers.pyx", line 742, in dependency_injector.containers.DeclarativeContainer.__new__
  File "src/dependency_injector/containers.pyx", line 393, in dependency_injector.containers.DynamicContainer.load_config
  File "src/dependency_injector/providers.pyx", line 2106, in dependency_injector.providers.Configuration.load
  File "src/dependency_injector/providers.pyx", line 2381, in dependency_injector.providers.Configuration.from_pydantic
  File "C:\Users\Virus\AppData\Local\pypoetry\Cache\virtualenvs\procharity-back-2-0-FpLSYL19-py3.11\Lib\site-packages\pydantic\__init__.py", line 210, in __getattr__
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Virus\AppData\Local\pypoetry\Cache\virtualenvs\procharity-back-2-0-FpLSYL19-py3.11\Lib\site-packages\pydantic\_migration.py", line 289, in wrapper
    raise PydanticImportError(
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.1.1/migration/#basesettings-has-moved-to-pydantic-settings for more details.

For further information visit https://errors.pydantic.dev/2.1.1/u/import-error
```

2023-08-24 08:43 UTC, NiKuma0 reviewed
Нужно немного поправить коде стайл.

2023-08-24 08:43 UTC, NiKuma0 commented on src/bot/bot.py
> +    bot: Application, BOT_WEBHOOK_MODE: bool, telegram_webhook_url: str, SECRET_KEY: str
Капсом пишут константы, а это аргумент функции, он не может быть константой 
```suggestion
    bot: Application, weebhook_mode: bool, telegram_webhook_url: str, secret_key: str

```

2023-08-24 08:43 UTC, NiKuma0 commented on src/bot/bot.py
> +    bot: Application, BOT_WEBHOOK_MODE: bool, telegram_webhook_url: str, SECRET_KEY: str
Тут также убери капс.

2023-08-24 08:43 UTC, NiKuma0 commented on src/depends.py
> +    config = providers.Configuration()
Мы его нигде не используем, можно удалить.

2023-08-24 08:43 UTC, NiKuma0 commented on src/depends.py
> +    telegram_bot = providers.Singleton(create_bot, bot_token=settings.provided.BOT_TOKEN)
Раздели все комментариями, чтоб тут не был монолитный текст - `# Settings`, `# Database connection` и т.д.

2023-08-24 08:43 UTC, NiKuma0 commented on src/run_api.py
Этот файл можно спокойно удалять.

2023-08-24 08:43 UTC, NiKuma0 commented on src/run_bot.py
Этот файл можно удалить.

2023-08-25 11:14 UTC, NiKuma0 approved these changes

2023-08-25 11:14 UTC, merged