feature/add_healthcheck_bot_checkup
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #180
Opened 2023-08-21 05:07 UTC by ArtemBalandin81

Набросал вариант первой проверки - пока только бота. 
Разместил в эндпоинте аналитики. Мне показалось так логичнее
Продолжаю работу над проверкой базы и последнего коммита.

2023-08-22 09:44 UTC, NiKuma0 requested changes

2023-08-22 09:44 UTC, NiKuma0 commented on src/api/services/health_check.py
> +            logging.info("Health check: Bot connection succeeded")
Тут не правильно используешь библиотеку `logging` (нужно сначала инициализировать `logger`) - к тому же мы используем `structlog`. Думаю этот лог не много бесполезен.

2023-08-22 09:44 UTC, NiKuma0 commented on src/api/services/health_check.py
> +                return dict(status="True", method="webhooks", url=webhook_info.url)
Лучше используй модели pydantic.

2023-08-22 09:44 UTC, NiKuma0 commented on src/api/services/health_check.py
> +                return dict(status="True", method="webhooks", url=webhook_info.url)
Вообще сервис не должен заниматься отрисовкой, чем и является модели pydantic. Вдруг мы захотим использовать этот сервис в боте? Там pydantic будет лишнем...

Поэтому можно оставить тут `dict` (но не во вьюхе, там добавь pydantic), но используй лучше [`TypedDict`](https://peps.python.org/pep-0589/).

2023-08-22 09:47 UTC, NiKuma0 commented
Посмотри структуру ответа в старом боте, у нас должна быть такая же, чтобы фронт работал)

2023-08-22 09:49 UTC, NiKuma0 commented
> Не до конца понимаю, что необходимо чекапить? Пока ответ такой:

Посмотри [структуру ответа из старого бота](https://github.com/ProCharity/ProCharity_bot/blob/develop/app/webhooks/health_check.py#L20), у нас должна быть такая же, чтобы фронт работал. От туда же, можно подсмотреть что нужно чекать)

2023-08-22 15:01 UTC, ArtemBalandin81 commented on src/api/services/health_check.py
> +                return dict(status="True", method="webhooks", url=webhook_info.url)
Немного запутался)
Вроде во вьюхах (это же эндпоинты в фастапи?) итак пайдентик использую?

@health_check_router.get(
    "/", description="Проверяет соединение с БД, ботом и выводит информацию о последнем коммите."
)
async def get_health_check(health_check_service: HealthCheckService = Depends()) -> HealthCheck:
    return HealthCheck(
        check_bot=await health_check_service.check_bot(),
        last_commit=await health_check_service.get_last_commit(),
    )

2023-08-22 15:26 UTC, NiKuma0 commented on src/api/services/health_check.py
> +                return dict(status="True", method="webhooks", url=webhook_info.url)
Ну да, только вот `check_bot` без него

2023-08-28 13:49 UTC, NiKuma0 requested changes

2023-08-28 13:49 UTC, NiKuma0 commented on src/api/services/health_check.py
> +            else:
Тут можно и без else.

2023-08-28 13:49 UTC, NiKuma0 commented on src/api/services/health_check.py
> +        self._container = Container()
Так делать нельзя - почитай [вики](https://www.notion.so/Wiki-017a7e5894604b75942b3ba9ac8ed092#ffaa6e9821ba4f889a462a59ad27aae3) и приложенные ссылки. Объект не должен сам создавать свои зависимости. Помимо этого, контейнер уже инициализирован, его не нужно так использовать. Добавь этот сервис в контейнер (`depends.py`) и там пропиши зависимости - `bot`, `engine` и т.п.

2023-08-28 13:49 UTC, NiKuma0 commented on src/core/db/db.py
> +    async with async_session() as session:
Может эта функция и будет работать со старым кодом, но точно не с новым. Прошлая версия работала? Я создал [по этому поводу issue](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/issues/185).

2023-08-28 13:49 UTC, NiKuma0 commented on src/core/db/repository/base.py
> +    async def get_last_update(self) -> str | None:
Кажется эта функция подходит и для `AbstractRepository`

2023-09-01 11:26 UTC, NiKuma0 reviewed
Поправь конфликт.

2023-09-01 11:26 UTC, NiKuma0 commented on src/api/services/health_check.py
> +                "commit_error": f"{exc}",
Давай добавим эти параметры в сеттинги, будет брать их из окружения. В таком случае, библиотека python-git будет нужна только в dev dependencies.

2023-09-01 13:52 UTC, ArtemBalandin81 commented on src/api/services/health_check.py
> +                "commit_error": f"{exc}",
Никита, я правильно понимаю:
1. Добавляем в settings переменную VERSION = False (TRUE - это workflow, False - это GIT)
2. Ее же добавляем в окружение .env
3. В зависимости от VERSION в HealthCheckService в функции проверки коммитов мы:
- либо используем GIT для получения данных о коммите, 
- либо подставляем пустые параметры из сеттингс
4. Библиотеку GIT переносим в dev

Не до конца представляю, что и как можно вытянуть из workflow для переменной VERSION.
Но ход мысли в ту сторону, или у тебя иные задумки?

2023-09-02 09:11 UTC, NiKuma0 commented on src/api/services/health_check.py
> +                "commit_error": f"{exc}",
Из workflow можно получить всю инфу об ветке и об последнем коммите. Можно обойтись без переменной `COMMIT_WORKFLOW_MODE`.

2023-09-02 09:17 UTC, NiKuma0 requested changes

2023-09-02 09:17 UTC, NiKuma0 commented on src/api/services/health_check.py
> +                "tags": settings.TAGS,
Сделай более подробную переменную `TAGS` - чтобы было ясно что это за теги.

2023-09-02 09:17 UTC, NiKuma0 commented on src/settings.py
> +    TAGS: list = []
```suggestion
    TAGS: list[str] = []
```

2023-09-02 09:17 UTC, NiKuma0 commented on src/settings.py
> +    TAGS: list = []
А парсится ли лист из .env файла?

2023-09-02 09:17 UTC, NiKuma0 commented on src/settings.py
> +    COMMIT_WORKFLOW_MODE: bool = False
Можно без этой переменной.

2023-09-02 09:17 UTC, NiKuma0 commented on src/api/services/health_check.py
> +from git.exc import InvalidGitRepositoryError
Это нужно обернуть в `try except` т.к. не везде эта библиотека будет установлена.

2023-09-03 03:51 UTC, ArtemBalandin81 commented on src/settings.py
> +    TAGS: list = []
Никита, я задам встречный вопрос: а нужны ли нам вообще теги?
В ветке develop их нет.
В краткой инструкции к проекту их тоже нет.
Возможно кто-то их использует, использует ли?
Они перекочевали из прошлого проекта и там они вытягивались из листа тегов - возможно они использовали их, а мы нет?

Вот как было у них:
    last_tag = repo.tags[-1]
    tag = str(last_tag) if master.commit == last_tag.commit else None

Относительно твоего вопроса - я не до конца понимаю, как теги должны парситься из .env
Тег проставляется в момент коммита по типу: git tag -a v1.4 -m "my version 1.4" и потом его можно вытянуть, если он есть. У нас нет, поэтому я поставил пустой лист как заглушку, временно

2023-09-06 09:15 UTC, NiKuma0 approved these changes

2023-09-06 09:15 UTC, NiKuma0 commented on src/api/services/health_check.py
> +        if str(os.getcwd()) == DOCKER_WORKDIR:
Не вижу смысла этой проверки. Если не будет репозитория, то мы вернем переменные из окружения.

2023-09-06 09:15 UTC, NiKuma0 commented on src/api/services/health_check.py
> +            Repo(os.getcwd())
Давай объединим два блока в один. В одном `try` [можно использовать несколько `except`ов ](https://docs.python.org/3/tutorial/errors.html#handling-exceptions). 
```suggestion
            repo = Repo(os.getcwd())
```

2023-09-06 09:15 UTC, NiKuma0 commented on src/api/services/health_check.py
> +        except NameError as exc:
Не вижу ошибку `ImportError`, нужно ее тоже обработать.

2023-09-06 09:15 UTC, NiKuma0 commented on src/api/services/health_check.py
> +            return commit_status
Это можно объединить с первым блоком: 
```suggestion
        except (InvalidGitRepositoryError, NameError) as exc:
            commit_status: CommitStatus = {
                "last_commit": settings.LAST_COMMIT,
                "commit_date": settings.COMMIT_DATE,
                "git_tags": settings.TAGS,
                "commit_error": f"{exc.__name___}: {exc}",
            }
            return commit_status
```

2023-09-06 09:39 UTC, NiKuma0 requested changes
Потестил на сервере, падает с ошибкой - `TypeError: Cannot read properties of undefined (reading 'last_update')`. По всей видимости, не тот формат json. У тебя: 
```json
{
  "check_db_connection": { ... },
  "check_bot": { ... },
  "last_commit": { ... }
}
```
Фронт ожидал:
```json
{
  "db": { ... },
  "bot": { ... },
  "git": { ... }
}
```
Посмотри внимательнее [старый код](https://github.com/ProCharity/ProCharity_bot/blob/develop/app/webhooks/health_check.py#L23)...

2023-09-07 02:46 UTC, ArtemBalandin81 commented
Поправил выдачу под ожидаемые ключи:
{
  "db": { ... },
  "bot": { ... },
  "git": { ... }
}

В git выдача не совпадает с прошлым апи (теги и ошибка включены в словарь)
В прежней версии было:
last_commit: str
commit_date: strftime
tag: str

Сейчас:
last_commit: str
commit_date: strftime
git_tags: list[str]
commit_error: str

Также в check_bot в словарь апи добавлен url (если webhook mode).

В принципе, если фронт эти поля выдачи ждет строго - их тоже нужно править "как было": git_tags обратно в tag, url убирать из выдачи, commit_error тоже убирать

2023-09-08 18:23 UTC, NiKuma0 approved these changes

2023-09-08 18:23 UTC, merged