updated docs for tasks and categories
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #183
Opened 2023-08-25 12:33 UTC by Kaydalova

2023-08-25 12:47 UTC, NiKuma0 requested changes

2023-08-25 12:47 UTC, NiKuma0 commented on src/api/schemas.py
> +    id: NonNegativeInt = Field(..., description=TASK_ID_DESCRIPTION)
Гораздо проще будет читаться если не использовать константы: 
```suggestion
    id: NonNegativeInt = Field(..., description="Уникальный идентификатор задачи")
```

2023-08-25 12:47 UTC, NiKuma0 commented on src/api/constants.py
> +В запросе передается полный список актуального контента (категорий, задач), \
В питоне подобный синтаксис считается устаревшем (когда используешь `\` для переноса строки). Вместо этого рекомендуется использовать скобки:

```python
SOME_TEXT = (
    "Some line \n"
    "Some line, "
     "but look like multi line"
)

2023-08-25 13:30 UTC, Kaydalova commented on src/api/schemas.py
> +    id: NonNegativeInt = Field(..., description=TASK_ID_DESCRIPTION)
Все константы из дескрипшена убрать?

2023-08-26 11:25 UTC, NiKuma0 requested changes

2023-08-26 11:25 UTC, NiKuma0 commented on src/application.py
Оставь этот файл как в develop.

2023-08-28 13:59 UTC, NiKuma0 commented
![image](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/78080842/13e1f2f3-0043-4e96-9f29-1c4d70a74f0b)
Честно говоря выглядит не очень. Можно несколько тегов сделать? Чтобы `POST /api/categories` был с тегом `Content` и `Categories`. Текст хотелось бы видеть под тегом, а не рядом. Как тут "Получает список всех категорий":  
![image](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/78080842/152e6fd4-10a7-4e89-b858-48b15220a33b)

2023-08-28 14:00 UTC, NiKuma0 commented on src/api/schemas.py
> +        description=("Принадлежность к родительской категории." "Если null, то это родительская категория."),
```suggestion
        description=("Принадлежность к родительской категории. Если null, то это родительская категория."),
```

2023-09-08 18:25 UTC, NiKuma0 approved these changes
Отлично! Нужно только конфликт поправить.

2023-09-24 10:48 UTC, closed without merging