Создание CI/CD
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #19
Opened 2023-04-18 17:53 UTC by albaranovsky

Задача: https://www.notion.so/CI-CD-dc6028b6e6d746e8a7b81071d02c1e3b?pvs=4

2023-04-19 07:30 UTC, NiKuma0 reviewed
Скоро появится сервер, с ним потестируем

2023-04-19 07:30 UTC, NiKuma0 commented on .github/workflows/deploy_stage.yaml
> +    branches:
Я просил делать деплой для каждой ветке с прификсом `feature/`, `fix/` и `refactoring/`. Можешь взять [код от сюда](https://github.com/Studio-Yandex-Practicum/mspp/blob/develop/.github/workflows/stage_deploy.yaml#L7)

2023-04-19 07:30 UTC, NiKuma0 commented on .github/workflows/deploy_stage.yaml
> +            echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env
Воспользуйся multi-line:
```bash
cat > .env <<- EOM
<some_fields>
EOM
```

2023-04-21 09:49 UTC, NiKuma0 commented on .github/workflows/deploy_stage.yaml
> +  #    branches:
И как мы теперь это затестим? Пусть запускается, лишним не будет

2023-04-21 12:44 UTC, albaranovsky commented on .github/workflows/deploy_stage.yaml
> +  #    branches:
Возможно, пока лучше вручную? Сейчас активна обработка workflow_dispatch (стр. 16), согласно [доке ](https://docs.github.com/ru/actions/managing-workflow-runs/manually-running-a-workflow) вроде то, что нужно.

2023-04-22 10:17 UTC, NiKuma0 requested changes

2023-04-22 10:17 UTC, NiKuma0 commented on .github/workflows/deploy_stage.yaml
> +  #    branches:
@albaranovsky У нас деплой идет на тестовый стенд, он может принимать любую ветку. Ни к чему такая осторожность, уж лучше отлавливать ошибки с деплоем сразу, чем сначала вручную запускать деплой, ждать, ловить ошибку, исправлять и снова вручную запускать.  В ручную будем перебираться на работающую ветку.

2023-04-28 15:20 UTC, NiKuma0 approved these changes

2023-04-28 15:29 UTC, merged