feat(bot, bot-services, repository, models) added unsubscribe reason
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #193
Opened 2023-09-09 12:17 UTC by Sovraska

Реализовано: 
- сервис `UnsubscribeReasonService`
- репозиторий  `UnsubscribeReasonRepository` который просто наследуется от абстрактного 
- модель `UnsubscribeReason` и связана с юзером

2023-09-10 09:46 UTC, NiKuma0 requested changes

2023-09-10 09:46 UTC, NiKuma0 commented on src/bot/services/unsubscribe_reason.py
> +        self._sessionmaker = contextlib.asynccontextmanager(sessionmaker)
Сервис не должен зависеть от сессию, только от репозиториев. Посмотри как сделано в `src/api/services/`

2023-09-10 09:46 UTC, NiKuma0 commented on src/bot/services/unsubscribe_reason.py
> +            reason_repository = UnsubscribeReasonRepository(session)
Так делать не нужно) Посмотри как сделано в сервисах api

2023-09-10 09:46 UTC, NiKuma0 commented on src/core/db/migrations/versions/2023-09-09_14.47.01_add_unsubscribe_reason.py
> +"""add_unsubscribe_reason
Хорошо что сделал миграции, многие забывают)

2023-09-10 09:46 UTC, NiKuma0 commented on src/bot/services/unsubscribe_reason.py
> +            return await reason_repository.create(UnsubscribeReason(user=user.id, unsubscribe_reason=reason))
А если она уже существует?

2023-09-10 14:02 UTC, Sovraska commented on src/bot/handlers/menu.py
> +    unsubscribe_reason_service = UnsubscribeReasonService()
Я не могу Импортировать контейнер в menu 
получается circular import
 так как у нас в контейнере есть обьект этого же бота

2023-09-10 14:10 UTC, Sovraska commented on src/bot/handlers/menu.py
> +    unsubscribe_reason_service = UnsubscribeReasonService()
![image](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/92330086/920118c4-d775-4ce2-9091-b3ea41b2af5f)

2023-09-10 14:10 UTC, Sovraska commented on src/bot/handlers/menu.py
> +    unsubscribe_reason_service = UnsubscribeReasonService()
![image](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/92330086/de395510-096e-49db-a682-0aba9ab31db8)

2023-09-10 15:57 UTC, NiKuma0 commented on src/bot/handlers/menu.py
> +    unsubscribe_reason_service = UnsubscribeReasonService()
@Sovraska Скинь ошибку подробнее. /logs

2023-09-11 11:51 UTC, NiKuma0 reviewed
Пару претензий по code style

2023-09-16 09:27 UTC, NiKuma0 requested changes
Не нужно все свои локальные изменения тащить в основной репо.

2023-09-16 09:27 UTC, NiKuma0 commented on README.md
> +1. Создайте и заполните файл .env как в [инструкции](.env).
Все еще изменено. Не нужно тащить эти изменения в наш репо.

2023-09-16 09:27 UTC, NiKuma0 commented on pyproject.toml
> -gitpython = "^3.1.32"
Зачем удалил зависимость?

2023-09-19 08:37 UTC, NiKuma0 requested changes

2023-09-19 08:37 UTC, NiKuma0 commented on src/core/db/models.py
> +    user: Mapped[int] = mapped_column(Integer(), ForeignKey("users.id"))
Это не похоже что будет работать, расскажи как тестировал. Тут должно быть как минимум две колонки - `user_id` и `user`, посмотри как в других частях сделано. [Вот пример из доки](https://docs.sqlalchemy.org/en/20/orm/basic_relationships.html#many-to-one).

2023-09-19 08:56 UTC, Sovraska commented on src/core/db/models.py
> +    user: Mapped[int] = mapped_column(Integer(), ForeignKey("users.id"))
![image](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/92330086/42970607-e95a-467a-ae81-4bf2c28e5bcc)
 Вот таким образом отлично работает

2023-09-19 09:00 UTC, Sovraska commented on src/core/db/models.py
> +    user: Mapped[int] = mapped_column(Integer(), ForeignKey("users.id"))
вот пример из доки 

![image](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/92330086/1c19edb6-9347-4fc2-b026-d741f94a761b)


а вот как реализовано у меня 

![image](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/92330086/5cd68720-8468-4068-9b95-beef6dd77063)


![image](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/92330086/00cc777f-5b12-4111-8334-15203cbaf1f4)

это поле один к  одному а потому нет разницы с какой стороны присоеденяется 
потому я решил не создовать доп поле у юзера 

![image](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/92330086/edf93c2c-f426-4ce8-abaa-79ae8a4b608c)

2023-09-19 14:38 UTC, NiKuma0 commented on src/core/db/models.py
> +    user: Mapped[int] = mapped_column(Integer(), ForeignKey("users.id"))
@Sovraska Хорошо, это работает) Только тут нет нормальных тайпингов... Вот пример из доки One To One: 
```python
class Parent(Base):
    __tablename__ = "parent_table"

    id: Mapped[int] = mapped_column(primary_key=True)
    child: Mapped["Child"] = relationship(back_populates="parent")


class Child(Base):
    __tablename__ = "child_table"

    id: Mapped[int] = mapped_column(primary_key=True)
    parent_id: Mapped[int] = mapped_column(ForeignKey("parent_table.id"))

    parent: Mapped["Parent"] = relationship(back_populates="child")   # Вот этого поля у тебя не достаёт.
```

P.S. Используй коде-блоки, а не скрины.

2023-09-19 15:25 UTC, Sovraska commented on src/core/db/models.py
> +    user: Mapped[int] = mapped_column(Integer(), ForeignKey("users.id"))
ага понял сейчас допилю

2023-09-20 04:10 UTC, Sovraska commented on src/core/db/models.py
> +    user: Mapped[int] = mapped_column(Integer(), ForeignKey("users.id"))
@NiKuma0  Готово

2023-09-21 14:58 UTC, NiKuma0 approved these changes

2023-09-21 14:58 UTC, merged