Add /group endpoint and classes Messages in schemas
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #195
Opened 2023-09-10 16:55 UTC by PavelPrist

2023-09-11 12:47 UTC, NiKuma0 requested changes

2023-09-11 12:47 UTC, NiKuma0 commented on README.md
> +1. Создайте и заполните файл .env как в [инструкции](.env).
Оставь файл как был. Зачем эти изменения?

2023-09-11 12:47 UTC, NiKuma0 commented on src/api/endpoints/notification.py
> +    TelegramNotificationUsersRequest
```suggestion
    TelegramNotificationUsersRequest,
```

2023-09-11 12:47 UTC, NiKuma0 commented on src/api/endpoints/notification.py
> +    "/group", description="Send messages to group"
Функция выше "перекрывает" эту вьюху. Запрос на `/group` подходит под паттерн выше - `/{telegram_Id}`. Поставь свою вьюху выше `send_user_message` и будет работать.

2023-09-11 12:47 UTC, NiKuma0 commented on src/api/schemas.py
> +from typing import Dict, List, Optional
В python 3.11 можно отказаться от всех этих импортах, используй встроенные конструкции:
Вместо `List` - `list`
Вместо `Dict` - `dict`
Вместо `Optional[...]` - `... | None`

Если есть время, отрефачь весь файл, пожалуйста)

2023-09-11 12:47 UTC, NiKuma0 commented on src/api/schemas.py
> +    field_validator, root_validator, conlist)
У нас такой коде стайл: 
```suggestion
from pydantic import (
    BaseModel,
    Extra,
    Field,
    NonNegativeInt,
    StrictStr,
    field_validator,
    root_validator,
    conlist,
)
```

2023-09-11 12:47 UTC, NiKuma0 commented on src/api/schemas.py
> +                "Категория не может быть дочерней для самой себя.")
```suggestion
            raise ValueError(
                "Категория не может быть дочерней для самой себя."
            )
```

2023-09-11 12:47 UTC, NiKuma0 commented on src/api/schemas.py
> +                'Для передачи строки с числами в поле specializations используйте формат: "1, 2, 3" ')
Почему тут поправил и выше тоже? Прошлые строки ни как не противоречили нашему code-style, а теперь есть немного)  
```suggestion
            raise ValueError(
                'Для передачи строки с числами в поле specializations используйте формат: "1, 2, 3"'
            )
```

2023-09-11 13:18 UTC, PavelPrist commented on README.md
> +1. Создайте и заполните файл .env как в [инструкции](.env).
это очень странно. я ничего не менял в нем.  даже истории нет, что я что-то в нем менял. переписал эту строчку Создайте и заполните файл .env как в [инструкции](.env.example).

2023-09-11 13:20 UTC, PavelPrist commented on src/api/endpoints/notification.py
> +    "/group", description="Send messages to group"
спасибо большое! всю голову сломал, откуда он хочет telegram_Id

2023-09-11 13:30 UTC, PavelPrist commented on src/api/schemas.py
> +from typing import Dict, List, Optional
done

2023-09-11 13:31 UTC, PavelPrist commented on src/api/schemas.py
> +    field_validator, root_validator, conlist)
не заметил этого стиля)) 
сделаю

2023-09-11 14:03 UTC, PavelPrist commented on src/api/schemas.py
> +                'Для передачи строки с числами в поле specializations используйте формат: "1, 2, 3" ')
да не правил я... не пойму ничего.

2023-09-12 12:29 UTC, NiKuma0 requested changes

2023-09-12 12:29 UTC, NiKuma0 commented on .env.example
У тебя тут файл `.env.example` удалён. У себя локально можешь так и оставить, но такие изменения в репозиторий не тащи.

2023-09-12 12:29 UTC, NiKuma0 commented on README.md
> +3. Переименовать [`.env.example`](.env) в `.env` и задать переменные окружения.
Не нужно менять этот файл.

2023-09-12 12:29 UTC, NiKuma0 commented on src/api/constants.py
> +UNSUCCESSFUL_COUNT = 0
Кажется эти константы не где не используются.

2023-09-12 12:29 UTC, NiKuma0 commented on src/api/endpoints/notification.py
> +import logging
Мы используем `structlog` для логирования.

2023-09-12 12:29 UTC, NiKuma0 commented on src/api/endpoints/notification.py
> +    UNSUCCESSFUL_COUNT = 0
В python капсом записываются константы, а это просто переменные, они объявляются каждый вызов функции.

2023-09-12 12:29 UTC, NiKuma0 commented on src/api/endpoints/notification.py
> +    UNSUCCESSFUL_COUNT = 0
Лучше будет success rate а не count.

2023-09-12 12:29 UTC, NiKuma0 commented on src/api/endpoints/notification.py
> +    result = (f'Successful sending - {SUCCESSFUL_COUNT}, '
Используй модели pydantic.

2023-09-12 12:30 UTC, NiKuma0 commented
Поправь конфликт

2023-09-12 12:38 UTC, PavelPrist commented on .env.example
ох. я его переименовал. и забыл. извиняюсь.

2023-09-12 12:46 UTC, PavelPrist commented on src/api/constants.py
> +UNSUCCESSFUL_COUNT = 0
вопрос в том, что я их пытаюсь использовать, но почему-то не получается. Можешь помочь понять, почему я не могу их импортировать? Точнее я импортирую, но в функции константы не видят их.

2023-09-12 12:49 UTC, PavelPrist commented on src/api/endpoints/notification.py
> +import logging
убрал.

2023-09-12 12:53 UTC, PavelPrist commented on src/api/endpoints/notification.py
> +    result = (f'Successful sending - {SUCCESSFUL_COUNT}, '
не понимаю, комментария. Что он означает в данном случае, можно поподробнее?

2023-09-15 06:46 UTC, NiKuma0 commented on README.md
> +3. Переименовать [`.env.example`](.env) в `.env` и задать переменные окружения.
Не один, кста) Уже создал задачу по этому поводу.

2023-09-16 09:58 UTC, NiKuma0 requested changes
Поправь конфликт.

2023-09-19 08:31 UTC, NiKuma0 approved these changes

2023-09-19 08:32 UTC, merged