added checked category icon if subcategory checked
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #199
Opened 2023-09-12 16:18 UTC by beskrovniibv

2023-09-13 04:52 UTC, ArtemBalandin81 commented
Пока разбираюсь и вспоминаю бота)
Нашел небольшой баг (не слишком критично, но все же)
когда первый раз вызываешь /menu - изменить компетенции - не показываются выбранные.
Если потом выберешь любую и вернешься в меню, отображение уже происходит
![Компетенции](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/105808126/efc39d67-f1c1-42fc-a069-32091014ec68)

2023-09-13 17:33 UTC, beskrovniibv commented
> Пока разбираюсь и вспоминаю бота) Нашел небольшой баг (не слишком критично, но все же) когда первый раз вызываешь /menu - изменить компетенции - не показываются выбранные. Если потом выберешь любую и вернешься в меню, отображение уже происходит ![Компетенции](https://user-images.githubusercontent.com/105808126/267539022-efc39d67-f1c1-42fc-a069-32091014ec68.jpg)

Привет, я про это подумал. И даже сделал, в коде видно ))
Не знаю, почему у тебя не работает.
Сейчас у себя (пере-)проверю.

2023-09-13 17:40 UTC, beskrovniibv commented
Я, конечно, молодец. Сделал только половину.

2023-09-13 18:15 UTC, beskrovniibv commented
Перезалил с исправлениями.

2023-09-15 14:07 UTC, NiKuma0 requested changes

2023-09-15 14:08 UTC, NiKuma0 commented
Поправь конфликт.

2023-09-21 10:52 UTC, beskrovniibv commented
Готово!

2023-09-22 11:43 UTC, NiKuma0 approved these changes
В целом все отлично, можно мержить. Если будет время и желание, поправь замечание по коде стайлу.

2023-09-22 11:43 UTC, NiKuma0 commented on src/core/db/repository/category.py
> +        subq = (
Лучше его назвать как-то понятнее, например `parent_and_children_count_subquery`.

2023-09-22 11:43 UTC, NiKuma0 commented on src/core/db/repository/category.py
> +            .where(Category.parent_id != None)  # noqa
Тут можно воспользоваться [функциями sqlalchemy](https://docs.sqlalchemy.org/en/20/core/sqlelement.html#column-element-foundational-constructors) чтобы не пришлось прописывать `# noqa`:
```suggestion
            .where(Category.is_archived == false())
            .where(Category.parent_id != null())
```

2023-09-23 08:52 UTC, beskrovniibv commented
> В целом все отлично, можно мержить. Если будет время и желание, поправь замечание по коде стайлу. 

Сделаю.

2023-09-23 17:15 UTC, beskrovniibv commented on src/bot/handlers/categories.py
> +    user_service = user_service
Справедливо.

2023-09-23 17:15 UTC, beskrovniibv commented on src/bot/services/user.py
> +        repository = self._user_repository
Справедливо.

2023-09-23 17:18 UTC, beskrovniibv commented on src/core/db/repository/category.py
> +        subq = (
Принято!

2023-09-23 17:22 UTC, beskrovniibv commented on src/core/db/repository/category.py
> +            .where(Category.parent_id != None)  # noqa
Отлично! Спасибо.

2023-09-23 17:25 UTC, beskrovniibv commented
Отработал замечания из ревью.

2023-09-24 10:44 UTC, merged