Readme refactor
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #204
Opened 2023-09-15 09:49 UTC by PavelPrist

2023-09-16 09:55 UTC, NiKuma0 requested changes

2023-09-16 09:55 UTC, NiKuma0 commented on README.md
>        <a href="#для-разработки">Для разработки</a>
Тут не все ссылки рабочие, т.к. некоторые блоки ты удалил.

2023-09-16 09:55 UTC, NiKuma0 commented on README.md
> +        <li><a href="#Установка и настройка приложения">Установка приложения</a></li>
```suggestion
        <li><a href="#установка-и-настройка-приложения">Установка приложения</a></li>
```

2023-09-16 09:55 UTC, NiKuma0 commented on README.md
> +1. Создайте и заполните файл .env как в полном примере [переменных окружения](env.example).
По идее полный пример должен быть как дополнение, если сразу его выдать новичку (этот блок у нас не для разработчиков), то он испугается от кол-во переменных)  Давай тут предложим заполнить только необходимые переменные, а ниже дадим ссылку на полный пример.


```suggestion
1. Создайте и заполните файл `.env`:

    ```
    BOT_TOKEN=<your_token_from_botfather>
    ```

    > **Note** 
    > [Полный пример переменных окружения](env.example).
```

И добавь, также, ссылку на инструкцию по получению токена бота.

2023-09-16 09:55 UTC, NiKuma0 commented on README.md
> +4. Создать .env и скопировать [`env.example`](env.example) в `.env` и задать переменные окружения.
Тут сделай также как я описал выше. Только переменных окружения должно быть чуть больше - нужно указать переменные БД postgres-а

2023-09-16 09:55 UTC, NiKuma0 commented on README.md
> +    USE_NGROK=True
Если используешь эту переменную, туннель запускать не нужно (пункт 2). Эта инструкция все еще актуально, ей может пользоваться наш фронт, но для разработки будет удобнее просто поставить эту переменную.

2023-09-16 09:55 UTC, NiKuma0 commented on README.md
> -### Переменные окружения (.env)
Этот блок можно оставить, можно просто здесь указать ссылку на файл.

2023-09-16 09:55 UTC, NiKuma0 commented on src/api/endpoints/notification.py
Кажется эти изменения не должны быть тут... Этот ПР на изменения README, а тут какой-то код меняется. Убери это.

2023-09-18 11:02 UTC, PavelPrist commented on README.md
> -### Переменные окружения (.env)
> Этот блок можно оставить, можно просто здесь указать ссылку на файл.

посмотри, пожалуйста, вроде как получается в новой редакции это уже лишнее .

2023-09-18 11:19 UTC, PavelPrist commented
Чтобы убрать путаницу с кодом лишним, я предлагаю эту ветку просто закрыть.  И я создал новую на ПР где только readme изменяется.

2023-09-18 11:20 UTC, PavelPrist commented
Чтобы убрать путаницу с кодом лишним, я предлагаю эту ветку просто закрыть.  И я создал новую на ПР где только readme изменяется.

2023-09-19 08:38 UTC, closed without merging