Feature/add admin login
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #210
Opened 2023-09-17 15:31 UTC by akiqq

2023-09-18 11:19 UTC, NiKuma0 reviewed
Этот эндпоинт нужен для админки (фронта), поэтом чтобы его затестить, нужно создать админа и попробовать залогинется `<your_host>/admin/`. Наверное будет проще это сделать на сервере, чтобы локально не мучится с фронтом (https://procharity.duckdns.org/admin/). Потом кинь результаты тестов.

2023-09-18 11:19 UTC, NiKuma0 commented on src/api/endpoints/admin_login.py
> +    if user is not None:
Уменьши вложенность:
```suggestion
    if user is None:
        return HTTPStatus.BAD_REQUEST("Неверный почтовый адрес или пароль.")
```

2023-09-18 11:19 UTC, NiKuma0 commented on src/api/endpoints/admin_login.py
> +refresh_security = JwtRefreshBearer(secret_key="secret_key", auto_error=True)
Это зависимости, зависимостями управляем через DI. Добавь их в контейнер - `depends.py`

2023-09-18 11:19 UTC, NiKuma0 commented on src/api/endpoints/admin_login.py
> +from fastapi_jwt import JwtAccessBearerCookie, JwtRefreshBearer
Не вижу новую библиотеку в `pyproject.toml` и `poetry.lock`

2023-09-22 11:56 UTC, NiKuma0 requested changes
Сервер упал с ошибкой
```
procharity_bot_backend  |   File "/app/src/depends.py", line 5, in <module>
procharity_bot_backend  |     from fastapi_jwt import JwtAccessBearerCookie, JwtRefreshBearer
procharity_bot_backend  | ModuleNotFoundError: No module named 'fastapi_jwt'
```
Обнови requerements.txt 
```shell
poetry export -f requirements.txt --output requirements.txt --without-hashes

2023-09-22 11:56 UTC, NiKuma0 commented on src/api/endpoints/admin_login.py
> +    if user is not None:
Так и не уменьшил

2023-09-23 10:02 UTC, NiKuma0 requested changes

2023-09-23 10:02 UTC, NiKuma0 commented on src/api/router.py
> +api_router.include_router(admin_user_router, prefix="/admin", tags=["AdminUser"])
Я не просто так упомянул старый проект - все эндпоинты и схемы должны быть такими-же как в прошлой версии. Сейчас фронт не работает, он обращается по адресу `/api/v1/auth/login/` и получает 404. Посмотри как выглядит структура API в старом проекте.

2023-09-23 13:20 UTC, akiqq commented
Поменял ендпоинт, все равно ловлю 404.


![image](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/111808447/9d223f3c-89a1-4eca-9f2b-b84c60338761)

![image](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/111808447/1a39affa-d625-4658-b54f-b5f7eb27a6cf)

2023-09-23 13:54 UTC, NiKuma0 requested changes

2023-09-23 13:54 UTC, NiKuma0 commented on src/api/router.py
> +api_router.include_router(admin_user_router, prefix="/v1/auth", tags=["AdminUser"])
Тут не нужен этот `v1` 
```suggestion
api_router.include_router(admin_user_router, prefix="/auth", tags=["AdminUser"])
```

2023-09-23 14:02 UTC, akiqq commented
Все работает! Спасибо за помощь!
![image](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/111808447/00f97343-2663-4ab1-8171-c00606636443)

2023-09-24 10:36 UTC, NiKuma0 approved these changes

2023-09-24 10:37 UTC, merged