Fix/webhook launch
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #213
Opened 2023-09-19 09:39 UTC by jullitka

В файле main.py некорректный доступ к настройкам через контейнер.
Так не работает:
    container.settings.provided.USE_NGROK 
    container.settings.provided.BOT_WEBHOOK_MODE
    container.settings.provided.telegram_webhook_url
    container.settings.provided.SECRET_KEY
Соответственно вебхук не включается
А вот  так работает: 
    container.settings().USE_NGROK 
    container.settings().BOT_WEBHOOK_MODE
    container.settings().telegram_webhook_url
    container.settings().SECRET_KEY
После замены бот стал запускаться в режиме webhook.

2023-09-19 13:15 UTC, NiKuma0 reviewed
Отлично!

2023-09-19 13:15 UTC, NiKuma0 commented on src/settings.py
> +    BOT_WEBHOOK_MODE: bool = True
Тут также. Локально лучше меняй .env файл, а не сеттинги.

2023-09-21 14:20 UTC, NiKuma0 requested changes

2023-09-21 14:20 UTC, NiKuma0 commented on poetry.lock
Этот файл тоже оставь как он был.

2023-09-22 05:45 UTC, jullitka commented on poetry.lock
вернула

2023-09-22 11:57 UTC, NiKuma0 approved these changes

2023-09-22 11:57 UTC, merged