add an account link button
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #227
Opened 2023-10-01 07:12 UTC by jullitka

Добавила кнопку, которая ссылается на сайт (по аналогии со старым ботом). НО! В ссылке фигурирует external_id, которого может не быть у конкретного пользователя в БД. Соответственно, в этом случае ничего не работает. Пока сделала для пользователе без external_id ссылку на страницу авторизации. Проверив работу в старом боте я просто попала на страницу сайта со словами "Пользователь с id None не найден". 
Соответственно в процессе возникли вопросы:
- Что является связью аккаунта с ботом? Заполнение поля external_id или нет?
- Куда должны попадать пользователи, у которых нет external_id?

2023-10-03 09:46 UTC, NiKuma0 reviewed
Есть только пара замечаний, но в остальном все просто отлично)

2023-10-03 09:46 UTC, NiKuma0 commented on src/bot/constants/urls.py
> +PROCHARITY_URL_USER = "https://procharity.ru/auth/bot_procharity.php?user_id={external_id}&telegram_id={telegram_id}"
Лучше это убрать в сеттинги - у нас может быть несколько адресов сайта procharity - тестовый и прод.

2023-10-03 09:46 UTC, NiKuma0 commented on src/bot/handlers/registration.py
> +    keyboard = await get_start_keyboard(callback_data_on_start=callback_data_on_start, url_for_connection=url_connect)
Наверное стоит убрать формирование ссылки в отдельную функцию.

2023-10-03 17:21 UTC, NiKuma0 requested changes

2023-10-03 17:21 UTC, NiKuma0 commented on src/bot/utils.py
> +    else:
Можно без `else`

2023-10-03 17:21 UTC, NiKuma0 commented on src/bot/utils.py
> +from src.settings import settings
Так сетинги получать не надо, это устаревшей метод, используй DI

2023-10-04 07:56 UTC, jullitka commented on src/bot/handlers/registration.py
> +        url_connect = get_connection_url(update.effective_user.id)
Не очень поняла: это замечание или нет?) Нужно чтобы функция вызывалась здесь один раз? После блока if/else? Или нет? Если да, то тогда получается что обязательно нужно использовать external_id и если брать external_id = ext_user.id, то во втором случае, когда extr_user -  None будет ошибка.  Я пока не вижу другого варианта в таком случае, кроме как явно указать после if: external_id = ext_user.id, а после else: external_id = None дополнительно к уже имеющемуся коду. И тогда уже использовать после if/else один раз get_connection_url(update.effective_user.id, **external_id**). Но будет ли это лучше?

2023-10-04 14:34 UTC, merged