Feature/kick monkey patching
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #234
Opened 2023-10-11 11:06 UTC by KVGribko

[#229](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/issues/229)
- `init_app` - Переименована в `init_fastapi`
-  `init_fastapi` - перенесена из `src/api/__init__,py` в `src/api/main.py`
-  `init_bot` - перенесена из `src/bot/__init__,py` в `src/bot/main.py`
- Инициализация приложения `FastAPI` и `Bot` теперь производится на уровне `Container`
- Инжектирование зависимостей в `on_startup`

2023-10-11 18:09 UTC, NiKuma0 requested changes

2023-10-11 18:09 UTC, NiKuma0 commented on src/api/main.py
> +from src.settings import settings
Так не нужно использовать `settings` - эта плохая практика. Перемести ее в аргументы функции `init_fastapi`, чтобы было: 
```python
def init_fastapi(fast_api: FastAPI, settings: Settings) -> FastAPI: ...

2023-10-11 18:09 UTC, NiKuma0 commented on src/main.py
> +async def startup(
Тут забыл декоратор `@inject`. Желательно перемесить регистрацию `startapp` и `shutdown` в `init_fastapi`.

2023-10-12 08:26 UTC, KVGribko commented on src/api/main.py
> +from src.settings import settings
Такая реализация была изначально, я тут ничего не менял.
Испарвил.

2023-10-12 11:49 UTC, KVGribko commented on src/main.py
> +async def startup(
Перенес регистрацию `startapp` и `shutdown` в `init_fastapi`

Еще вчера, когда все было в `main()`, столкнулся с такой проблемой, что, если объявлять  функцию, внутри области видимости другой функции то зависимости не работают. 
```python
def set_events(
):
    @fastapi_app.on_event("startup")
    @inject
    async def on_startup(settings: Settings = Provide[Container.settings]):
        if settings.USE_NGROK is True:
            set_ngrok()
       ....
```
Происходит ошибка `AttributeError: 'AttributeError: 'Provide' object has no attribute 'USE_NGROK'` так как, внутри функции `on_startup` , переменная  `settings` имеет класс `<class 'dependency_injector.wiring.Provide'>`, а не `<class 'src.settings.Settings'>`. Не нашел решение что с этим делать, поэтому создал отдельную функцию `startup`  которую затем вызывал из `async def on_startup()`. 

В реализации которую сейчас отправил, вынес реализации методов `startapp` и `shutdown` в отдельный файл `src/api/events.py`, чтобы избежать циклических зависимостей.

2023-10-14 14:25 UTC, NiKuma0 approved these changes

2023-10-14 17:43 UTC, ArtemBalandin81 commented on src/api/main.py
> +    set_events(fastapi_app, run_bot)
И я не видел, но решил что потайной смысл в этом должен быть)

2023-10-14 18:07 UTC, merged