Replaced logging
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #248
Opened 2023-10-20 16:47 UTC by Alexandra2706

- [Заменить logging на structlog везде, где пишутся логи#238](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/issues/238)

2023-10-20 17:37 UTC, ArtemBalandin81 requested changes

2023-10-20 17:37 UTC, ArtemBalandin81 commented on src/bot/bot.py
> +    log.info(result)
Интересно, почему в аналогичной корутине src/api/auth/token.py используется await log.ainfo?
Есть ли связь в его использовании: обычная функция, или асинхронная?

src/api/endpoints/notification.py - тоже обычный (правильно ли?)
src/bot/handlers/menu.py - асинхронная

А в следующих модулях вообще декоратор. А мы не можем вообще его везде использовать?
(на подумать)
используется @logger_decor:

src/api/endpoints/health_check.py
src/bot/handlers/categories.py
src/bot/handlers/feedback_form.py
src/bot/handlers/menu.py
src/bot/handlers/registration.py
src/bot/handlers/tasks.py

2023-10-20 17:37 UTC, ArtemBalandin81 commented on src/core/services/notification.py
> +logger = structlog.get_logger(module=__name__)
может быть его везде называть одинаково - log?

2023-10-21 16:10 UTC, Alexandra2706 commented on src/bot/bot.py
> +    log.info(result)
@logger_decor логирует имя функции и ее аргументы в момент вызова, часто требуется логировать что-то в середине функции. Также часто требуется использовать уровень логирования отличный от инфо.

2023-10-22 05:45 UTC, ArtemBalandin81 approved these changes

2023-10-22 15:49 UTC, merged