Update base.py
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #249
Opened 2023-10-21 17:29 UTC by mekhaneg

changing already_have from ContentRepository type to List[int] by adding mrthod .all()

2023-10-22 06:24 UTC, ArtemBalandin81 requested changes

2023-10-22 06:24 UTC, ArtemBalandin81 commented on src/api/services/base.py
> +            already_have = (await self._repository.get_by_ids(ids)).all()
Если проблема только в этом, то мне кажется, мы так не делаем
Лучше в репозитории поправить, используя _session.execute по типу
    async def get_all(self) -> list[DatabaseModel]:
        """Возвращает все объекты модели из базы данных."""
        objects = await self._session.execute(select(self._model))
        return objects.scalars().all()

2023-10-22 13:44 UTC, ArtemBalandin81 requested changes
Залил для теста на сервер.
В /api/v1/categories/ добавил новую категорию:
[
  {
    "id": 71,
    "name": "Category Name",
    "parent_id": 1
  }
]
+ все добавилось
+ далее попытался ее изменить на:
"Category Name2"
+ все изменилось.
АПИ работает, ошибок нет

Запустил бота и запросил изменить компетенции - стало показывать только ту, что я сейчас добавил 71. Какой-то баг.
Нужно разобраться почему так (может быть 71 нельзя добавлять, т.к. там до нее есть уже новичок, опытный, профессионал). Но все равно стоит разобраться почему так

2023-10-22 16:03 UTC, NiKuma0 commented
> Запустил бота и запросил изменить компетенции - стало показывать только ту, что я сейчас добавил 71. Какой-то баг.

@ArtemBalandin81 Это не баг, а фича) Мы получаем все данные одним запросом. Если в нашей БД нет категорий/задач мы их архивируем - не показываем пользователю.

2023-10-22 16:04 UTC, NiKuma0 approved these changes

2023-10-22 16:05 UTC, NiKuma0 approved these changes

2023-10-22 16:05 UTC, NiKuma0 commented on src/api/services/base.py
> +            already_have = (await self._repository.get_by_ids(ids)).all()
Это нужно на уровне репозитория. Создай отдельный ПР, этот смержу.

2023-10-22 16:05 UTC, merged

2023-10-22 16:19 UTC, ArtemBalandin81 commented
> > Запустил бота и запросил изменить компетенции - стало показывать только ту, что я сейчас добавил 71. Какой-то баг.
> 
> @ArtemBalandin81 Это не баг, а фича) Мы получаем все данные одним запросом. Если в запросе нет категорий/задач мы их архивируем - не показываем пользователю.

Блин, сколько раз уже наступал на эти грабли))) Я добавил одну категорию, остальные стали автоматом архивными, потому и не отображаются. А клиент-то знает, что нужно все разом отправлять. Бага нет

2023-10-23 17:45 UTC, beskrovniibv commented on src/api/services/base.py
> +            already_have = (await self._repository.get_by_ids(ids)).all()
> Это нужно на уровне репозитория. Создай отдельный ПР, этот смержу.

Сделал Draft.