Fixes for CI/CD
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #26
Opened 2023-04-28 17:19 UTC by albaranovsky

2023-04-29 09:52 UTC, NiKuma0 requested changes
Убери `types: [closed]`, хочу запускать наш деплой сразу на всех ветках. К, тому же, нужно как то это потестить.

2023-04-29 10:44 UTC, NiKuma0 requested changes

2023-04-29 10:44 UTC, NiKuma0 commented on .github/workflows/deploy_stage.yaml
>        - 'feature/**'
Вот почему у нас ничего не работает, должно быть так: 
```yaml
on:
  push:
    branches:
      - develop
      - 'feature/**'
      - 'fix/**'
      - 'refactoring/**'
  pull_request:
    branches:
      - develop
    types: [closed]
```

2023-04-29 12:26 UTC, NiKuma0 requested changes
Из-за строчки 32 (`if: github.event.pull_request.merged == true`) скипается наш деплой, проверь, может еще есть какие-то правила которые упустил. В общем - жду запуска деплоя.

2023-05-01 11:47 UTC, NiKuma0 commented on .github/workflows/deploy_stage.yaml
> +    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true
Эту конструкцию можно убрать, у нас фильтрация в блоке `on`

2023-05-01 11:47 UTC, NiKuma0 commented on .github/workflows/deploy_stage.yaml
> +    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true
Это можно убрать тоже.

2023-05-01 11:56 UTC, NiKuma0 requested changes

2023-05-01 15:35 UTC, NiKuma0 requested changes
И еще немного. Неверная команда при запуске докера. Сейчас `docker <do something>` должно быть `sudo docker <do something>`, также неврный вызов докер комауза - должно быть `sudo docker compose <do smothing>` вместо `docker-compose <do something>`.

2023-05-01 15:46 UTC, NiKuma0 commented
Теперь ругается что не вводится пароль. [Тут есть решение](https://stackoverflow.com/questions/11955298/use-sudo-with-password-as-parameter)

2023-05-03 16:42 UTC, NiKuma0 requested changes

2023-05-03 16:42 UTC, NiKuma0 commented on infra/docker-compose.staging.yml
>    postgres:
Добавь healthckeack, [тут есть хороший гайд](https://github.com/peter-evans/docker-compose-healthcheck)

2023-05-03 16:42 UTC, NiKuma0 commented on Dockerfile
> +CMD ["uvicorn", "src:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
`--reload` - Это флаг для разработки. К тому же у нас есть подобная штука в docker-compose

2023-05-04 14:52 UTC, NiKuma0 reviewed
Отлично, бот на сервере! Поправь один моментик..

2023-05-04 14:52 UTC, NiKuma0 commented on requirements.txt
> +python-dotenv==1.0.0 ; python_version >= "3.11" and python_version < "4.0"
Так себе решение. `python-dotenv` - для разработки, для запуска приложения он не нужен. Лучше добавь переменные окружения в `backend` и чтобы сеттинги брались из окружения а не из файла.

2023-05-05 13:18 UTC, NiKuma0 commented on src/settings.py
> -BASE_DIR = Path(__file__).resolve().parent.parent
Это ты зря убрал. Как мне пользоваться ботом локально ?

2023-05-05 15:28 UTC, NiKuma0 commented on src/settings.py
> -BASE_DIR = Path(__file__).resolve().parent.parent
Я тут потестил - pydantic в любом случае пробует сначала взять переменные из окружения, не смотря на то что указан файл...

2023-05-07 16:52 UTC, NiKuma0 commented
Нашел другое решение, вместо `echo { secrtects.SSH_PASSWORD } | sudo -S docker ... `  просто `docker compose ... `. Добавил пользователя dev в группу docker, теперь докер можно запускать без `sudo`.

2023-05-07 19:05 UTC, albaranovsky commented on src/settings.py
> -BASE_DIR = Path(__file__).resolve().parent.parent
Вернул поддержку `.env`. В доке Pydantic заявлено, что переменные окружения всегда будут иметь приоритет над значениями, загружаемыми из файла `.env` .

2023-05-08 11:28 UTC, NiKuma0 approved these changes

2023-05-08 11:29 UTC, merged