Feature/analytics/reasons canceling
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #264
Opened 2023-11-04 16:51 UTC by KVGribko

#259

Переделано поле `reasons_canceling` в ответе на запрос `/api/v1/analytics/ `. Теперь вместо `str`  возвращается `dict[str, int]` в формате `{"причина": количество}` , идентично прежней api.

2023-11-04 19:41 UTC, ArtemBalandin81 requested changes

2023-11-04 19:41 UTC, ArtemBalandin81 commented on src/api/services/analytics.py
> +        return dict(reasons_statistic_from_db)
return dict() смущает. вроде мы так не делаем в проекте
Попробуй использовать TypedDict как у нас в схемах (BotStatus, CommitStatus, HealthCheck)

2023-11-04 20:13 UTC, ArtemBalandin81 commented on src/core/db/repository/unsubscribe_reason.py
> +    async def get_reason_cancelling_statistics(self) -> list[tuple[str, int]]:
а тут нельзя просто -> list[UnsubscribeReason]?

2023-11-04 20:14 UTC, ArtemBalandin81 commented on src/api/schemas.py
>      active_users_statistic: dict[str, str] = {}
дублирую для наглядности:

return dict() смущает. вроде мы так не делаем в проекте
Попробуй использовать TypedDict как у нас в схемах (BotStatus, CommitStatus, HealthCheck)

2023-11-04 20:52 UTC, KVGribko commented on src/core/db/repository/unsubscribe_reason.py
> +    async def get_reason_cancelling_statistics(self) -> list[tuple[str, int]]:
Поля `count` нет в `UnsubscribeReason`

2023-11-04 21:15 UTC, KVGribko commented on src/api/services/analytics.py
> +        return dict(reasons_statistic_from_db)
Насколько я понял, с помощью `TypedDict` можно описать обязательные или опциональные ключи словаря. в текущей реализации ключи должны быть на русском языке и написаны через пробел.

2023-11-05 07:20 UTC, NiKuma0 commented on src/core/db/repository/unsubscribe_reason.py
> +    async def get_reason_cancelling_statistics(self) -> list[tuple[str, int]]:
А почему тогда `tuple`? С ним совсем же неудобно работать. Попробуй использовать `.scalars` вместо `.execute`.

2023-11-05 09:48 UTC, KVGribko commented on src/core/db/repository/unsubscribe_reason.py
> +    async def get_reason_cancelling_statistics(self) -> list[tuple[str, int]]:
`execute` возвращает кортеж с таким  же числом объектов, сколько перечислено в функции `select()`.
Когда мы делаем так:
```python
select(
            UnsubscribeReason.unsubscribe_reason.label("reason"),
            func.count(UnsubscribeReason.unsubscribe_reason).label("count"),
        )
```
то у нас будет по два элемента в каждом кортеже.
`scalars()` же «распаковывает» кортеж и берёт из него только первый элемент. и это больше подходит когда у нас в `select()` один элемент, например, `Model`
```python
select(UnsubscribeReason)
```
можно сделать чтобы он возвращал модель `pydantic`, 
```python
    async def get_reason_cancelling_statistics(self) -> list[ReasonCancelingStatistics]:  # list[tuple[str, int]]:
        query = select(
            UnsubscribeReason.unsubscribe_reason.label("reason"),
            func.count(UnsubscribeReason.unsubscribe_reason).label("count"),
        ).group_by(UnsubscribeReason.unsubscribe_reason)
        reasons = await self._session.execute(query)
        return [ReasonCancelingStatistics(reason=reason, count=count) for reason, count in reasons.all()]
```

но мы не должны на уроне `UnsubscribeReasonRepository` получить сырые данные из бд и привести их уже в удобную для нас форму на уроне `AnalyticsService` ?

2023-11-05 16:37 UTC, ArtemBalandin81 commented on src/core/db/repository/unsubscribe_reason.py
> +    async def get_reason_cancelling_statistics(self) -> list[tuple[str, int]]:
очень развернуто все объяснено, но точно нет путаницы в scalars() и scalar()?
Сам очень долго бился над одной из задач из-за этого....

2023-11-05 16:41 UTC, ArtemBalandin81 commented on src/api/schemas.py
> +    reasons_canceling: dict[str, int] = {}
Попробуй реализовать первый вариант. Идентичность апи нарушать нельзя

2023-11-06 05:22 UTC, NiKuma0 commented on src/api/schemas.py
> +    reasons_canceling: dict[str, int] = {}
Оба варианта так себе... У нас есть четкие причины отписки, их мы вряд ли будем менять, поэтому можно вручную описать примерно такой класс:

```python
class ReasonCancelingStatistics(BaseModel):
    many_notification: int
    no_time: int
    ...
```

Конечно в случае если нужно будет добавить причину отписки придется менять два класса... Оставляю на твое усмотрение, либо оставь как есть, либо добавь предложенную модель. Во втором случае будет более типизированный код, который уменьшает кол-во багов. Первый будет более универсальным. 

Хотя, может, наш фронт исключительно ожидает структуру как сверху, тогда типизация будет лучшем решением.

2023-11-06 05:26 UTC, NiKuma0 requested changes

2023-11-06 05:26 UTC, NiKuma0 commented on src/api/services/analytics.py
> +        return dict(reasons_statistic_from_db)
Вот эту текущую реализацию нужно точно менять. Нам не нужны ключи на русском языке)

2023-11-12 14:50 UTC, ArtemBalandin81 requested changes

2023-11-12 14:50 UTC, ArtemBalandin81 commented on src/api/services/analytics.py
> +    async def get_reason_cancelling_statistics(self) -> ReasonCancelingStatistics:
Решили, что в сервисах не используем схемы пайдентик на случай, если сервисы будем использовать еще где-то. Вот тут [подробнее](https://github.com/orgs/Studio-Yandex-Practicum/projects/5/views/1?sortedBy%5Bdirection%5D=asc&sortedBy%5BcolumnId%5D=48553385&sortedBy%5Bdirection%5D=desc&sortedBy%5BcolumnId%5D=Linked+pull+requests&pane=issue&itemId=35652481)

2023-11-12 16:55 UTC, ArtemBalandin81 requested changes

2023-11-12 16:55 UTC, ArtemBalandin81 commented on src/api/schemas.py
> +class ReasonCancelingStatistics(TypedDict):
Наверное, можно все же обычную пайдентик схему использовать?
Стараемся уйти от тайпдикт

2023-11-12 16:55 UTC, ArtemBalandin81 commented on src/api/services/analytics.py
> +
в сервисах стараемся не использовать пайдентик, чтобы сервисы были универсальными: для бота и апи
Схема пайдентик осталась

2023-11-12 16:55 UTC, ArtemBalandin81 commented on src/api/services/analytics.py
> +        return ReasonCancelingStatistics(dict(reasons_statistic_from_db))
можно же наверное вернуть словарь, а во вьюхе с помощью пайдентик его отображать?

2023-11-12 16:55 UTC, ArtemBalandin81 commented on src/core/db/repository/unsubscribe_reason.py
> +    async def get_reason_cancelling_statistics(self) -> list[tuple[str, int]]:
список кортежей остался, не получилось без него?

2023-11-12 16:55 UTC, ArtemBalandin81 commented on src/core/db/repository/unsubscribe_reason.py
> +        return reasons.fetchall()
а просто .all()?
не проверял, но вроде в проекте нет нигде fetchall()

2023-11-13 17:23 UTC, KVGribko commented on src/core/db/repository/unsubscribe_reason.py
> +    async def get_reason_cancelling_statistics(self) -> list[tuple[str, int]]:
как то уйти от этого не получилось. разве что тут прям преобразовывать данные в другую форму(словарь, модель)

2023-11-18 13:36 UTC, NiKuma0 approved these changes
@KVGribko  Поправь конфликт, и можно мержить) @ArtemBalandin81 также нужен твой апрув.

2023-11-19 06:09 UTC, ArtemBalandin81 approved these changes

2023-11-19 07:09 UTC, merged