Добавил в админку статистику по таскам в эндпоинт /api/analytics/ #265
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #268
Opened 2023-11-07 16:59 UTC by Rederickmind

### Добавил в админку статистику по таскам в эндпоинт /api/analytics/
Поле tasks возвращает словарь следующего вида:
```
"tasks": {
    "last_update": "2023-11-07 00:00:00",
    "active_tasks": 155
  }
```
![Снимок](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/11664980/1c90931b-dfc6-40cd-8ec7-a160dbec7a63)

**Что сделано:**

- Использован метод count_all_active класса AbstractRepository. 
- Добавлен task_repository для analytic_service в depends.py. 
- Добавлен TypedDict ActiveTasks для вывода в схеме ответа аналитики. 
- Определены методы для вывода даты обновления и количества активных задач в services/analytics.py. 
- В endpoints/analytics.py выводится Pydantic схема с количеством активных задач сервиса. 

**Где были произведены изменения:**

- src/api/endpoints/analytics.py
- src/api/schemas.py
- src/api/services/analytics.py
- src/core/db/repository/task.py
- src/depends.py

**Протестировано:**

- Все кнопки бота работают
- Остальные эндпоинты отдают тот же результат что и до изменений
- Число активных задач в /api/analytics/ сходится с числом активных задач в эндпоинте /api/health_check/
- Через эндпоинт Get All Tasks /api/tasks/ получил список всех задач и циклом посчитал количество активных в этом списке, получилось то же самое что в двух эндпоинтах указанных выше

2023-11-08 04:41 UTC, ArtemBalandin81 requested changes
Смотри, в `health_check.py` есть словарь, который отдает все что нам нужно:
```
    async def check_db_connection(self) -> DBStatus:
        try:
            active_tasks = await self._repository.count_active_all()
            get_last_update = await self._repository.get_last_update()
        except SQLAlchemyError as exc:
            db_status: DBStatus = {"status": False, "db_connection_error": f"{exc.__class__.__name__}: {exc}"}
            return db_status
        if get_last_update is None:
            get_last_update = "Unable to get last_update"
        db_status: DBStatus = {
            "status": True,
            "last_update": get_last_update,
            "active_tasks": active_tasks,
        }
        return db_status
```
Мы же можем просто использовать этот сервис, без описания дублирующего?
Добавить схему под этот сервис (как у тебя сделано) и отказаться от дальнейшего дублирования кода?

2023-11-09 16:57 UTC, Rederickmind commented
### Добавил в админку статистику по таскам в эндпоинт /api/analytics/
Поле tasks возвращает словарь следующего вида:
```
tasks": {
    "last_update": "2023-11-09 00:00:00",
    "active_tasks": 149
  }
```
![Снимок2](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/11664980/e0e7650e-e045-41bc-a449-ea34108bd539)


**Что сделано:**
Удалены новые дублирующиеся методы, ниже решение через использование healthcheck:

- Использован метод check_db_connection из HealthCheck. 
- Добавлен HealthCheckService для analytic_service в depends.py. 
- Добавлена схема ответа ActiveTasks для вывода в схеме ответа аналитики. 
- Создан метод get_count_active_tasks, который импользвет check_db_connection из HealthCheck для получения даты обновления и количества активных задач в services/analytics.py. 

**Где были произведены изменения:**

-  src/api/endpoints/analytics.py
-  src/api/schemas.py
-  src/api/services/analytics.py
-  src/depends.py

**Протестировано:**

- Все кнопки бота работают
- Остальные эндпоинты отдают тот же результат что и до изменений
- Число активных задач в /api/analytics/ сходится с числом активных задач в эндпоинте /api/health_check/
- Через эндпоинт Get All Tasks /api/tasks/ получил список всех задач и циклом посчитал количество активных в этом списке, получилось то же самое что в двух эндпоинтах указанных выше

2023-11-10 05:31 UTC, ArtemBalandin81 commented on src/api/endpoints/analytics.py
> +async def get_analytics(
а можно использовать response_model?
По типу как тут? Или это сложно для пайдентик?

```
@task_router.get(
    "/{user_id}",
    response_model=list[TaskResponse],
    response_model_exclude_none=True,
    description="Получает список всех задач из категорий на которые подписан юзер.",
)
@inject
async def get_tasks_for_user(
    user_id: int, task_service: TaskService = Depends(Provide[Container.task_service])
) -> list[TaskResponse]:
    return await task_service.get_tasks_for_user(user_id)
    ```

2023-11-10 05:35 UTC, ArtemBalandin81 requested changes

2023-11-10 05:35 UTC, ArtemBalandin81 commented on src/api/services/analytics.py
> +        last_update = data["last_update"]
Можешь посмотреть, как было в прежнем боте. Какой формат времени ожидался?
Получается, что у нас везде он разный. И можно ли избавиться от ненужного времени?
```
"tasks": {
    "last_update": "2023-11-04 00:00:00",
    "active_tasks": 1
  }
  ```

2023-11-10 07:11 UTC, Rederickmind commented on src/api/endpoints/analytics.py
> +async def get_analytics(
У нас DBStatus, который отдаёт check_db_connection() это TypedDict, я поискал и не нашёл чтобы в нем можно было как в Pydantic схеме просто исключить поля

2023-11-10 07:19 UTC, Rederickmind commented on src/api/services/analytics.py
> +        last_update = data["last_update"]
Посмотрю, а где ещё он другой? Тут то как раз то же самое что в /api/health_check/ и тот же формат, посмотрел другие эндпоинты, там время только в дедлайне задач и до определенного дня

С чем нужно сравнить формат и какой нам нужен?

2023-11-10 07:58 UTC, Rederickmind commented on src/api/services/analytics.py
> +        last_update = data["last_update"]
В старом коде такой же формат
![old](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/11664980/3849d0b9-0c94-4ec9-954d-3b25c4a11749)

В новом он вынесен в константу и получается используется для моего эндпоинта и для healthhcheck
![new](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/11664980/5c926570-ef92-42c7-ab1f-4001fb09ce3c)

Нужно убрать время и там, и там?

2023-11-11 10:22 UTC, Rederickmind commented on src/api/endpoints/analytics.py
> +async def get_analytics(
Дописал проверку, всё должно быть правильно

У нас уже есть проверка соединения с базой в health_check, которая отдает словарь db_status с полями об ошибке и статусом соединения с базой

Проверка:
```
async def check_db_connection(self) -> DBStatus:
        try:
            active_tasks = await self._repository.count_active_all()
            get_last_update = await self._repository.get_last_update()
        except SQLAlchemyError as exc:
            db_status: DBStatus = {"status": False, "db_connection_error": f"{exc.__class__.__name__}: {exc}"}
            return db_status
        if get_last_update is None:
            get_last_update = "Unable to get last_update"
        db_status: DBStatus = {
            "status": True,
            "last_update": get_last_update,
            "active_tasks": active_tasks,
        }
        return db_status
```

Словарь, который мы получаем:
- Если база инициализирована, но не загружены тестовые данные
```
{
    "status": true,
    "last_update": "Unable to get last_update",
    "active_tasks": 0
  }
```
- Если база неинициализирована:
```
{
    "status": false,
    "db_connection_error": "ProgrammingError: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.UndefinedTableError'>: relation \"tasks\" does not exist\n[SQL: SELECT count(*) AS count_1 \nFROM tasks \nWHERE tasks.is_archived = false]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
  } 
```

**Так как мы в src\api\services\analytics.py вызываем эту функцию, нам в случае ошибки соединения с базой должно отдавать словарь указанный выше**

Написал проверку этого поля в функции и альтернативное заполнение нужного нам в этом эндпоинте ActiveTasks

```
async def get_count_active_tasks(self) -> ActiveTasks:
        db_status: DBStatus = await self._health_check_service.check_db_connection()
        if db_status['status'] is False:
            tasks: ActiveTasks = {
                "last_update": "Unable to get last_update",
                "active_tasks": 0
            }
            return tasks
        last_update = db_status["last_update"]
        if last_update is None:
            last_update = "Unable to get last_update"
        active_tasks = db_status["active_tasks"]
        tasks: ActiveTasks(
            last_update=last_update,
            active_tasks=active_tasks
        )
        return tasks
```

Но всё равно получаю 500 ошибку при запросе до инициализации базы и заполнения тестовыми данными
![ошибка1](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/11664980/efe0ba67-0e19-46c5-aead-80fefc31e79c)

В терминале при запросе на /api/analytics/ пишет про ошибку в подсчете пользователей, возможно он падает поэтому и не доходит до моей функции
![Users count](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/11664980/acff0058-694a-4d77-8c66-938e50c070ae)

2023-11-11 10:48 UTC, Rederickmind commented
Дописал проверку, всё должно быть правильно

У нас уже есть проверка соединения с базой в health_check, которая отдает словарь db_status с полями об ошибке и статусом соединения с базой

Проверка:
```
async def check_db_connection(self) -> DBStatus:
        try:
            active_tasks = await self._repository.count_active_all()
            get_last_update = await self._repository.get_last_update()
        except SQLAlchemyError as exc:
            db_status: DBStatus = {"status": False, "db_connection_error": f"{exc.__class__.__name__}: {exc}"}
            return db_status
        if get_last_update is None:
            get_last_update = "Unable to get last_update"
        db_status: DBStatus = {
            "status": True,
            "last_update": get_last_update,
            "active_tasks": active_tasks,
        }
        return db_status
```

Словарь, который мы получаем:
- Если база инициализирована, но не загружены тестовые данные
```
{
    "status": true,
    "last_update": "Unable to get last_update",
    "active_tasks": 0
  }
```
- Если база неинициализирована:
```
{
    "status": false,
    "db_connection_error": "ProgrammingError: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.UndefinedTableError'>: relation \"tasks\" does not exist\n[SQL: SELECT count(*) AS count_1 \nFROM tasks \nWHERE tasks.is_archived = false]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
  } 
```

**Так как мы в src\api\services\analytics.py вызываем эту функцию, нам в случае ошибки соединения с базой должно отдавать словарь указанный выше**

Написал проверку этого поля в функции и альтернативное заполнение нужного нам в этом эндпоинте ActiveTasks

```
async def get_count_active_tasks(self) -> ActiveTasks:
        db_status: DBStatus = await self._health_check_service.check_db_connection()
        if db_status['status'] is False:
            tasks: ActiveTasks = {
                "last_update": "Unable to get last_update",
                "active_tasks": 0
            }
            return tasks
        last_update = db_status["last_update"]
        if last_update is None:
            last_update = "Unable to get last_update"
        active_tasks = db_status["active_tasks"]
        return ActiveTasks(
            last_update=last_update,
            active_tasks=active_tasks
        )
```

Но всё равно получаю 500 ошибку при запросе до инициализации базы и заполнения тестовыми данными
![ошибка1](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/11664980/efe0ba67-0e19-46c5-aead-80fefc31e79c)

В терминале при запросе на /api/analytics/ пишет про ошибку в подсчете пользователей, возможно он падает поэтому и не доходит до моей функции
![Users count](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/11664980/acff0058-694a-4d77-8c66-938e50c070ae)

2023-11-12 12:06 UTC, NiKuma0 commented on src/api/services/analytics.py
> +    async def get_count_active_tasks(self) -> ActiveTasks:
Похоже что вся эта логика больше относиться к отрисовке, нежели к сервисной. Давай ее перенесем во вьюху.

2023-11-12 12:06 UTC, NiKuma0 commented on src/api/services/analytics.py
> +        active_tasks = db_status["active_tasks"]
Это все можно объединить в один блок: 
```python
last_udpate = db_status["last_update"]
if not (db_status["status"] or db_status["last_update"]):
    last_update = "Unable to get last_update"
return ActiveTasks(last_update=last_update, active_tasks=db_status["active_tasks"])

2023-11-12 12:31 UTC, Rederickmind commented on src/api/services/analytics.py
> +    async def get_count_active_tasks(self) -> ActiveTasks:
Не очень понял этот комментарий

Мы же берем вьюху check_db_connection
А здесь уже вервисом дергаем из её результат только нужные значения

2023-11-12 12:33 UTC, Rederickmind commented on src/api/schemas.py
> +class ActiveTasks(TypedDict):
Уже переделал

2023-11-12 13:02 UTC, ArtemBalandin81 commented on src/api/services/analytics.py
> +    async def get_count_active_tasks(self) -> ActiveTasks:
Идея в том, чтобы рисовали эндпоинты, а сервисы только обращались к репозиториям и при этом не использовали пайдентик, чтобы быть универсальными (и для апи, и для бота).

Это очень тонкая настройка, постоянно сносит то туда, то сюда.
Нужно попробовать все немного перенастроить
Вот тут еще есть немного [мудрости](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/pull/271/files#r1390391752)

2023-11-12 16:36 UTC, Rederickmind commented on src/api/services/analytics.py
> +        active_tasks = db_status["active_tasks"]
Исправил, работает

2023-11-12 19:08 UTC, Rederickmind commented on src/api/services/analytics.py
> +    async def get_count_active_tasks(self) -> ActiveTasks:
Переделал как понял на созвоне, проверьте пожалуйста в нужную ли сторону проведены изменения

2023-11-12 19:09 UTC, Rederickmind commented
**Что сделано:**
- Оставил в src/api/services/analytics.py проверки и сделал чтобы сервис отдавал переменные, а не схему.
- Добавил в src/api/endpoints/analytics.py функцию для оборачивания переменных last_update, active_tasks в Pydantic схему ActiveTasks

**Где были произведены изменения:**

-  src/api/endpoints/analytics.py
-  src/api/services/analytics.py

2023-11-13 10:45 UTC, NiKuma0 approved these changes

2023-11-13 10:45 UTC, NiKuma0 commented on src/api/services/analytics.py
> +        return last_update, active_tasks
Вот эту всю логику перенеси в `get_active_tasks_analytic`, и можно мержить

2023-11-13 17:07 UTC, Rederickmind commented on src/api/services/analytics.py
> +        return last_update, active_tasks
Перенёс, проверьте пожалуйста всё ли ок

2023-11-13 17:08 UTC, Rederickmind commented
Откатил свои изменения в src/depends.py.
Перенес метод получения аналитики по задачам из src/api/services/analytics.py в src/api/endpoints/analytics.py

2023-11-16 04:40 UTC, ArtemBalandin81 commented on src/api/services/analytics.py
> +        return last_update, active_tasks
Наверное, можно подумать о выносе этой проверки в отдельную функцию
Возможна она должна использоваться и в других статистиках этого эндпоинта
Чтобы не затягивать ПР мерджу, но в когда всю статистику соберем, возможно немного отрефачим ее

2023-11-16 04:42 UTC, ArtemBalandin81 approved these changes

2023-11-16 04:42 UTC, merged