Создание декоратора auto_commit и рефакторинг директории repository
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #27
Opened 2023-04-28 17:34 UTC by yonvik

2023-04-29 10:39 UTC, NiKuma0 requested changes

2023-04-29 10:39 UTC, NiKuma0 commented on src/core/utils.py
> +async def auto_commit(commit=True):  # поставил True временно. Пока не напишется Service
Кажется ты немного не правильно понял задачу. Нужно пользоваться методами репозитория так, чтобы можно было отключить вызов функции `commit` прямо из сервиса. То есть в вызове метода был доп параметр - `commit`, и выглядело бы так: 
```python
async def some_service(repository):
  await repository.archive_all(commit=False)  
  # Теперь коммит не вызывается внутри репо, 
  # и мы можем делать транзакции или вызвать коммит на уровне сервиса 
  await repository._session.commit()  
```
У тебя, же, вырубается вызов коммита на уровне создания класса репозитория, это немного не солидно)

2023-04-29 14:56 UTC, NiKuma0 commented on src/core/utils.py
> +    async def auto_commit_wraps(self, commit=True):
Есть успехи - теперь объедини старый код с новый. В функциях репо не должен быть атрибут `commit=True` только декоратор. В самом декораторе вызови функцию (`func`) и оставь `wraps`.

2023-04-29 17:52 UTC, NiKuma0 requested changes
Потестируй приложение в свагере - localhost:8000/docs

2023-04-29 17:52 UTC, NiKuma0 commented on src/core/utils.py
> +        return func
```suggestion
        return await func(*args, **kwargs)
```

2023-05-01 17:29 UTC, yonvik commented on src/core/utils.py
> +        return func
В предлагаемых изменениях будет всё ломаться. Потому что мы должны вызывать просто функцию, без параметров. Если передавать параметры он будет ругаться на api/services что в них нет нужных нам параметров либо их больше чем нужно...(протестировал)
+ await в обычном вызове будет приводить к ошибке TypeError(object function can't be used in 'await' expression)

2023-05-02 22:57 UTC, NiKuma0 requested changes

2023-05-02 22:57 UTC, NiKuma0 commented on src/core/utils.py
> +async def auto_commit(func):
Эта функция не должна быть асинхронной. Мне кажется ты не очень хорошо понимаешь как работают декораторы. Почитай теорию, пособирай другие декораторы)

2023-05-02 22:57 UTC, NiKuma0 commented on src/core/utils.py
> +        await func(self, objects)
Мы должны возвращать результат работы фунции.  
```python
async def wraps(*args, **kwargs, commit=True):
    result = await func(*args, **kwargs)
    ...
    return result

2023-05-04 18:39 UTC, NiKuma0 requested changes

2023-05-04 18:39 UTC, NiKuma0 commented on src/core/db/repository/base.py
> +            auto_commit()
Очень не приятная функция. Она в любом случае должна делать коммит, иначе в ней нет смысла. Оставь как было. Но добавь аргумент `commit` в саму функцию - не через декоратор
```suggestion
            self._session.commit()
```

2023-05-05 13:23 UTC, merged