Добавлена статистика всех пользователей за период
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #271
Opened 2023-11-08 20:53 UTC by AndreiFilatov

Ответ с `/api/analytics/` после правок:
```
{
  "command_stats": {},
  "reasons_canceling": "",
  "number_users": 30,
  "all_users_statistic": {
    "added_users": {
      "2023-11-01": 1,
      "2023-11-04": 1
    },
    "added_external_users": {
      "2023-11-04": 1
    },
    "users_unsubscribed": {
      "2023-10-27": 1,
      "2023-10-31": 1,
      "2023-11-01": 1
    }
  },
  "active_users_statistic": {},
  "tasks": {}
}
```
![Response](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/96495051/680948e6-7b58-490e-a3ed-1775335cc3a4)

### Что сделано:
1. Добавлена библиотека `Faker=19.13.0` для генерации тестовых данных.
2. Добавлено заполнение таблиц `users` и `unsubscribe_reason` тестовыми данными.
3. Добавлен расчет показателей при обращении к `/api/analytics/` с параметром `date_limit`:
    * `added_users` &ndash; число пользователей, зарегистрировавшихся из бота за период в 30 дней до даты `date_limit`;
    * `added_external_users` &ndash; число пользователей, пришедших с сайта `https://procharity.ru/` за период в 30 дней до даты `date_limit`;
    * `users_unsubscribed` &ndash; число пользователей, отписавшихся от рассылки за период в 30 дней до даты `date_limit`.

### Внесенные изменения:
* **`src/fill_db.py`**
Добавлены функции `filling_user_in_db` и `filling_unsubscribe_reason_in_db` для наполнения таблиц `users` и `unsubscribe_reason` соответственно.

* **`src/depends.py`**
В `analytic_service` контейнера dependency_injector прокинут `unsubscribe_reason_repository`.

* **`src/core/db/repository/base.py`**
В класс `AbstractRepository` добавлен метод `get_statistics_by_days` с универсальным запросом к БД как в старом боте.

* **`src/api/schemas.py`**
Добавлен класс дополнительный класс `AllUsersStatistic` на базе `TypedDict` для его дальнейшего использования в основном классе для статистики `Analytic`.

* **`src/api/services/analytics.py`**
В класс `AnalyticsService` добавлен новый метод `get_all_users_statistic` для расчета необходимых показателей на базе метода `get_statistics_by_days`.

* **`src/api/endpoints/analytics.py`**
Добавлен вывод рассчитанных параметров `all_users_statistic` по запросу к эндпоинту.

### Тестирование
Для тестирования были сгенерированы тестовые данные в таблицах `users` и `unsubscribe_reason` и руками проверены результаты работы нового функционала при обращении к эндпоинту `/api/analytics/` с различными значениями параметра `date_limit`.

2023-11-09 05:12 UTC, ArtemBalandin81 requested changes

2023-11-09 05:12 UTC, ArtemBalandin81 commented on src/api/services/analytics.py
> +DAYS_NUMBER = 30
Нужно дополнительно обратить внимание - уточнить как в ТЗ предполагается:
- вынести в константы
- или в настройки проекта может быть
- или сделать более гибким

2023-11-09 05:12 UTC, ArtemBalandin81 commented on src/core/db/repository/base.py
> +    async def get_all_users_statistic(self, date_begin, date_limit, column_name) -> dict[str, int]:
изменить имя метода на более универсальное

2023-11-09 17:27 UTC, AndreiFilatov commented on pyproject.toml
> +faker = "19.13.0"
Можешь, пожалуйста, пояснить выражение "перенести в dev"?
Я понял, что нужно удалить эту зависимость из `poetry`. Но чтобы для разработки иметь возможность и далее использовать `Faker`, мне нужно создать копии файлов `poetry.lock` и `pyproject.toml`, назвав их `poetry_dev.lock` и `pyproject_dev.toml` соответственно, и в них `Faker` оставить? Чтобы при разработке использовать именно эти файлы, удаляя из них приписку `_dev`?

2023-11-09 17:44 UTC, AndreiFilatov commented on src/api/endpoints/analytics.py
> +    date_limit: date = "2023-11-20",
2. Артем, извини, не совсем понял твои вопросы.
Получается, некоторая логика апи определена в некотором ТЗ? Можешь, пожалуйста, подсказать, где и что можно посмотреть на этот счет? Не уверен, что смогу ответить на эти вопросы.

1. В зависимости от п 2. внесу необходимые изменения.
То, что я там оставил конкретную дату, это моя ошибка, просто для тестирования ее устанавливал и не удалил. Насколько я понял из описания апи предыдущей версии проекта, параметр `date_limit` был обязательным в этом энпоинте.
Ниже скрин из файла `api/front/analytics.py`
![Старая_версия](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/96495051/99176445-e5d8-41c1-bbdb-121e6385af9c)

2023-11-10 17:31 UTC, ArtemBalandin81 requested changes

2023-11-10 17:31 UTC, ArtemBalandin81 commented on pyproject.toml
> +faker = "19.13.0"
А если сначала просто удалить ее `poetry remove Faker`
А потом установить с флагом `--dev?`
`poetry add --dev Faker`

Я не много имел опыта работы с поэтри, но, очевидно, что Faker нужен лишь для разработки
В проекте есть разделение на основные пакеты и для разработки

2023-11-10 17:31 UTC, ArtemBalandin81 commented on src/api/endpoints/analytics.py
> +    date_limit: date = "2023-11-20",
`date_limit` конечно же нужен. Я лишь имел ввиду, что если он подставляется в форму апи, то было бы логично его привязать к текущей дате. Давай просто оставим форму пустой для начала, как ты и предложил, удалив дефолтное значение.
ТЗ в виде ТЗ по админке нам так и не спустили. Работаем с тем, что есть и ждем отмашки тимлида

2023-11-10 17:31 UTC, ArtemBalandin81 commented on src/api/endpoints/analytics.py
> +    date_limit: date = "2023-11-20",
или используем какое-нибудь поле с example, оставляем на твое усмотрение

2023-11-10 17:31 UTC, ArtemBalandin81 commented on src/api/schemas.py
> +class AllUsersStatistic(TypedDict):
Ждем отмашки Тимлида (можно почитать [драфт таски](https://github.com/orgs/Studio-Yandex-Practicum/projects/5/views/1?sortedBy%5Bdirection%5D=asc&sortedBy%5BcolumnId%5D=48553385&sortedBy%5Bdirection%5D=desc&sortedBy%5BcolumnId%5D=Linked+pull+requests&pane=issue&itemId=35652481) для понимания). Но в целом есть пожелания уйти от тайпдикта к пайдантик во вьюхах, не в сервисах. 

Предлагаю заменить на модель пайдентик, как в параллельной задаче по таскам (но и следить ,что тимлид отпишется там)

2023-11-12 11:47 UTC, NiKuma0 approved these changes
В целом все хорошо)

2023-11-12 11:47 UTC, NiKuma0 commented on src/api/schemas.py
> +class AllUsersStatistic(TypedDict):
Да, тут лучше использовать pydantic.

2023-11-12 11:47 UTC, NiKuma0 commented on src/api/services/analytics.py
> +    async def get_all_users_statistic(self, date_limit) -> AllUsersStatistic:
Лучше отталкивается от того, что API может измениться, поэтому предлагаю немного другую структуру.
В сервисах опишем методы, по типу `get_added_users_statistic` и т.п. а во вьюхе их вызывать:
```python
async def func(...):
    return AllUsersStatistic(
        added_users=await service.get_added_users_statistic,
        added_external_users=await service.get_added_external_users_statistic,
        ...
    )

2023-11-13 19:14 UTC, AndreiFilatov commented
### Внесенные изменения:
* **`pyproject.toml`**
Зависимость `Faker` перенесена в `dev`.
* **`requirements.txt`**
Зависимость `Faker` удалена.
* **`src/api/services/analytics.py`**
Вместо одной функции описаны 3 функции под каждый из показателей статистики:
    * `get_added_users_statistic`
    * `get_added_external_users_statistic`
    * `get_unsubscribed_users_statistic`
* **`src/api/schemas.py`**
Для класса `AllUsersStatistic` использована модель Pydantic `BaseModel` вместо `TypeDict`.
* **`src/api/endpoints/analytics.py`**
    1. Для параметра `date_limit` удалено значение по умолчанию, добавлен пример значения посредством `Query(..., example=...)`.
    2. Ответ на запрос собирается на базе модели `AllUsersStatistic` и отдельных функций `get_added_users_statistic`, `get_added_external_users_statistic` и `get_unsubscribed_users_statistic`.
* **`src/api/constants.py`**
В данный файл перенесены константы `DATE_FORMAT_FOR_STATISTICS` и `DAYS_NUMBER`, которые используются в файлах `src/api/services/analytics.py` и `src/core/db/repository/base.py` соответственно.

2023-11-16 14:13 UTC, NiKuma0 approved these changes

2023-11-16 19:08 UTC, ArtemBalandin81 commented on src/api/services/analytics.py
> +from src.api.constants import DAYS_NUMBER
Андрей Квичанский не пропустит такое имя)
Правда, лучше переименовать более понятно (кол-во дней к чему, чего?)

2023-11-16 19:44 UTC, AndreiFilatov commented
### Внесенные изменения:
* **`src/api/constants.py`** и **`src/api/endpoints/analytics.py`**
Переименовал константу `DAYS_NUMBER` в `DAYS_NUMBER_FOR_USERS_STATISTIC`.
* Устранил конфликты, которые возникли после разнесения схем из одного файла по нескольким файлам, лежащим в отдельной папке.

2023-11-18 13:35 UTC, NiKuma0 commented
Поправь конфликт, и можно мержить)

2023-11-18 14:04 UTC, AndreiFilatov commented
Конфликт поправил.

2023-11-18 20:12 UTC, ArtemBalandin81 requested changes

2023-11-18 20:12 UTC, ArtemBalandin81 commented on src/api/services/analytics.py
> +        return added_users
ну уж раз правим, то - лишняя переменная. Можно сразу return

2023-11-19 04:38 UTC, ArtemBalandin81 approved these changes

2023-11-19 04:52 UTC, merged

2023-11-19 20:16 UTC, AndreiFilatov commented on src/api/services/analytics.py
> +        added_users = await self._user_repository.get_statistics_by_days(date_begin, date_limit, "created_at")
Артем, понимаю твою мысль, но попробую защить такой способ)

В прошлой версии был использован следующий подход (скрин ниже) - в параметр функции передавалось конкретное поле с указанием модели.
![image](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/96495051/79e0cc15-7d43-449f-938f-0dfeaa2c919b)
Никита, когда ставил задачу, сформулировал ее следующим образом: "попробовать реализовать универсальный запрос к БД как в старом боте". Исходя из этого решил, что универсальнее всего будет добавить этот запрос в абстрактный класс `AbstractRepository`, на базе которого создаются классы с запросами к базе для других моделей. Обдумывая, как передать в метод класса нужное поле модели, участвующее в запросе, я решил так - вместо того, чтобы передавать в метод класса поле конкретное поле модели, достаточно будет передать только его имея, ведь саму модель я и так знаю, потому что она доступна внутри класса репозитория, метод которого я и вызываю. Т.е. вместо
```
added_users = await self._user_repository.get_statistics_by_days(date_begin, date_limit, User.created_at)
```
использую
```
added_users = await self._user_repository.get_statistics_by_days(date_begin, date_limit, 'created_at')
```
а саму модель определяю уже на уровне репозитория.

Если нужно сделать через `User.created_at` - не вопрос, я поправлю. Да и переименование полей самой модели в любом случае повлечет необходимость изменения данного кода.

2023-11-19 20:20 UTC, AndreiFilatov commented on src/api/services/analytics.py
> +        return added_users
Согласен. Могу поправить.
Это лучше сделать в рамках данного PR или уйти в отдельную задачу? Просто заметил, что ты создал под эти правки отдельную задачу в Backlog.