Разделить DI контейнер. #262
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #273
Opened 2023-11-09 19:29 UTC by Ogyrecheg

Разделил контейнер. Как тестировал: дергал за эндпоинты, чинил код, DI - боль.

2023-11-10 05:19 UTC, ArtemBalandin81 requested changes

2023-11-10 05:19 UTC, ArtemBalandin81 commented on src/depends.py
> +class SettingsContainer(containers.DeclarativeContainer):
А по отдельным файлам не нужно раскидать контейнеры?

2023-11-10 06:26 UTC, beskrovniibv commented on src/depends.py
> +class SettingsContainer(containers.DeclarativeContainer):
> А по отдельным файлам не нужно раскидать контейнеры?

Вероятно станет неудобно импортировать их. Не знаю, насколько это будет хорошо, но на первый взгляд кажется, что создать пакет `depends` в пакете `core` решит проблему с неудобным импортом.

2023-11-12 10:59 UTC, NiKuma0 requested changes

2023-11-12 10:59 UTC, NiKuma0 commented on src/depends.py
> +    """Контейнер зависимостей Settings."""
Не вижу смысла создавать один контейнер для одной зависимости. Предлагаю оставить `settings` в основном контейнере.

2023-11-12 10:59 UTC, NiKuma0 commented on src/depends.py
> +    settings = providers.Container(SettingsContainer)
Зачем тут целый контейнер? Достаточно просто `settings`. Используй [`Dependency` провайдер](https://python-dependency-injector.ets-labs.org/providers/dependency.html), как было в примере из документации.

2023-11-12 10:59 UTC, NiKuma0 commented on src/depends.py
> +    data_base_connection = providers.Container(DataBaseConnectionContainer)
Тут и в других местах, используй [`DependenciesContainer` провайдер](https://python-dependency-injector.ets-labs.org/api/providers.html?highlight=dependenciescontainer#dependency_injector.providers.DependenciesContainer), как было в примере из документации.

2023-11-13 18:35 UTC, Ogyrecheg commented
Поправил контейнер, используя советы, которые Никита озвучил на воскресном демо.
Тестировал энд поинты, тыкал кнопки в боте

2023-11-18 13:34 UTC, NiKuma0 commented
@Ogyrecheg Не забудь поправить конфликт.

2023-11-20 21:34 UTC, Ogyrecheg commented
Ребят, устранил конфликты, тестировал ручками свагер + бота мучал.

2023-11-21 16:11 UTC, NiKuma0 requested changes

2023-11-25 19:20 UTC, Ogyrecheg commented
Обновил requirements (не отрабатывал скрипт fill_db.py), починил конфликты мерджа

2023-11-26 22:56 UTC, NiKuma0 approved these changes

2023-11-28 13:43 UTC, merged