Разделил schemas.py на файлы в папке src/api/schemas/
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #275
Opened 2023-11-12 12:08 UTC by Rederickmind

Заполнил _init…_.py файл, проверил что за счет него импорты в остальных файлах не сломались, эндроинты API работают, бот работает

**Изменения:**
- Удален оригинальный файл schemas.py
- Добавлена папка со схемами по адресу src/api/schemas/:
  - src/api/schemas/__init__.py
  - src/api/schemas/admin.py
  - src/api/schemas/analytics.py
  - src/api/schemas/base.py
  - src/api/schemas/categories.py
  - src/api/schemas/external_site_user.py
  - src/api/schemas/health_check.py
  - src/api/schemas/notification.py
  - src/api/schemas/tasks.py

Файлы разделены по логике эндпоинтов, в остальных файлах импорты работают за счет __init__py
Нужно ли в остальных файлах в коде прописывать полные пути до файлов со схемами или мы оставим такое использование?

**Протестировано:**
- Запустил проект с изменениями, проверил что все эндпоинты отдают схемы как раньше
- В боте тоже изменений в работе не увидел

2023-11-12 12:34 UTC, ArtemBalandin81 approved these changes
Проверил на сервере. Ошибок не выявлено

2023-11-12 18:21 UTC, Rederickmind commented
Убрал из __init__.py # noqa
Добавил переменную __all__

2023-11-13 13:33 UTC, NiKuma0 requested changes

2023-11-13 13:33 UTC, NiKuma0 commented on src/api/schemas/__init__.py
> +    TaskResponse,
Это должен быть список строк)

2023-11-13 17:16 UTC, Rederickmind commented on src/api/schemas/__init__.py
> +    TaskResponse,
Поправил

2023-11-16 08:45 UTC, NiKuma0 approved these changes
Поправь конфликт, и можно мержить.

2023-11-16 14:33 UTC, merged