Создана миграция и инструкция по мигрированию
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #276
Opened 2023-11-12 12:46 UTC by AlexBatanov

2023-11-12 13:32 UTC, NiKuma0 approved these changes
В целом все отлично) Добавь описание как это было протестировано, с примерами до/после.

2023-11-12 13:32 UTC, NiKuma0 commented on src/core/db/migrations/versions/2023-11-11_12.18.35_initial.py
> +        op.alter_column("users", "external_signup_date", new_column_name="updated_at")
Кажется это поле отвечает за дату привязки `User` к `ExternalSiteUser`. Добавь это поле в нашу модель `User`.

2023-11-12 13:32 UTC, NiKuma0 commented on src/core/db/migrations/versions/2023-11-11_12.18.35_initial.py
> +    if not inspector.has_table("admin_token_requests"):
Кажется мы эту модель не используем, она не важна, можно просто ее не трогать.

2023-11-12 13:32 UTC, NiKuma0 commented on src/core/db/migrations/versions/2023-11-11_12.18.35_initial.py
> +    if not inspector.has_table("notifications"):
Этого у нас тоже нет... Давай добавим модель в `models.py`, может пригодится)

2023-11-12 13:32 UTC, NiKuma0 commented on src/core/db/migrations/versions/2023-11-11_12.18.35_initial.py
> +    if not inspector.has_table("statistics"):
Также нет этой модели. Давай не будем ее создавать)

2023-11-13 11:24 UTC, AlexBatanov commented
тестирование происходило следующим образом:
накатывался дамп, сохранял поля таблиц и выборку данных
на дам накатывалась миграция и сравнивал что поля изменились, данные не пострадали и заполнились верно
![data_new_tasks](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/115994817/032c78fd-cfdc-49d7-be65-98d5ac778548)
![data_new_users](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/115994817/e5235059-414d-4f1f-8956-317cd1fe5b73)
![data_old_tasks](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/115994817/82fa3b30-038d-43f2-99ab-0955b3a61f39)
![data_old_users](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/115994817/8e32c4bd-14ef-4586-8168-9efbcdfeab87)
![new_tasks](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/115994817/555f591a-b82f-44b0-addf-8712591620b3)
![new_users](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/115994817/d3b34181-f982-4568-b7e3-2a45bdcc147a)
![old_task](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/115994817/7f9ad6a2-100d-4700-bd2b-a13a735ab7f5)
![old_users](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/115994817/9cbcdf25-0fb5-41c5-b915-42ac11277271)

2023-11-16 05:34 UTC, ArtemBalandin81 requested changes
при попытке деплоя ветки на сервер получаю следующую ошибку:

Deploy
The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

Возможно, требуется обновление компонентов в actions?
Другой ПР залился без проблем

2023-11-16 18:47 UTC, ArtemBalandin81 approved these changes
![migrations](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/105808126/ec3cde7a-883d-405d-87fa-9aa37973109e)
Видел что удавалось победить, но сейчас снова нет.
Может ли быть, что что-то перезатерлось последующими мерджами на сервере?

2023-11-18 08:42 UTC, merged