Изменить ссылку на сайт.
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #278
Opened 2023-11-14 21:33 UTC by Ogyrecheg

Убрал урлы в константы, применил константы в ссылках проекта.
Тестировал все ссылки ручками, корректно подтягивался нужный урл.

2023-11-15 08:42 UTC, NiKuma0 requested changes

2023-11-15 08:42 UTC, NiKuma0 commented on src/bot/constants/urls.py
> +TEST_PROCHARITY_URL = "http://test6.procharity.corptest.ru/"
Я же в задаче описал что у нас может меняться ссылка, поэтому ее нужно в сетинги убрать, таким образом, чтобы ее можно было просто изменить в `.env` файле.

2023-11-15 21:27 UTC, Ogyrecheg commented
Теперь необходимые урлы для проекта можно достать из settings.py. Инжектил урлы в нужные места кода из контейнера Container. Тестировал ручками бота, по всем ссылкам переходит

2023-11-16 19:07 UTC, beskrovniibv commented on src/settings.py
> +    PROCHARITY_URL: str
Не вполне очевидно, как задать нужные значения? Передаём через `.env`? Тогда надо добавить информацию в `env.example`

2023-11-16 19:07 UTC, beskrovniibv commented on src/bot/handlers/tasks.py
> +    detailed_text = display_task_verbosely(task, settings.HELP_PROCHARITY_URL)
См. замечание к функции.

2023-11-16 23:47 UTC, Ogyrecheg commented on src/core/utils.py
> +def display_task_verbosely(task, url):
Попробовал убрать подстановку url внутрь функции, код уходит в ошибку цикличного импорта ...

2023-11-16 23:48 UTC, Ogyrecheg commented on src/core/utils.py
> +def display_task_verbosely(task, url):
![1](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/98617958/cf59fd03-b0dc-4b37-ae79-16356f32cd4b)

2023-11-18 12:59 UTC, NiKuma0 commented on src/settings.py
> +    PROCHARITY_URL: str
Добавь дефолтное значение. Также стоит добавить [валидатор](https://docs.pydantic.dev/2.1/api/networks/#pydantic.networks.AnyHttpUrl), чтобы в случае если предоставили не валидный url, приложение валилось сразу. 
```suggestion
    PROCHARITY_URL: AnyHttpUrl = "https://procharity.ru"
```

2023-11-18 12:59 UTC, NiKuma0 commented on src/settings.py
> +    YA_PRAKTIKUM_URL: str
Тут также. Дефолтное значение и валидатор.

2023-11-18 12:59 UTC, NiKuma0 commented on src/settings.py
> +    PROCHARITY_URL_USER: str
Не очень понятно, зачем тут три (`HELP_PROCHARITY_URL` третья) дополнительных переменных. Давай без них)

2023-11-18 12:59 UTC, NiKuma0 commented on src/core/utils.py
> +def display_task_verbosely(task, url):
Не похоже на антипаттерн, да и код понятный - можно оставить как есть, но я бы добавил тайп хинты.

2023-11-18 13:32 UTC, NiKuma0 commented on src/core/utils.py
> +    bonus_link = f"{url}article/10053"
> Ссылка может уехать, если, например, информация на сайте обновится. Ты, фактически, вместо URL только подставляешь домен. Кажется, этого может оказаться недостаточно.

@beskrovniibv ты имеешь ввиду что эндпоинт `/article/` может измениться?
Можно смело рассчитывать что такого не произойдет. В ином случае, нам скорее всего понадобится всю логику переделывать)

2023-11-19 22:20 UTC, Ogyrecheg commented
Комрады, прикрутил костыльный валидатор урлов(settings.py), из коробки оно не работало. Убрал "лишние" переменные для урлов (settings.py), поправил функции(src/core/utils.py), учитывая комментарии ревьюверов.

2023-11-19 22:21 UTC, Ogyrecheg commented on src/core/utils.py
> +    bonus_link = f"{url}article/10053"
Готово

2023-11-20 17:45 UTC, beskrovniibv commented on src/settings.py
> +    HELP_PROCHARITY_URL: Url = "https://help.procharity.ru/"
Случилось то, чего я ждал, что случится.
В `src/bot/utils.py` у тебя есть `return f"{settings.PROCHARITY_URL}auth/bot_procharity.php?user_id={external_id}&telegram_id={telegram_id}"`
Легко заметить, как отсутствие `/` всё сломало.
Предлагаю в константы писать без слэшей (но допускать их наличие), а потом слеш дописать (если необходимо).

2023-11-20 18:59 UTC, Ogyrecheg commented
Ребят, добавил валидатор для последнего слеша в url (settings.py), протестировал ручками, вроде работает (при отсутствии последнего слеша в константе урла .env файла, автоматом дописывает его)

2023-11-20 20:14 UTC, beskrovniibv approved these changes
Как будто бы ок

2023-11-21 15:33 UTC, NiKuma0 commented on env.example
> +YA_PRAKTIKUM_URL =https://praktikum.yandex.ru/ # URL Ya Praktikum
```suggestion
YA_PRAKTIKUM_URL=https://praktikum.yandex.ru/ # URL Ya Praktikum
```

2023-11-21 15:33 UTC, NiKuma0 commented on src/bot/utils.py
> +        # return settings.PROCHARITY_URL_USER.format(external_id=external_id, telegram_id=telegram_id)
Убери комментарий.

2023-11-21 15:33 UTC, NiKuma0 commented on src/settings.py
> +Url = Annotated[str, BeforeValidator(lambda value: str(TypeAdapter(AnyHttpUrl).validate_python(value)))]
Зачем это? Почему просто не использовать `AnyHttpUrl` вместо `Url`?

2023-11-21 16:03 UTC, Ogyrecheg commented on src/settings.py
> +Url = Annotated[str, BeforeValidator(lambda value: str(TypeAdapter(AnyHttpUrl).validate_python(value)))]
Отвечаю: из коробки AnyHttpUrl не работает
![1](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/98617958/2215389a-1d9b-461b-9d3d-552a75dc1ad0)

2023-11-21 16:13 UTC, Ogyrecheg commented
Убрал лишние пробелы в env.example. Убрал комментарии

2023-11-24 09:37 UTC, NiKuma0 approved these changes

2023-11-24 09:37 UTC, merged