Add healthcheck in workwflow
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #287
Opened 2023-11-25 10:57 UTC by sushidze

2023-11-25 14:01 UTC, NiKuma0 requested changes
Workflow падает с ошибкой, посмотри и поправь.

2023-11-25 14:01 UTC, NiKuma0 commented on .github/workflows/healthcheck.yaml
> +  HEALTHCHECK_API_URL: 'procharity.duckdns.org'
Это не обязательная переменная и не верная.

2023-11-25 14:01 UTC, NiKuma0 commented on .github/workflows/healthcheck.yaml
> +  APPLICATION_URL: 'procharity.duckdns.org'
```suggestion
  APPLICATION_URL: 'http://localhost:8000'
```

2023-12-16 11:45 UTC, tWoAlex commented
Запуск Workflow в тесте `pull_request` падает из-за старой логики эндпойнта `api/health_check/` в ветках `develop` и `master`

2023-12-16 12:08 UTC, tWoAlex commented on .github/workflows/healthcheck.yaml
> +  EMAIL_ADMIN: 'procharityadmin_1@yandex.ru'
https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/actions/runs/7231774544/job/19705317001?pr=287
Константы `ORGANIZATIONS_EMAIL` и `EMAIL_ADMIN` являются обязательными для загрузки настроек

2023-12-17 12:08 UTC, NiKuma0 requested changes

2023-12-17 12:08 UTC, NiKuma0 commented on README.md
> +    docker-compose -f infra/docker-compose.local.yml up
Оставь как было.

2023-12-17 12:08 UTC, NiKuma0 commented on requirements.txt
> +GitPython==3.1.34 ; python_version >= "3.11" and python_version < "4.0"
Это тут не нужно.

2023-12-17 12:08 UTC, NiKuma0 commented on .github/workflows/healthcheck.yaml
> +        echo EMAIL_ADMIN=${{ env.EMAIL_ADMIN }} >> .env
Не вижу параметров для инфы о коммите. [Посмотри этот воркфлоу](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/blob/develop/.github/workflows/deploy_stage.yaml#L109)

2023-12-19 07:41 UTC, tWoAlex commented
* На данный момент workflow работает.
* Протестирован внутри своей ветки `feature/add-healthcheck-in-workflow` с учётом изменений в логике эндпойнта `api/health_check/`, предложенных в этом PR.
* Протестирован при помощи триггера `push → feature/add-healthcheck-in-workflow`. Сейчас триггер убран из кода.

2023-12-23 10:35 UTC, ArtemBalandin81 commented on src/api/services/health_check.py
пустая строка?

2023-12-23 10:35 UTC, ArtemBalandin81 commented on src/api/endpoints/health_check.py
> +    # last_commit_data["git_tags"] = [str(tag) for tag in last_commit_data["git_tags"]]
лучше без комментариев

2023-12-23 10:36 UTC, ArtemBalandin81 commented on src/api/endpoints/health_check.py
> +    last_commit_data = await health_check_service.get_last_commit()
лишняя переменная?

2023-12-23 11:21 UTC, tWoAlex commented on src/api/services/health_check.py
Хук `black` (`./.pre-commit-config.yaml`) автоматически проставляет отсуп после импорта

2023-12-23 11:31 UTC, tWoAlex commented on src/api/services/health_check.py
У меня есть встречный вопрос:

Импорт `from git import Repo` появился в методе `HealthCheckService.get_last_commit` до меня.
Уместно ли его вынести под импорты в начале модуля, обернув в `try-catch` с получением флага успешного импорта, чтобы избежать повторных вызовов внутри метода, довольствуясь лишь проверкой флага?

2023-12-25 13:57 UTC, ArtemBalandin81 commented on src/api/services/health_check.py
@NiKuma0

2023-12-28 13:35 UTC, NiKuma0 commented on src/api/services/health_check.py
> У меня есть встречный вопрос:
> 
> Импорт `from git import Repo` появился в методе `HealthCheckService.get_last_commit` до меня. Уместно ли его вынести под импорты в начале модуля, обернув в `try-catch` с получением флага успешного импорта, чтобы избежать повторных вызовов внутри метода, довольствуясь лишь проверкой флага?

Не вижу в этом особого смысла.

2023-12-28 13:36 UTC, NiKuma0 approved these changes

2023-12-28 13:38 UTC, merged