change /group logic
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #297
Opened 2023-12-08 21:35 UTC by AI-Stratov

1. Реализована отправка сообщений по user_id в эндпоинте /messages/group/
2. Реализована валидация на уровне сервиса. 3 кейса - Нет пользователя, У пользователя нет telegram_id, Пользователь отказался от рассылки
3. Для каждого случая из этих ошибок предусмотрен Exception (SendMessageError), который также обрабатывается в сервисном слое
4. Чтобы не нарушать работу других эндпоинтов, сервисная логика выполняется в новом методе
5. Соответственно изменены комментарии и docstring эндпоинта
6. Соответственно изменена схема MessageList

Тестирование:
Создал записи в таблице User для каждого случая. Проверил ошибки валидации из пункта 2. Проверил, что сообщение теперь отправляется не по telegram_id, а по User.id.

PS. Поскольку к отношениям между моделями бд возникли вопросы во время первого синхрона, считаю что в рамках данной задачи не следует их трогать. Лучше создать отдельную таску, при работе над которой погрузиться в то, почему ExternalSiteUsers не связана с User. В тексте задачи есть упоминание того, что у модели ExternalSiteUser есть user_id, это неправда :) ExternalSiteUser используется, чтобы зарегистрировать пользователя и записать его как User в registration.py. При этом, когда User создается, у него прописывается telegram_id из effective_user.id. А external_id заполняется данными из ExternalSiteUser, который уже должен быть в базе (получение через id_hash). В общем, использование эндпоинта для того, чтобы отравить сообщение по user.id мне показалось наиболее целесообразным. Наверное, при составлении таски это и имели в виду. Могу переделать на отправку по external_id, если я не прав.

2023-12-09 05:03 UTC, ArtemBalandin81 commented
Оформи пожалуйста пост в пачке
Мы так не делаем:
![no status](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/105808126/aa960864-e267-4b52-9ea1-f5b30040100e)

2023-12-11 10:24 UTC, NiKuma0 requested changes

2023-12-11 10:24 UTC, NiKuma0 commented on src/api/services/messages.py
> +log = structlog.get_logger(module=__name__)
Зачем `mudule`? structlog так по дефолту работает.

2023-12-11 10:24 UTC, NiKuma0 commented on src/api/services/messages.py
> +        try:
Лучше поставить `try: except:` вне функции - во время ее вызова:

```python
async def some_func(...):
    try:
        telegram_notification_service.send_message_to_user_by_id(...)
    except ...:
        ...
```

Так уменьшим вложенность кода и будем следовать второму принципу SOLID.

2023-12-11 10:24 UTC, NiKuma0 commented on src/api/services/messages.py
> +                raise SendMessageError(user_id, "User blocked the bot")
В идеале, все эти ошибки нужно вынести в отдельные классы, которые будут наследоваться от `SendMessageError`.

2023-12-12 14:24 UTC, NiKuma0 requested changes

2023-12-12 14:24 UTC, NiKuma0 commented on src/api/router.py
> +# api_router.include_router(analytic_router, prefix="/analytics", tags=["Analytic"])
Оставь как было. Это часть когда нужна в версии 2.1, но не в 2.0

2023-12-12 14:26 UTC, AI-Stratov commented on src/api/router.py
> +# api_router.include_router(analytic_router, prefix="/analytics", tags=["Analytic"])
Ок, я просто обновился от дефолтной ветки

2023-12-12 14:32 UTC, AI-Stratov commented on src/api/router.py
> +# api_router.include_router(analytic_router, prefix="/analytics", tags=["Analytic"])
Ок, тогда я комиты не откатываю? Можно

2023-12-12 14:39 UTC, NiKuma0 commented on src/api/router.py
> +# api_router.include_router(analytic_router, prefix="/analytics", tags=["Analytic"])
Нужно сначала на сервере твою ветку запустить, потом мержить.

2023-12-12 14:42 UTC, NiKuma0 requested changes

2023-12-12 14:42 UTC, NiKuma0 commented on pyproject.toml
> +typing-extensions = "4.8.0"
Эти изменения пока не должны попасть в `develop`

Наследуйся в следующий раз от ветки `develop` а не от `dev-2.1`. Тебе придется все переделать - тут очень много изменений...

2023-12-12 14:43 UTC, AI-Stratov commented on pyproject.toml
> +typing-extensions = "4.8.0"
Хорошо. Я просто подумал, что ветка 2.1 под новую группу разрабов была создана

2023-12-12 14:57 UTC, AI-Stratov commented on pyproject.toml
> +typing-extensions = "4.8.0"
Тогда наверное этот закрыть, а новый я создал уже

2023-12-12 16:07 UTC, closed without merging

2023-12-12 16:36 UTC, AI-Stratov commented
Информация для потомков: переезд сюда:
https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/pull/304