Send message by user id
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #304
Opened 2023-12-12 14:56 UTC by AI-Stratov

Изменения те же, что и https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/pull/297, но отнаследовал ветку от develop

2023-12-16 16:25 UTC, ArtemBalandin81 commented on src/api/endpoints/notification.py
> +            status, msg = await telegram_notification_service.send_message_to_user_by_id(message.user_id, message)
Покажется придиркой, но на курсе "били по рукам" за сокращенные имена переменных ("msg")
Кажется, мы стараемся не использовать их и в этом проекте.
Мб получится как-то выкрутиться и переименовать так, чтобы было понятно и не плодились мессаджи?

2023-12-16 16:36 UTC, ArtemBalandin81 commented on src/api/services/messages.py
> +    async def send_message_to_user_by_id(self, user_id, notifications) -> tuple[bool, str]:
Предлагаю заменить на send_message_to_user_by_user_id
Иначе немного запутывает: какой ай-ди?, месседжа, или юзера?

2023-12-16 16:37 UTC, ArtemBalandin81 commented on src/api/services/messages.py
> +        user_i: User | None = await self._session.scalar(select(User).where(User.id == user_id))
неудачное имя user_i

2023-12-16 16:43 UTC, ArtemBalandin81 commented on src/api/endpoints/notification.py
> +        except SendMessageError as e:
аналогично выше

2023-12-16 16:44 UTC, ArtemBalandin81 commented
Предложил бы до конца решить задачу, предложив вариант связки моделей

2023-12-17 12:36 UTC, NiKuma0 requested changes

2023-12-17 12:36 UTC, NiKuma0 commented on src/api/services/messages.py
> +        user_i: User | None = await self._session.scalar(select(User).where(User.id == user_id))
Сервисы не обращаются на прямую к sqlalchemy. Этим занимаются репозитории.
Используй `UserRepository`, не нужно переизобретать велосипед.

2023-12-17 12:36 UTC, NiKuma0 commented on src/api/services/messages.py
> +            raise TelegramIDNotFoundError(user_id)
Такого не может быть, telegram_id обязательное поле.

2023-12-17 12:42 UTC, AI-Stratov commented on src/api/endpoints/notification.py
> +            status, msg = await telegram_notification_service.send_message_to_user_by_id(message.user_id, message)
Согласен, я мимикрировал под чужой, уже существующий код. Исправлю. Для понятности, на мой взгляд, надо передавать данные между слоями как data transfer object, сделаю pydantic схемы. Потому что эта "распаковка" на месте, через запятую, тоже так себе

2023-12-17 12:42 UTC, AI-Stratov commented on src/api/services/messages.py
> +    async def send_message_to_user_by_id(self, user_id, notifications) -> tuple[bool, str]:
Ок.

2023-12-17 12:47 UTC, AI-Stratov commented on src/api/services/messages.py
> +            raise TelegramIDNotFoundError(user_id)
Было в условии задачи. Уберу

2023-12-17 12:48 UTC, AI-Stratov commented on src/api/services/messages.py
> +        user_i: User | None = await self._session.scalar(select(User).where(User.id == user_id))
Согласен, но кто-то уже в сервисе обращается к базе и даже зависимость прокинул. Чужой код исправить или не трогать?

2023-12-17 12:49 UTC, AI-Stratov commented on src/api/services/messages.py
> +        user_i: User | None = await self._session.scalar(select(User).where(User.id == user_id))
Ок.

2024-02-27 06:45 UTC, closed without merging