добавлен хук блокировки бота
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #325
Opened 2024-01-02 07:23 UTC by ViktorAllayarov

## Что сделано
1) в файле src\bot\handlers\registration.py  добавлен хук ChatMemberHandler(on_chat_member_update)
2) в файле src\bot\services\user.py добавлен метод `user_banned_update ` сервиса `UserService`
3) в файле src\core\db\repository\user.py добавлен метод `update_user_banned`  репозитория `UserRepository`

## Как проверял
- заблокировал бота, проверил в базе статус User.banned
- разблокировал бота, проверил в базе статус User.banned

2024-01-06 10:04 UTC, NiKuma0 approved these changes

2024-01-11 11:52 UTC, NiKuma0 requested changes

2024-01-11 11:52 UTC, NiKuma0 commented on src/bot/handlers/registration.py
> +    await user_service.user_banned_update(telegram_id=update.effective_user.id)
Нужно точно указать, пользователь был забанен или нет, а не менять статус на противоположный - иначе это может привести к доп. багам.

Можно ли из этого update понять, пользователь заблокировал бот или разблокировал?

2024-01-30 20:44 UTC, gwaimui commented on src/bot/handlers/registration.py
> +    await user_service.user_banned_update(telegram_id=update.effective_user.id)
Добавлены два метода user_banned и user_unbanned для вычисления статуса отдельно для каждого случая. bot/handlers/registration добавлен extract_status_change и уточнен on_chat_member_update.

Проверка: забанила, добавила бота, изменение статуса BANNED фиксирует

2024-02-02 17:25 UTC, gwaimui commented on src/bot/handlers/registration.py
> +    await user_service.user_banned_update(telegram_id=update.effective_user.id)
Решение
https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/pull/343/commits/354d45b85975d775daa7ee9133c0d7b525be6801

2024-02-04 11:46 UTC, gwaimui commented on src/bot/handlers/registration.py
> +    ext_user_service: ExternalSiteUserService = Provide[Container.bot_services_container.bot_site_user_service],
связь с моделью конкретного пользователя

2024-02-04 14:49 UTC, closed without merging