Fix/group send message
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #339
Opened 2024-01-18 16:24 UTC by Pav4l

fix early PR

2024-01-22 12:55 UTC, NiKuma0 requested changes
Добавь инфу как это было протестировано и [привяжи ПР к задаче](https://www.notion.so/Wiki-017a7e5894604b75942b3ba9ac8ed092?pvs=4#35b396f7ac1447b19c88cf839d1e11c0).

2024-01-22 12:55 UTC, NiKuma0 commented on src/api/endpoints/external_site_user.py
> +    if not site_user.id:
Нам в любом случае передается `id`.
Проверь есть ли `ExternalSiteUser` с `id_hash` который передается, если да, выполняй `update`.

2024-01-22 12:55 UTC, NiKuma0 commented on src/api/schemas/external_site_user.py
> +    id: Optional[int] = Field(None)
```suggestion
    id: int | None = None
```

2024-01-22 12:55 UTC, NiKuma0 commented on src/core/db/models.py
> +    user_id: Mapped[int] = mapped_column(ForeignKey("users.id", name="fk_external_site_users_user_id"), nullable=True)
Добавь поле `external_id`, а `id_hash` переименуй в `external_id_hash` (и сделай его `unique=True` и `index=True`). 

У нас будет два поле `external_id` и `id` - первое будет передаваться из сайта, второе будет генерироваться автоматом.

2024-01-29 07:37 UTC, Pav4l commented on src/core/db/models.py
> +    user_id: Mapped[int] = mapped_column(ForeignKey("users.id", name="fk_external_site_users_user_id"), nullable=True)
fix

2024-01-29 07:37 UTC, Pav4l commented on src/api/schemas/external_site_user.py
> +    id: Optional[int] = Field(None)
fix

2024-01-29 07:37 UTC, Pav4l commented on src/api/endpoints/external_site_user.py
> +    if not site_user.id:
fix

2024-01-30 13:07 UTC, NiKuma0 requested changes

2024-01-30 13:07 UTC, NiKuma0 commented on src/api/endpoints/external_site_user.py
> +    if site_user.id:
Эту логику нужно убрать в сервис.

2024-01-30 13:07 UTC, NiKuma0 commented on src/api/endpoints/external_site_user.py
> +            raise ValueError("ExternalSiteUser с указанным id_hash не найден.")
`id` и `id_hash` это два разных поля.

Эта ошибка лишняя, лучше ее убрать. В случае если пользователь не найден, его нужно создать.

2024-02-05 13:53 UTC, Pav4l commented on src/core/db/repository/external_site_user.py
> +            .values({ExternalSiteUser.user_id: user_id, ExternalSiteUser.updated_at: func.current_timestamp()})
fix

2024-02-05 13:53 UTC, Pav4l commented on src/core/db/repository/external_site_user.py
> +    async def update_user_id_in_external_site_user(self, ext_user_id, user_id):
fix

2024-02-05 13:53 UTC, Pav4l commented on src/core/db/repository/user.py
> +        return result.scalar_one_or_none()
fix

2024-02-05 13:53 UTC, Pav4l commented on src/api/endpoints/external_site_user.py
> +            raise ValueError("ExternalSiteUser с указанным id_hash не найден.")
fix

2024-02-05 13:53 UTC, Pav4l commented on src/api/endpoints/external_site_user.py
> +    if site_user.id:
fix

2024-02-28 12:57 UTC, closed without merging