Feature/invitation token checker 2
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #340
Opened 2024-01-19 09:05 UTC by Melnik-ni

Были удалены лишние строки и поменян статус с 201 на 200

2024-01-22 12:40 UTC, NiKuma0 requested changes

2024-01-22 12:40 UTC, NiKuma0 commented on src/authentication.py
> +    if not registration_record or registration_record.token_expiration_date < datetime.now():
Эту логику лучше убрать в сервис.

2024-01-23 17:45 UTC, ArtemBalandin81 commented on src/authentication.py
> +    return JSONResponse(content={"description": "Токен подтвержден."}, status_code=status.HTTP_200_OK)
Не нужно ли здесь использовать пайдентик схему?

2024-01-23 17:55 UTC, ArtemBalandin81 commented on src/authentication.py
> +async def check_invitation_token(
Складывается ощущение, что эта функция вообще лишняя и можно обойтись без нее, перенеся логику в сервис
Нужно покрутить и посмотреть как описаны остальные эндпоинты, не фастапи юзерс

2024-01-30 11:22 UTC, NiKuma0 requested changes

2024-01-30 11:22 UTC, NiKuma0 commented on src/api/schemas/token_schemas.py
> +class TokenCheckResponse(BaseModel):
Так делать не нужно - у нас есть своя базовая модель в `src.schemas.base`, от нее наследуйся

2024-01-30 11:25 UTC, NiKuma0 reviewed
Понажимай `Resolve conversation` под решеными комментариями.

2024-01-30 11:25 UTC, NiKuma0 commented on src/api/endpoints/admin.py
> +    admin_user_router.include_router(register_router, prefix="/auth", tags=["auth"])
Не очень понимаю, зачем тут был изменён этот блок?

2024-01-31 18:48 UTC, Melnik-ni commented on src/api/endpoints/admin.py
> +    admin_user_router.include_router(register_router, prefix="/auth", tags=["auth"])
Тут мой затуп был. Все поменял и проверил регистрацию с актуальным токином и несуществующим. В обоих случаях проверка прошла успешно.

2024-01-31 18:49 UTC, Melnik-ni commented on src/api/schemas/token_schemas.py
> +class TokenCheckResponse(BaseModel):
Спасибо, не заметил.

2024-01-31 22:42 UTC, gorskyolga commented on src/authentication.py
>          },
Это точно нужно удалять? Это относится к регистрации, а не к эндпоинту для проверки токена..

2024-01-31 22:58 UTC, gorskyolga commented on src/api/services/admin_token_request.py
> +            raise InvalidInvitationToken
Так как эта проверка была перенесена из create_with_token из UserManager (src/authentication.py), то её нужно удалить оттуда.

2024-01-31 23:04 UTC, gorskyolga commented on src/api/services/admin_token_request.py
> +        return TokenCheckResponse(description="Токен подтвержден.")
Кажется, так лучше не делать. При регистрации админа create_with_token при вызове get_by_token ожидает получить объект AdminTokenRequest из БД (берёт из нее email и удаляет запись из БД после успешной регистрации).

2024-02-01 13:30 UTC, Melnik-ni commented on src/api/services/admin_token_request.py
> +            raise InvalidInvitationToken
Устранил.

2024-02-01 17:54 UTC, gorskyolga commented on src/authentication.py
> -        await self.user_db.update(user, {"last_login": date.today()})
Это удаление точно нужно?

2024-02-01 18:02 UTC, gorskyolga commented on src/api/schemas/token_schemas.py
> +    description: str
Все остальные схемы в проекте импортируются в `src/api/schemas/__init__.py` и далее импортируются из него. Лучше сделать также.

2024-02-04 14:57 UTC, NiKuma0 approved these changes

2024-02-04 14:58 UTC, merged