updated tasks schemas add fields+
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #349
Opened 2024-01-28 18:09 UTC by gwaimui

**Что сделано**

В **src.core.db.models** и **src.api.schemas.tasks** добавлены поля в БД (для Tasks)
legal_address - Юридический адрес
fund_city - город фонда
fund_rating - рейтинг фонда
fund_site - сайт фонда
yb_link - ссылка на ютуб
vk_link - ссылка на vk
fund_sections - деятельность фонда (в виде массива id категорий)

В **src.api.schemas.base** настроена не строгая валидация ([strict=False] для RequestBase

**Проверка**
Запрос get/api/tasks Get All Tasks и post/api/tasks Actualize Tasks на предмет корректности полей + при внесении изменений в Request body (валидный json)

2024-01-29 04:35 UTC, ArtemBalandin81 requested changes
Не уверен, что правильно с моделями.
Нет файла миграций, чтобы проверить работоспособность

2024-01-29 04:35 UTC, ArtemBalandin81 commented on src/api/schemas/tasks.py
> +    fund_city: StrictStr = Field(
интересно, а это не тоже самое - что `location` ниже?
или `location` - это местонахождения самой задачи, тогда нужно там поправить описание

2024-01-29 04:35 UTC, ArtemBalandin81 commented on src/api/schemas/tasks.py
> +    legal_address: StrictStr = Field(
здесь с описанием аналогично

2024-01-29 04:35 UTC, ArtemBalandin81 commented on src/core/db/models.py
> +    fund_sections: Mapped[list["Category"]] = relationship("Category", back_populates="funds")
А здесь не пропущена `secondary=funds_categories`? 
По аналогии с моделью User:
```
    categories: Mapped[list["Category"]] = relationship(
        "Category", secondary="users_categories", back_populates="users"
    )
 ```

2024-01-29 04:35 UTC, ArtemBalandin81 commented on src/core/db/models.py
> +    funds: Mapped[list["Task"]] = relationship("Task", back_populates="fund_sections")
и тут secondary?

2024-01-29 19:10 UTC, gwaimui commented on src/api/schemas/tasks.py
> +        ..., example="My Organization Legal Adress", description="Юридический адрес организации, оставившей задачу."
Принято

2024-01-29 19:10 UTC, gwaimui commented on src/api/schemas/tasks.py
> +    legal_address: StrictStr = Field(
Замечания учтены

2024-01-29 19:11 UTC, gwaimui commented on src/core/db/models.py
> +    fund_sections: Mapped[list["Category"]] = relationship("Category", back_populates="funds")
Замечания учтены

2024-01-29 19:11 UTC, gwaimui commented on src/core/db/models.py
> +    funds: Mapped[list["Task"]] = relationship("Task", back_populates="fund_sections")
Замечания учтены

2024-01-30 12:02 UTC, NiKuma0 requested changes

2024-01-30 12:02 UTC, NiKuma0 commented on src/core/db/models.py
> +class Fund(Base):
Не вижу особого смысла в этой модели. Чтобы ее добавить, нужно также изменить логику создания задач, поэтому давай обойдемся без этой модели.

2024-01-30 12:02 UTC, NiKuma0 commented on src/api/schemas/tasks.py
>      class Config:
Лучше избавиться от устаревшего метода конфигурации. Если он используется только примеров, то смело удаляй, достаточно `Field(example="something")`

2024-02-01 10:20 UTC, NiKuma0 requested changes

2024-02-01 10:20 UTC, NiKuma0 commented on src/core/db/migrations/versions/2024-01-31_08.28.16_.py
> +    #            nullable=False)
Почему тут часть миграций закомментирована?

2024-02-01 10:20 UTC, NiKuma0 commented on src/core/db/models.py
> +    funds: Mapped[list["Task"]] = relationship("Task", secondary="funds_categories", back_populates="fund_sections")
Зачем это поле? Лучше его просто убрать, вместе с `FundsCategories` - тут будет совсем другая структура данных. Сейчас просто сделай `fund_sections: Mapped[list[int]]`

2024-02-13 05:15 UTC, ArtemBalandin81 requested changes

2024-02-13 05:15 UTC, ArtemBalandin81 commented on src/api/schemas/tasks.py
> +    name_organization: StrictStr | None = Field(..., example="My Fund", description="Название Фонда.")
```StrictStr | None```
- Название же не может быть пустым? Как и юр.адрес, город. - мне кажется, тут должно быть строгая аннотация

2024-02-13 05:15 UTC, ArtemBalandin81 commented on src/api/schemas/tasks.py
> -        json_schema_extra = {
`json_schema_extra` точно не зря удалили?
`class Config` полностью устарел, если так  -то куда-то `json_schema_extra` дб переместиться
+ ее нужно расширить, т.к. добавились новые поля

2024-02-13 05:15 UTC, ArtemBalandin81 commented on src/api/schemas/tasks.py
> +    name_organization: StrictStr | None = Field(..., example="My Fund", description="Название Фонда.")
тут аналогично выше

2024-02-13 05:15 UTC, ArtemBalandin81 commented on src/api/schemas/tasks.py
> -        json_schema_extra = {
и тут

2024-02-13 05:15 UTC, ArtemBalandin81 commented on src/core/db/migrations/versions/2024-02-02_15.11.29_.py
> +def upgrade() -> None:
миграции не прошли
```
ERROR [alembic.util.messaging] Multiple head revisions are present for given argument 'head'; please specify a specific target revision, '<branchname>@head' to narrow to a specific head, or 'heads' for all heads
FAILED: Multiple head revisions are present for given argument 'head'; please specify a specific target revision, '<branchname>@head' to narrow to a specific head, or 'heads' for all heads
Error: Process completed with exit code 255.
```

2024-02-13 05:15 UTC, ArtemBalandin81 commented on src/core/db/models.py
> +    name_organization: Mapped[str] = mapped_column(String, nullable=True)
nullable=True в общем, вызывает вопросы
если действительно, так, тогда выше претензии можно снять
Нужно уточнить у заказчика (Никиты)

2024-02-13 19:05 UTC, NiKuma0 commented on src/api/schemas/tasks.py
> +    name_organization: StrictStr | None = Field(..., example="My Fund", description="Название Фонда.")
Строгую аннотацию лучше не делать.

2024-02-13 19:05 UTC, NiKuma0 commented on src/api/schemas/tasks.py
> -        json_schema_extra = {
Это лишнее, лучше убрать

2024-02-14 15:17 UTC, NiKuma0 approved these changes

2024-02-14 15:20 UTC, merged