Feature/add downgrade
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #350
Opened 2024-01-29 18:17 UTC by Melnik-ni

Были скопированы методы создания миграции в функцию downgrade, а затем, заменены на противоположные. 
Тестил, запустил команду откатки миграции и не была получена ошибка.

2024-01-30 11:29 UTC, NiKuma0 requested changes

2024-01-30 11:29 UTC, NiKuma0 commented on src/core/db/migrations/versions/2024-01-11_16.21.54_v2_0.py
> +    op.create_table("statistics")
Тут нужно добавить подробности, что за таблица - это можно позаимствовать из той миграции, где таблица создавалась.

В следующий раз протестируй, пройдись сверху вниз по миграциям и обратно.  При этом БД должна быть заполнена какими либо данными.

2024-01-31 14:59 UTC, Melnik-ni commented on src/core/db/migrations/versions/2024-01-11_16.21.54_v2_0.py
> +    op.create_table("statistics")
Исправил замечание.
Пробежался по миграциям и все было успешно

2024-02-01 09:19 UTC, NiKuma0 approved these changes

2024-02-01 09:19 UTC, merged