add swag
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #36
Opened 2023-05-16 14:57 UTC by Aleksey-shipkov

2023-05-16 18:37 UTC, NiKuma0 requested changes

2023-05-16 18:37 UTC, NiKuma0 commented on infra/docker-compose.swag.yml
> +      - "9999:5432"
Оставь по дефолту
```suggestion
      - "5432:5432"
```

2023-05-16 18:37 UTC, NiKuma0 commented on infra/docker-compose.swag.yml
> +      - URL=procharity.duckdns.com
```suggestion
      - URL=procharity.duckdns.org
```

2023-05-16 18:37 UTC, NiKuma0 commented on infra/docker-compose.swag.yml
> +      - /procharity2/full/nginx_logs:/var/log/nginx
используй относительный путь:
```suggestion
      - ../nginx_logs:/var/log/nginx
```

2023-05-16 18:37 UTC, NiKuma0 commented on infra/docker-compose.swag.yml
> +      test: [ "CMD-SHELL", "pg_isready" ]
Добавь `-U ${POSTGRES_USER}` - сервер валится, не работает, [тут объяснение](https://stackoverflow.com/questions/60193781/postgres-with-docker-compose-gives-fatal-role-root-does-not-exist-error)

2023-05-16 18:44 UTC, NiKuma0 commented on infra/docker-compose.swag.yml
> +      - URL=procharity.duckdns.com
Давай лучше упакуем в переменную `APPLICATION_URL`  домен может поменяется

2023-05-16 19:24 UTC, Aleksey-shipkov reviewed
Resolved

2023-05-18 13:41 UTC, NiKuma0 requested changes

2023-05-18 13:41 UTC, NiKuma0 commented on infra/docker-compose.swag.yml
> +      - URL=${APPLICATION_URL}
Добавь к запуску докер компауза инфу где искать .env файл, без этого он падает с ошибкой на сервере

![image](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/78080842/2368395b-22a5-4211-824e-a1d760969505)

2023-05-18 13:41 UTC, NiKuma0 commented on infra/swag_nginx.conf
> +    server_name procharity.duckdns.com;
Тут добавь переменную из окружения. Кажется из-за этой строки я получаю статус 403.

2023-05-18 13:41 UTC, NiKuma0 commented on infra/docker-compose.swag.yml
> +      - URL=${APPLICATION_URL}
Также стоит почистить все контайнеры перед запуском `docker container rm $(docker container ls -q)`

2023-05-18 18:29 UTC, NiKuma0 commented on .github/workflows/deploy_stage.yaml
> +            docker compose --file docker-compose.yaml --env-file ../.env up -d --remove-orphans
По хорошему тут должно быть три команды: 
1. Запулить наше приложение
2. Запустить командой `docker compose up` - она автоматически подменит контейнер, да так, что пользователь и не заметит) 
3. Удалить все что не используется командой `docker system prune -a -f`

2023-05-19 11:39 UTC, NiKuma0 approved these changes
Очень хорошо, починили старые ошибки. Вот только все еще нет доступа на сайт. Думаю это уже на стороне FastAPI. Поправь замечания, и будем мержить.

2023-05-19 14:03 UTC, merged