Feature/category context saving
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #38
Opened 2023-05-18 15:21 UTC by Eltimccc

Добавил:
- Сохранение котегорий в контексте user_data;
- Выбранные подкатегории отмечаются галочкой (✅);
- Работает кнопка назад из подкатегорий.

2023-05-19 10:36 UTC, elych-ru commented on src/bot/handlers.py
> +    await query.message.edit_text("Выберите категории", reply_markup=reply_markup)
Выше бот обращается с пользователем на "ты", имхо нужно единообразно в разных частях интерфейса обращаться, т.е. если принимаем обращение на "ты", то здесь (и ниже) нужно "Выбери".

2023-05-19 10:40 UTC, elych-ru commented on src/bot/keyboards.py
>      keyboard.extend(categories_buttons)
Выше идёт инициализация пустого списка keyboard, а список categories_buttons далее не используется. Предлагаю избавиться от лишнего списка и всё сразу делать в keyboard.

2023-05-19 10:42 UTC, elych-ru commented on src/bot/handlers.py
> +    if subcategory_id in selected_categories:
Для небольшого списка категорий/подкатегорий это, конечно, не критично, но если упороться по алгоритмической сложности, тут получится сначала один поиск в списке, потом (remove) - второй. Может использовать тип set для хранения списков категорий/подкатегорий?

2023-05-19 12:12 UTC, NiKuma0 requested changes

2023-05-19 12:12 UTC, NiKuma0 commented on src/bot/handlers.py
> +    subcategory_id = int(query.data.split("_")[2])
Вообще тут по-хорошему нужен regex поиск. Что если мы решим поменять наши калбаки? Будет очень хорошо если при этом не придется менять хендлеры

2023-05-19 12:38 UTC, NiKuma0 commented on src/bot/handlers.py
> +    subcategory_id = int(query.data.split("_")[2])
Когда добавляешь паттерн, в хендлер передается Match объект - кажется его можно получить в функции если указать аргумент `match` или из `context`-а. Посмотри в документации.

2023-05-19 16:39 UTC, Eltimccc commented on src/bot/handlers.py
> +    subcategory_id = int(query.data.split("_")[2])
Я переделал как ты сказал, но любопытно, я когда переделывал, то без matсh и re, тоже калбэки работали же. А так создаем переменные, модуль, импортируем, и .match добавляется, целое дело в общем. Какой профит?)

2023-05-20 11:03 UTC, NiKuma0 commented on src/bot/handlers.py
> +    subcategory_match = select_category_pattern.match(query.data)
Это можно взять из контекста `context.match` или `context.matches`

2023-05-22 13:30 UTC, NiKuma0 commented on src/bot/handlers.py
> +    parent_id = int(query.data.split("_")[1])
Тут тоже используй `match`

2023-05-22 13:30 UTC, NiKuma0 commented on src/bot/handlers.py
> +    if subcategory_match:
Если бы не было match-а хендлер бы не запустился. Убери вложенность кода

2023-05-22 13:30 UTC, NiKuma0 commented on src/bot/handlers.py
> +        selected_categories = set(context.user_data.get("selected_categories", []))
Переводить из листа в сет а потом обратно в сет - это большая нагрузка. Можно использовать dict.

2023-05-22 13:30 UTC, NiKuma0 commented on src/bot/keyboards.py
> +        if category.id not in context.user_data.get("selected_categories", [])
Давай тут использовать обычный цикл. Генератор слишком большим получился.

2023-05-22 17:49 UTC, NiKuma0 requested changes

2023-05-22 17:49 UTC, NiKuma0 commented on src/bot/handlers.py
> +        selected_categories[subcategory_id] = "this is a subcategory"
```suggestion
        selected_categories[subcategory_id] = None
```

2023-05-22 17:49 UTC, NiKuma0 commented on src/bot/handlers.py
> +    reply_markup = await get_subcategories_keyboard(parent_id, context)
Давай лучше будем передавать в функцию только то, что необходимо для ее работы/цели. В этом случае хватит только `selected_categories.keys()`

2023-05-24 11:54 UTC, NiKuma0 commented on src/bot/handlers.py
> +    if not parent_id_match:
Зачем это определять в отдельную переменную? Можно проще 
```suggestion
    if not context.match:
```

К тому же, если не будет context.match хендлер не запуститься - поэтому эта проверка не имеет смысла. Если посмотришь исходники, там вообще в случае если нет match-а атрибут не задается (обращение к `context.match` - будет падать с ошибкой AttributeError), но это может произойти только если паттерн не указан.

2023-05-24 11:54 UTC, NiKuma0 commented on src/bot/handlers.py
> +    parent_id = int(parent_id_match.group(1))
```suggestion
    parent_id = int(context.match.group(1))

```

2023-05-24 11:54 UTC, NiKuma0 commented on src/bot/handlers.py
> +    if subcategory_id in selected_categories.keys():
```suggestion
    if subcategory_id in selected_categories:

```
Так будет работать быстрее.

2023-05-24 11:54 UTC, NiKuma0 commented on src/bot/handlers.py
> +    reply_markup = await get_subcategories_keyboard(parent_id, context)
И тут поправь.

2023-05-25 13:27 UTC, NiKuma0 commented on src/bot/keyboards.py
> +async def get_subcategories_keyboard(parent_id, *selected_categories):
```suggestion
async def get_subcategories_keyboard(parent_id, selected_categories):
```
Мы договорились что selected_categories это dict (было бы не плохо если бы ты добавил аннотации), его нельзя распаковать с помощью `*` - это можно только для итерируемого объекта.

2023-05-25 13:27 UTC, NiKuma0 commented on src/bot/keyboards.py
> +    selected_categories = selected_categories
Это зачем?

2023-05-25 13:29 UTC, NiKuma0 commented on src/bot/keyboards.py
> +# Галочки по началу ставятся, но не сохраняются. потом выходит ошибка
Опиши этот баг в карточке с задачей, потом поправим.

2023-05-26 11:59 UTC, NiKuma0 approved these changes

2023-05-26 11:59 UTC, merged