Feature/email format
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #388
Opened 2024-02-28 18:25 UTC by mvolodka

Добавлены шаблоны для отправки писем на почту как было в старом проекте, также были добавлены методы для отправки этих писем, метод для создания ссылок с токеном.

2024-02-29 11:04 UTC, NiKuma0 requested changes

2024-02-29 11:04 UTC, NiKuma0 commented on src/core/services/email.py
> +            email (str): email получателя
Лучше использовать стиль документации (например [как в этом примере](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html)), это нужно чтобы IDE могла парсить эти сообщения и подсказывать за что отвечает аргумент.

Эта док стринга похоже на стиль гугл, только вот вместо "Аргументы" должно быть `Args:`

2024-03-02 06:42 UTC, mvolodka reviewed
Создание токена вынесено в отдельный файл, в функциях отправки писем аргументы в докстрингах обозначены Args.

2024-03-07 07:46 UTC, mvolodka commented on src/core/services/email.py
> +        template_body = self.create_link_with_token(email, "invitation_link")
Создание токена вынесено в отдельный сервис, в методы отправки ссылок на регистрацию и сброс пароля добавлен аргумент token: str.

2024-03-07 07:47 UTC, mvolodka commented on src/core/services/email.py
> +            email (str): email получателя
Исправил на Args, Парсинг аргументов работает.

2024-03-07 09:08 UTC, NiKuma0 requested changes

2024-03-07 09:08 UTC, NiKuma0 commented on src/api/services/create_invitation_token.py
> +async def create_invitation_token(
Давай придерживаться нашей архитектуры и не будем из сервиса обращаться к БД.
Создай класс репозитория для работы с токенами, и его сервис.

2024-03-07 09:08 UTC, NiKuma0 commented on src/settings.py
> +    TOKEN_EXPIRATION: int = 24
Обычно подсчет идет в секундах, поэтому это может сбить с толку. Давай как и везде поменяем на секунды
```suggestion
    TOKEN_EXPIRATION: int = 60 * 60 * 24
```

2024-03-08 23:40 UTC, NiKuma0 commented on src/api/services/create_invitation_token.py
> +async def create_invitation_token(
Если есть сервис для работы с токенами то перенеси туда эту функцию (сделав ее методом). А в `AdminTokenRequestRepository` добавь не достающие методы, чтобы сервис на прямую не обращался к БД, а только через репозитории.

2024-03-10 14:35 UTC, mvolodka commented on src/api/services/create_invitation_token.py
> +async def create_invitation_token(
В сервисе `AdminTokenRequestService` и репозитории `AdminTokenRequestRepository` добавлены методы `create_invitation_token` для работы с токенами, обращение к БД через репозитории. Время жизни токена переведено в секунды: `TOKEN_EXPIRATION: int = 60 * 60 * 24`.

2024-03-14 10:51 UTC, NiKuma0 approved these changes

2024-03-14 18:17 UTC, merged