Изменены кнопки меню.
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #392
Opened 2024-03-02 11:05 UTC by eugemos

### Что сделано
Изменены кнопки меню согласно заданию:
- убрана кнопка "О платформе";
- добавлены кнопки "Написать в службу поддержки" и "Перейти в личный кабинет";
- исправлены наименования и значки, где требовалось.

### Как проверял
Заходил в бот, вызывал меню и нажимал в нём на все кнопки:
- новая кнопка  "Написать в службу поддержки" открывает веб-приложение;
- новая кнопка "Перейти в личный кабинет" открывает надлежащую ссылку на сайт;
- остальные кнопки работают, как и раньше.

2024-03-04 13:56 UTC, ArtemBalandin81 reviewed
1. Вместо кнопки "подписаться на задания" у меня локально появляется "отменить подписку на задания"
2. А переименовывать тоже нужно было кнопки местами?
3. "О платформе" осталась, но нигде более не используется. Возможно не прав, но на демо кажется речь шла о том, чтобы ее спрятать (перенести) в меню (там где /start). Могу ошибаться (нужно уточнить у PM )

2024-03-04 14:00 UTC, NiKuma0 reviewed
В целом все хорошо.

2024-03-04 14:00 UTC, NiKuma0 commented on src/bot/keyboards.py
>  QUESTION_BUTTON_TITLE = "❓ Задать вопрос"
Старые кнопки нужно убрать, как и функции которые теперь не используется.

2024-03-04 16:36 UTC, eugemos commented on src/bot/keyboards.py
>  QUESTION_BUTTON_TITLE = "❓ Задать вопрос"
Старые кнопки пока ещё используются в меню, которое формируется в обработчике команды /start. Это меню содержит только эти кнопки. Убрать его?

2024-03-04 17:12 UTC, NiKuma0 commented on src/bot/keyboards.py
>  QUESTION_BUTTON_TITLE = "❓ Задать вопрос"
> Старые кнопки пока ещё используются в меню, которое формируется в обработчике команды /start. Это меню содержит только эти кнопки. Убрать его?

Да, убери.

2024-03-05 15:14 UTC, NiKuma0 requested changes

2024-03-05 15:14 UTC, NiKuma0 commented on src/bot/handlers/registration.py
> -        user = await user_service.register_user(
Зачем было это удалять? Это нужно, оставь.

2024-03-07 09:02 UTC, merged