Add transaction for ContentService
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #41
Opened 2023-05-19 15:28 UTC by maria-shi

2023-05-20 10:44 UTC, NiKuma0 requested changes
Похоже это не должно работать. Расскажи - как проходили тесты? Нужно дополнительно пройтись в сваггере (`localhost:8000/docs`)

2023-05-20 10:44 UTC, NiKuma0 commented on src/api/services/base.py
> +            session.commit()
тут должен быть `await` и вообще, `async with self._session.begin()`

2023-05-21 17:44 UTC, maria-shi commented
Отправила новый коммит. Проверила в сваггере, категории обновляются. Возникла проблема с проверкой задач: эндпоинт /api/tasks (GET) возвращает 500 статус, причем даже если вернуть код к изначальному варианту. При POST-запросе возвращается статус 200, как и в категориях, но проверить, сработали ли изменения, не могу.

2023-05-21 18:01 UTC, NiKuma0 commented
> При POST-запросе возвращается статус 200, как и в категориях, но проверить, сработали ли изменения, не могу.

Можно - зайди в БД `docker compose exec postgres psql -U <user> <dbname> select * from categories;`

2023-05-21 18:19 UTC, NiKuma0 requested changes
Куда все делась?)

2023-05-21 18:19 UTC, NiKuma0 commented on src/api/services/base.py
> +            yield session
Этого не надо. Уже есть, да и не нужно - используй `Depends`

2023-05-21 18:19 UTC, NiKuma0 commented on src/api/services/base.py
> +        async with self.get_async_session():
Куда делись транзакции?

2023-05-21 18:19 UTC, NiKuma0 commented on src/api/services/base.py
>      def __init__(self, repository: any = Depends()):
У нас есть базовый класс ContentRepositry - давай добавим его в аннотации. 
```suggestion
    def __init__(self, repository: ContentRepository= Depends()):
```
Также - сделай этот класс абстрактным. Есть вероятность, что `Depends` не будет наследоваться, в таком случае, убери его от сюда и вставь в наследуемые классы (`TaskService` и `CategoryService`)

2023-05-23 19:42 UTC, closed without merging