plus_one_title
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #427
Opened 2024-03-26 13:52 UTC by Melnik-ni

Было добавлено новое условие для того чтобы при просмотре актуальных заданий, ели их нет то выскакивает уведомление "Актуальных заданий по твоим компетенциям на сегодня нет."

2024-03-28 21:44 UTC, gorskyolga commented on src/bot/handlers/tasks.py
> +    if not tasks_to_show:
Пробовал вместо записывания shown_tasks в context проверять в этом месте также, что page_number == 1?

2024-03-31 18:19 UTC, eugemos requested changes

2024-03-31 18:19 UTC, eugemos commented on src/bot/handlers/tasks.py
> +    if not tasks_to_show:
Ты сравниваешь всё множество уже показанных задач с множеством задач на одной странице, и если на этой странице новых задач нет, то делаешь вывод, что их вообще нет. Что-то здесь не то.

2024-04-03 10:22 UTC, gorskyolga commented
Давай в рамках этого  PR решать только случай, когда в БД вообще нет заданий по компетенциям пользователя и ему нужно вместо сообщения, что он всë посмотрел, отобразить сообщение, что заданий нет. Изначально я только подразумевала.
Баг про зацикливание последней порции заданий будем решать отдельно.

2024-04-09 10:36 UTC, eugemos approved these changes

2024-04-09 13:02 UTC, gorskyolga approved these changes

2024-04-10 21:15 UTC, merged