Fisrts commit
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #43
Opened 2023-05-20 15:36 UTC by KonstKorn

Добавлена фильтрация в соответствии с таской. Изменены флаги в соответствии с таской и внесены соответствующие коррективы в db/models.py, db/repository/category.py и api/schemas.py. Ошибка запроса Get для получения всех объектов Task (отсутствует 4 поля (title, name_organization, deadline, description) в БД и всех миграциях несмотря на то, что в модели эти поля есть.

2023-05-20 16:50 UTC, NiKuma0 requested changes

2023-05-20 16:50 UTC, NiKuma0 commented on .env.example
> -# Переменные приложения
Оставь файл. Не нужно его удалять

2023-05-20 16:50 UTC, NiKuma0 commented on src/api/services/base.py
> +        await self._repository.set_update_is_archived_false_to_true(ids)
Может проще `archive_by_ids`?

2023-05-20 16:50 UTC, NiKuma0 commented on src/api/services/base.py
> +        already_have = await self._repository.get_ids_not_is_archived(ids)
По имени вообще не понятно что делает функция (возвращает ids?); предлагаю `get_all_non_archived_and_by_ids`

2023-05-20 16:50 UTC, NiKuma0 commented on src/core/db/repository/base.py
> +                )
```suggestion
                self._model.id.in_(ids)
                | (self._model.is_archived == False)
```

2023-05-20 16:50 UTC, NiKuma0 commented on src/core/db/repository/base.py
> +            )
Как по мне, двойной where более читабельным чем `and_`. Надо будет так на всем проекте поправить, но пока только у тебя.
```suggestion
            .where(self._model.is_archived == False)
            .where(self._model.id.not_in(ids))
```

2023-05-20 16:50 UTC, NiKuma0 commented on src/core/db/repository/category.py
> +            select(Category).where(and_(not_(Category.is_archived)), Category.parent_id.is_(None)))
Вообще можно воспользоваться `session.scalars(<query>)` это будет работать так же как `session.execute(<query>).scalars().all()`. И поменяй структуру запросов, чтобы было также как я описал выше.

2023-05-20 16:50 UTC, NiKuma0 commented on src/core/db/models.py
>      description = Mapped[str]
Вот из-за этого ляпа у нас не создаются миграции... Поправишь? 
```suggestion
    description: Mapped[str]
```

2023-05-20 18:23 UTC, KonstKorn commented on .env.example
> -# Переменные приложения
Я не удалял. Просто как по ридми убрал .example. Верну этот файл обратно

2023-05-20 18:24 UTC, KonstKorn commented on src/api/services/base.py
> +        await self._repository.set_update_is_archived_false_to_true(ids)
Понял. Поменяю.

2023-05-20 18:24 UTC, KonstKorn commented on src/api/services/base.py
> +        already_have = await self._repository.get_ids_not_is_archived(ids)
Понял. Поменяю.

2023-05-20 18:24 UTC, KonstKorn commented on src/core/db/repository/base.py
> +                )
Понял. Поменяю.

2023-05-20 18:25 UTC, KonstKorn commented on src/core/db/repository/base.py
> +            )
Понял. Поменяю.

2023-05-20 18:25 UTC, KonstKorn commented on src/core/db/repository/category.py
> +            select(Category).where(and_(not_(Category.is_archived)), Category.parent_id.is_(None)))
Понял. Поменяю.

2023-05-20 18:26 UTC, KonstKorn commented on src/core/db/models.py
>      description = Mapped[str]
Как же я то не заметил... Поменяю и создам новую миграцию.

2023-05-20 18:35 UTC, KonstKorn commented on src/core/db/repository/base.py
> +            )
Только вроде not_in вроде нет команды, у меня ошибку выдавал. А к notin не было вопросов)

2023-05-21 11:48 UTC, NiKuma0 reviewed
Думаю проблема с миграцями из-за **не** пустой БД. Попробуй ее очистить:
```bash
docker compose -f infra/docker-pg.yml down -v
```

2023-05-21 11:48 UTC, NiKuma0 commented on src/core/db/migrations/versions/2023-05-21_12.41.59_feature_category_and_task_model.py
Эта миграция ничего не делает. Убери

2023-05-21 11:48 UTC, NiKuma0 commented on src/core/db/models.py
> +    title: Mapped[str] = mapped_column(nullable=True)
Почему `nullable=True`? Если проблемы с миграциями, попробуй удалить БД `docker compose down -v`. Могут быть проблемы с fill_db.py - проверь, и сообщи мне - сделаю таску.

2023-05-21 11:48 UTC, NiKuma0 commented on src/core/db/models.py
> +    is_archived: Mapped[bool] = mapped_column(default=False)
Кажется тут тоже не должно быть nullable.

2023-05-21 11:48 UTC, NiKuma0 commented on src/core/db/models.py
> +    __allow_unmapped__ = True
Это зачем?

2023-05-21 11:48 UTC, NiKuma0 commented on src/core/db/models.py
> +    children: relationship("Category", backref=backref("parent", remote_side="Category.id"))
Это не должно работать...

2023-05-21 11:48 UTC, NiKuma0 commented on src/core/db/repository/base.py
> +CURRENT_DATE = datetime.now().strftime(DATE_FORMAT)
Тут будет не текущая дата, а дата запуска приложения. Также, не нужно приводить к строке - sqlalchemy сам все сделает.

2023-05-21 11:48 UTC, NiKuma0 commented on src/core/db/repository/base.py
> +            .where(str(self._model.deadline) == CURRENT_DATE)
Не очень понимаю зачем тут это условие, пояснишь?

2023-05-21 11:48 UTC, NiKuma0 commented on src/core/db/repository/category.py
> +        return categories
Я бы сделал как-то так, если согласен, можешь немного отрефачить. Ради такой предирки ПР не охото задерживать)

```suggestion
        return await self._session.scalars(
            select(Category)
            .where(Category.is_archived == False)
            .where(Category.parent_id == None)  # noqa
        )
```

2023-05-21 12:26 UTC, KonstKorn commented on src/core/db/migrations/versions/2023-05-21_12.41.59_feature_category_and_task_model.py
Странно, да. Убрал

2023-05-21 12:27 UTC, KonstKorn commented on src/core/db/models.py
> +    title: Mapped[str] = mapped_column(nullable=True)
Это так изначально было, я тут  ничего не трогал, кроме = поменял на  :. сейчас уберу и проверю

2023-05-21 12:29 UTC, KonstKorn commented on src/core/db/models.py
> +    is_archived: Mapped[bool] = mapped_column(default=False)
Это все тоже  так было. Ничего не трогал. Уберу.

2023-05-21 12:31 UTC, KonstKorn commented on src/core/db/models.py
> +    __allow_unmapped__ = True
потому что тут так -  children: relationship("Category", backref=backref("parent", remote_side="Category.id"))
без этого не работают миграции

2023-05-21 12:31 UTC, KonstKorn commented on src/core/db/models.py
> +    children: relationship("Category", backref=backref("parent", remote_side="Category.id"))
Это так и было. Убрать или что с этим делать?

2023-05-21 12:34 UTC, KonstKorn commented on src/core/db/repository/base.py
> +            .where(str(self._model.deadline) == CURRENT_DATE)
в archive_by_ids - фильтр по deadline ( мне кажется, это логично,  что в архив помещается объект Task, если у него ни только не совпадает id и is_archived == False, но и self._model.deadline == CURRENT_DATE , получается в архив уходит, если истек deadline. Мне показалось в этом  есть логика, но я понял,  что не знаю техзадания и при каких условиях должно уходить в архив. уберу

2023-05-21 12:35 UTC, KonstKorn commented on src/core/db/repository/base.py
> +CURRENT_DATE = datetime.now().strftime(DATE_FORMAT)
понял. уберу

2023-05-21 12:35 UTC, KonstKorn commented on src/core/db/repository/category.py
> +        return categories
это изначально было так написано, я не трогал. поменяю

2023-05-21 12:46 UTC, KonstKorn commented on src/core/db/models.py
> +    title: Mapped[str] = mapped_column(nullable=True)
Миграции проходят, все нормально. убрал

2023-05-21 13:22 UTC, NiKuma0 commented on src/core/db/models.py
> +    children: relationship("Category", backref=backref("parent", remote_side="Category.id"))
Не похоже что это так и было. [Посмотри в документации синтаксис](https://docs.sqlalchemy.org/en/20/orm/basic_relationships.html)
```suggestion
    children = relationship("Category", backref=backref("parent", remote_side="Category.id"))
```
Можно добавить аннотации:
```suggestion
    children: Mapped["Category"] = relationship("Category", backref=backref("parent", remote_side="Category.id"))
```

2023-05-21 13:26 UTC, KonstKorn commented on src/core/db/models.py
> +    children: relationship("Category", backref=backref("parent", remote_side="Category.id"))
точно,  это я исправил. Приношу извинения, я видно увлекся исправлением других полей. Сейчас все сделаю

2023-05-21 13:28 UTC, NiKuma0 commented on src/core/db/models.py
> +    __allow_unmapped__ = True
[Судя по доке ](https://docs.sqlalchemy.org/en/20/changelog/migration_20.html#migration-to-2-0-step-six-add-allow-unmapped-to-explicitly-typed-orm-models), это нам не нужно, а миграции не работают потому что не верно указана аннотация. `children: relationship` - не должно работать. Есть предположение, что `__allow_unmapped__ ` игнорирует аннотацию, поэтому у тебя все работало с этим.

2023-05-21 18:31 UTC, NiKuma0 approved these changes

2023-05-21 20:56 UTC, merged