Изменение сообщения о задании
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #438
Opened 2024-03-27 19:29 UTC by gorskyolga

### Что сделано:

Коммит 1:
Изменен формат сообщения о задании. Для этого:
- исправлена функция display_task, которая используется для формирования текста сообщения о задании; функция также была переименована (ранее называлась display_tasks);
- кнопка "Посмотреть описание" оформлена в функцию get_task_info_keyboard и перенесена в "src\bot\keyboards.py", т.к. все остальные кнопки описываются там.

Коммит 2:
Изменена реакция на кнопку "Посмотреть описание" (сообщение заменено на черновой вариант веб-аппа). Для этого:
- удалены функции display_task_verbosely и task_details_callback и шаблон TASK_DETAILS; использовались для вывода сообщения с подробной информацией о задании, больше нигде не использовались;
- в функции get_task_info_keyboard вывод сообщения заменен на веб-ап со ссылкой на задание;
- добавлена функция get_task_web_app_info (как заглушка для следующей задачи по веб-апп);
- в функции fill_db.py (наполнение БД тестовыми данными) исправлены ссылки для заданий, т.к. возникала ошибка "BadRequest: Inline keyboard button web app url 'http://example.com/task/<...>' is invalid: only https links are allowed".

### Как протестировала:
Проверила локально.
Чтобы протестировать кнопку с веб-апп, нужно в БД поменять ссылку на задание на что-нибудь реальное.

2024-03-29 16:33 UTC, Genek91 commented on src/bot/keyboards.py
> +    keyboard = [[InlineKeyboardButton("ℹ️ Посмотреть описание", web_app=get_task_web_app_info(task))]]
Может быть вынести в константу? Чтобы было удобнее потом работать со всеми кнопками. Или оставить это на итоговый рефакторинг?

2024-03-29 16:42 UTC, ASTimch commented on src/core/utils.py
> +        f"<b>Категория:</b> {task.category.name if task.category is not None else 'Не указана.'}\n\n"
'is not None' вроде как лишнее, можно просто 
{task.category.name if task.category else 'Не указана.'}

2024-03-29 17:15 UTC, eugemos requested changes

2024-03-29 17:15 UTC, eugemos commented on src/bot/keyboards.py
> +    """Кнопка для отображения подробной информации о задании и фонде"""
Это не "Кнопка для ...", а "Клавиатура с кнопкой для ..."

2024-03-29 17:15 UTC, eugemos commented on src/bot/keyboards.py
> +    keyboard = [[InlineKeyboardButton("ℹ️ Посмотреть описание", web_app=get_task_web_app_info(task))]]
А это не константа, она зависит от параметра task.

2024-03-29 17:15 UTC, eugemos commented on src/core/utils.py
> +    bonus_link = f"{url}article/6646"
Это константный URL, значит надо его целиком вынести в settings и получать его оттуда, как зависимость, прямо в эту функцию. А вызывающую функцию от этого освободить.

2024-03-29 17:15 UTC, eugemos commented on src/core/utils.py
> -        f"Бонусы: <a href='{bonus_link}'>{task.bonus * '💎'}</a>\n"
Согласно схеме количество бонусов указывается с помощью множителя, а не путём повторения значка бонуса.

2024-03-29 17:22 UTC, Genek91 commented on src/bot/keyboards.py
> +    keyboard = [[InlineKeyboardButton("ℹ️ Посмотреть описание", web_app=get_task_web_app_info(task))]]
Да точно, так не получится.

2024-03-29 17:42 UTC, Genek91 approved these changes

2024-03-29 18:44 UTC, gorskyolga commented on src/bot/keyboards.py
> +    """Кнопка для отображения подробной информации о задании и фонде"""
Исправила

2024-03-29 19:10 UTC, gorskyolga commented on src/core/utils.py
> +        f"<b>Категория:</b> {task.category.name if task.category is not None else 'Не указана.'}\n\n"
Исправила

2024-03-29 19:14 UTC, gorskyolga commented on src/core/utils.py
> -        f"Бонусы: <a href='{bonus_link}'>{task.bonus * '💎'}</a>\n"
Спасибо! Не подумала, что нужно это так трактовать. Исправляю.

2024-03-30 16:21 UTC, eugemos requested changes

2024-03-30 16:21 UTC, eugemos commented on src/core/utils.py
> +        f"<a href='{bonus_info_url}'><b>Бонусы:</b></a> {str(task.bonus)} * 💎\n\n"
Функция str тут не нужна, внутри { } она применяется автоматически, а вот знак умножения согласно схеме должен быть в виде ×, а не *.

2024-03-30 16:21 UTC, eugemos commented on src/core/utils.py
> +def display_task(task: Task, bonus_info_url: str) -> str:
Давай вот сюда перенесём зависимость, т.е. сделаем `bonus_info_url: str = Provide[Container.settings.provided.procharity_bonus_info_url]`, и избавим сразу две других функции о необходимости знать, что этой функции нужен какой-то URL.

2024-03-30 18:45 UTC, gorskyolga commented on src/core/utils.py
> +def display_task(task: Task, bonus_info_url: str) -> str:
Пробовала вчера так сделать, но приложение не запускалось с ошибкой импорта (ругалось последовательно на всё, что импортировалось из __init__.py в src.core.depends). И я решила не переносить эту зависимость внутрь функции...
Для решения проблемы с импортами вынесла эту функцию в отдельный файл.

2024-03-30 20:27 UTC, eugemos requested changes

2024-03-30 20:27 UTC, eugemos commented on src/bot/constants/messages.py
> +from dependency_injector.wiring import Provide
Очень странное место для этого файла: констант в нём нет и используется он не только ботом, но и API.
Самое место ему в `src.core` рядом с `utils.py`

2024-03-31 06:44 UTC, eugemos approved these changes

2024-03-31 15:03 UTC, merged