no_unset_subscribe
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #455
Opened 2024-04-03 18:55 UTC by Genek91

### Что сделано
Добавлена кнопка и функция `no_unset_mailing` для отмены отписки.
Добавлена функция `menu_send_message` для переиспользования в `menu_callback` и `no_unset_mailing`
### Как проверял
Пробовал разные варианты подписки/отписки/не отписки бота и проверял кнопку `Вернуться в меню`, смотрел изменения в БД.

2024-04-06 10:26 UTC, gorskyolga reviewed
Я не проверяла, но мне кажется, что эту задачу лучше решать, изменяя функцию set_mailing.
Сейчас она с ходу меняет статус подписки, а затем уже выясняет, подписался пользователь или отписался и выясняет причины отписки.
Вот мне кажется, что если это поменять и отписку пользователя перенести в хэндлер, который обрабатывает причины отписок, то можно будет обойтись без доп.функции, которая подписывает пользователя обратно, если он передумал.

2024-04-07 13:44 UTC, Genek91 commented
@gorskyolga 
> Я не проверяла, но мне кажется, что эту задачу лучше решать, изменяя функцию set_mailing. Сейчас она с ходу меняет статус подписки, а затем уже выясняет, подписался пользователь или отписался, и выясняет причины отписки. Вот мне кажется, что если это поменять и отписку пользователя перенести в хэндлер, который обрабатывает причины отписок, то можно будет обойтись без доп.функции, которая подписывает пользователя обратно, если он передумал.

Мне кажется что `set_mailing` как раз и нужен для того чтобы меня статус подписки (на то он и set_mailing), а выясняет причины отписки уже как раз `reason_handler`. И я думал что "причины отписок" и "не отписка" это разные по сути сущности и их нужно было разделить. Сейчас я включил "не отписку" в список причин чтобы не делать доп. функцию, но мне кажется так стало чуть запутанней.

2024-04-07 18:35 UTC, gorskyolga commented
Мы можем переназвать эти две функции, как нам понравится.

2024-04-07 18:38 UTC, gorskyolga commented
Мы можем переназвать эти две функции, как нам понравится.
Идея была в том, чтобы:
- в set_mailing перенести has_mailing = await user_service.set_mailing(telegram_id) внутрь if, если пользователь подписывается, и внутрь reason_handler, если пользователь отписывается;
- сделать, чтобы кнопка NO_UNSET_SUBSCRIBE_BUTTON ("Не отменять подписку"), которую ты добавил на первом коммите, возвращала в меню.

2024-04-07 19:18 UTC, gorskyolga commented
И ещё поменяй, пожалуйста, текст сообщения. Согласно схеме в Миро, он должен быть таким:
![image](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/51045160/90391b65-06e5-47c7-b056-161303c74bbc)
Ссылка там тоже нужна другая: https://procharity.ru/tasks/.

2024-04-07 20:55 UTC, Genek91 commented
> Мы можем переназвать эти две функции, как нам понравится. Идея была в том, чтобы:
> 
> * в set_mailing перенести `has_mailing = await user_service.set_mailing(telegram_id)` внутрь if, если пользователь подписывается, и внутрь reason_handler, если пользователь отписывается;
> * сделать, чтобы кнопка NO_UNSET_SUBSCRIBE_BUTTON ("Не отменять подписку"), которую ты добавил на первом коммите, возвращала в меню, чтобы у неё и кнопок с причинами отписки были разные callback.

Если, я правильно тебя понял, то непосредственно отписка должна происходить в момент выбора причин отписки, а не по нажатию на кнопку отписаться и нам это в принципе не важно (исправил на этот вариант). Сообщение и ссылку тоже поправил.

2024-04-08 13:02 UTC, gorskyolga commented on src/bot/constants/callback_data.py
> +NO_UNSET_SUBSCRIPTION = "no_unset_subscription"
Этот callback теперь не нужен, остался от прошлого коммита.

2024-04-08 13:06 UTC, gorskyolga commented on src/bot/handlers/menu.py
> +    """Выключение подписки пользователя и отправка сообщения с причиной на почту."""
Стоит также поменять название функции с reason_handler на unsubscribe_reason_handler, так будет понятнее, что эта функция делает.

2024-04-08 13:08 UTC, gorskyolga commented on src/bot/keyboards.py
> +        NO_UNSET_SUBSCRIBE_BUTTON,
Мне кажется, не стоит выносить здесь кнопки в отдельные переменные. Сейчас они используются только здесь и вряд ли будут переиспользованы.

2024-04-08 15:38 UTC, gorskyolga commented on src/bot/keyboards.py
> +NO_UNSET_SUBSCRIBE_BUTTON = [InlineKeyboardButton("Не отменять подписку", callback_data=callback_data.MENU)]
Нужно кнопку "Не отменять подписку" выделить среди причин отписки. Конкретных требований заказчика по ней нет. Давай сделаем перед текстом какой-нибудь значок. Можно ▶️ (такой же как при "Подписаться на задания"), можно какую-нибудь стрелку в стиле "вернуться обратно". Как больше самому нравится.

2024-04-08 16:53 UTC, Genek91 commented on src/bot/keyboards.py
> +NO_UNSET_SUBSCRIBE_BUTTON = [InlineKeyboardButton("Не отменять подписку", callback_data=callback_data.MENU)]
Добавил ↩️

2024-04-08 17:32 UTC, eugemos requested changes

2024-04-08 17:32 UTC, eugemos commented on src/settings.py
> +    TASKS_PROCHARITY_URL: Url = "https://procharity.ru/tasks/"
Не нужно добавлять ещё одну переменную окружения. Тут нужно создать свойство. См. примеры в этом файле ниже, например, procharity_faq_volunteer_url

2024-04-08 17:32 UTC, eugemos commented on src/bot/handlers/menu.py
> +    await user_service.set_mailing(telegram_id)
Неплохо бы переименовать эту функцию, ведь она не устанавливает подписку, а инвертирует. `toggle_mailing` ей бы подошло гораздо лучше.

2024-04-08 17:32 UTC, eugemos commented on src/bot/keyboards.py
> +NO_UNSET_SUBSCRIBE_BUTTON = [InlineKeyboardButton("Не отменять подписку", callback_data=callback_data.MENU)]
Неудачное название. Лучше NO_UNSUBSCRIBE_BUTTON или, ещё лучше, DONT_UNSUBSCRIBE_BUTTON.
Хорошо сочетается с UNSUBSCRIBE_BUTTON и короче к тому же.

2024-04-08 17:32 UTC, eugemos commented on src/bot/handlers/menu.py
> +    """Выключение подписки пользователя и отправка сообщения с причиной на почту."""
Ещё лучше `unsubscription_reason_handler`. Не всегда в английском языке одно и то же слово может быть и существительным и глаголом.

2024-04-09 06:44 UTC, eugemos requested changes

2024-04-09 06:44 UTC, eugemos commented on src/core/db/repository/user.py
> +    async def toggle_mailing(self, user: User, has_mailing: bool) -> None:
Тут перестарался. У этой функции было правильное название, ведь она действительно устанавливает заданное значение.

2024-04-09 10:39 UTC, eugemos approved these changes

2024-04-09 13:19 UTC, gorskyolga approved these changes

2024-04-10 21:31 UTC, merged