Fix/filter archived categories
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #456
Opened 2024-04-04 10:04 UTC by ASTimch

Добавлен: 
UserRepository.get_user_unarchived_categories()
Модифицированы (добавлен параметр filter_archived:bool):
UserService.get_user_categories()
UserService.get_user_categories_with_parents()

2024-04-06 10:34 UTC, gorskyolga commented
Для инфо:
Пока не смотрю этот PR, так как в него подтянуты изменения из другой ветки, которые планируется влить в develop (рефакторинг изменения категорий). Соответственно они отображаются в изменениях и смотреть тяжело. Буду смотреть после того, как вмержу ветку с рефакторингом изменения категорий в develop.

2024-04-08 08:46 UTC, gorskyolga commented
Для инфо:
Подтянула изменения из develop в ветку на репозитории, так что нужно будет обновить локальную ветку, если понадобится вносить изменения в неё.

2024-04-08 17:54 UTC, eugemos requested changes

2024-04-08 17:54 UTC, eugemos commented on src/bot/services/user.py
> +    async def get_user_categories(self, telegram_id: int, filter_archived: bool = False) -> dict[int, str]:
`filter_archived`может быть понято неоднозначно - то ли отбросить archived, то ли только их оставить. Как вариант, предлагаю `without_archived`.

2024-04-09 14:54 UTC, ASTimch commented on src/bot/services/user.py
> +    async def get_user_categories(self, telegram_id: int, filter_archived: bool = False) -> dict[int, str]:
Согласен, сам долго думал, как же назвать этот параметр.

2024-04-10 04:54 UTC, eugemos approved these changes

2024-04-10 10:33 UTC, gorskyolga reviewed
Мне кажется, можно не создавать отдельную функцию get_user_unarchived_categories в репозитории, а вместо этого передавать в get_user_categories параметр without_archived и в зависимости от него возвращать категории с / без архивных. То есть перенести эту развилку из сервиса в репозиторий.

Архивация категорий - это способ мягкого удаления категорий. Когда эндпоинт `api/categories` не получает категорию в списке актуальных, она архивируется в БД бота. Ситуации, когда нужно получить категории без архивных, гораздо более вероятные, чем те, когда нужны категории с архивными.
Если искать по коду, где используется get_user_categories и get_user_categories_with_parents, то видно, что сейчас нет мест, где они бы использовались без without_archived=True.

Так что стоит наоборот сделать для without_archived значением по умолчанию True. Или переделать его на with_archived со значением по умолчанию False.

2024-04-10 11:17 UTC, ASTimch commented
> Мне кажется, можно не создавать отдельную функцию get_user_unarchived_categories в репозитории, а вместо этого передавать в get_user_categories параметр without_archived и в зависимости от него возвращать категории с / без архивных. То есть перенести эту развилку из сервиса в репозиторий.
> 
> Архивация категорий - это способ мягкого удаления категорий. Когда эндпоинт `api/categories` не получает категорию в списке актуальных, она архивируется в БД бота. Ситуации, когда нужно получить категории без архивных, гораздо более вероятные, чем те, когда нужны категории с архивными. Если искать по коду, где используется get_user_categories и get_user_categories_with_parents, то видно, что сейчас нет мест, где они бы использовались без without_archived=True.
> 
> Так что стоит наоборот сделать для without_archived значением по умолчанию True. Или переделать его на with_archived со значением по умолчанию False.

Логику фильтрации архивных перенес в get_user_categories(), удалил  get_user_unarchived_categories

2024-04-10 15:09 UTC, gorskyolga approved these changes

2024-04-12 10:31 UTC, AntonZelinsky approved these changes

2024-04-12 12:38 UTC, merged