Убрал кнопку "У меня нет подходящих компетенций".
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #459
Opened 2024-04-05 07:55 UTC by Yohimbe227

Убрал кнопку "У меня нет подходящих компетенций". Исправил в соседних функциях пустой словарь в значениях функции по умолчанию.

2024-04-05 15:07 UTC, gorskyolga requested changes

2024-04-05 15:07 UTC, gorskyolga commented on src/bot/keyboards.py
> +    selected_categories = {} if selected_categories is None else selected_categories
Подскажи, пожалуйста, зачем здесь и в get_checked_categories_keyboard такая замена.

2024-04-05 15:07 UTC, gorskyolga commented on src/bot/keyboards.py
> -            [InlineKeyboardButton("Нет моих компетенций 😕", callback_data=callback_data.ADD_CATEGORIES)],
callback_data.ADD_CATEGORIES используется только этой кнопкой. Нужно его подчистить.

2024-04-05 16:23 UTC, Yohimbe227 commented on src/bot/keyboards.py
> +    selected_categories = {} if selected_categories is None else selected_categories
Использование изменяемых типов данных в качестве значений аргументов по умолчанию в Python может привести к неожиданным побочным эффектам.

def foo(param=[]):
    param.append(1)
    print(param)

foo()  # [1]
foo()  # [1, 1]
foo()  # [1, 1, 1]

2024-04-05 17:27 UTC, gorskyolga commented on src/bot/keyboards.py
> +    selected_categories = {} if selected_categories is None else selected_categories
Поняла, спасибо!

2024-04-05 17:34 UTC, gorskyolga commented on src/bot/keyboards.py
> -            [InlineKeyboardButton("Нет моих компетенций 😕", callback_data=callback_data.ADD_CATEGORIES)],
И еще не заметила сразу.. Раз уж тут теперь одна кнопка добавляется, то можно заменить extend на append.

2024-04-06 13:53 UTC, AntonZelinsky approved these changes

2024-04-06 15:03 UTC, gorskyolga approved these changes

2024-04-06 15:06 UTC, merged