Feature: save user categories to db
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #47
Opened 2023-05-27 10:39 UTC by Legyan

Для сохранения в таблицу users_categories нескольких категорий для одного юзера было необходимо убрать требования уникальности для user_id и category_id по отдельности, добавил для них общий UniqueConstraint.

2023-05-27 10:59 UTC, NiKuma0 requested changes
Нужно чтобы сохранённые категории подгружались перед выбором новых. То есть - если пользователь нажмет кнопку "Изменить компетенции" уже выбранные им категории должны отметится галочкой ✅. По идее должно решатся одной строчкой кода)

2023-05-27 10:59 UTC, NiKuma0 commented on src/bot/handlers.py
> +    telegram_id = update.effective_chat.id
Будет лучше взять id у юзера.

2023-05-27 10:59 UTC, NiKuma0 commented on src/bot/handlers.py
> +    users_categories_ids = list(users_categories.keys()) if users_categories else None
```suggestion
    users_categories_ids = context.user_data.get("selected_categories", {}).keys()
```

2023-05-27 10:59 UTC, NiKuma0 commented on src/bot/handlers.py
> +    if not categories:
Это можно поставить по выше, перед `user_service.sset_categories_to_user`

2023-05-27 10:59 UTC, NiKuma0 commented on src/core/db/models.py
>  users_categories = Table(
Тут было бы хорошо увидеть класс вместо `Table`

2023-05-27 10:59 UTC, NiKuma0 commented on src/core/services/user.py
> +    async def get_user_categories(self, telegram_id: int) -> list[str]:
Думаю можно объединить эти функции - чтобы `set_categories_to_user` возвращала список категорий.

2023-05-27 10:59 UTC, NiKuma0 commented on src/bot/bot.py
> +    bot.add_handler(CallbackQueryHandler(confirm_categories_callback, pattern="confirm_categories"))
Воспользуйся переменой, сохрани ее в `constains/callback_data`. Скоро тут все будет переписано в таком формате.

2023-05-27 11:39 UTC, Legyan commented on src/bot/handlers.py
> +    if not categories:
я проверяю это после присваивание категорий, потому что иначе после удаления пользователем всех своих категорий он получит вывод:
"Отлично! Теперь я буду присылать тебе уведомления о новых заданиях в категориях: "

2023-05-27 11:45 UTC, Legyan commented on src/core/services/user.py
> +    async def get_user_categories(self, telegram_id: int) -> list[str]:
Функция get_user_categories остаётся нужной для получения категорий из базы и добавления в контекст. Тогда может быть лучше оставить всё так, чтобы set_categories_to_user выполняла только одну ожидаемую по названию функции задачу?

2023-05-27 13:51 UTC, Legyan commented on src/bot/handlers.py
> +    telegram_id = update.effective_chat.id
Не понял что имеется ввиду

2023-05-27 13:59 UTC, NiKuma0 commented on src/bot/handlers.py
> +    telegram_id = update.effective_chat.id
```suggestion
    telegram_id = update.effective_user.id
```

2023-05-27 14:29 UTC, NiKuma0 approved these changes
Не большой рефакторинг на sqlalchemy 2.0, а так все хорошо, работает.

2023-05-27 14:29 UTC, NiKuma0 commented on src/core/db/models.py
> +    __abstract__ = True
В новой версии sqlalchemy [это делается иначе](https://docs.sqlalchemy.org/en/20/orm/inheritance.html#abstract-concrete-classes). Нужно наследоваться от `AbstractConcreteBase`

2023-05-27 14:29 UTC, NiKuma0 commented on src/core/db/models.py
> +class EntityBase(Base):
Переименуй в `ContentBase`, и добавь поле `is_archived`

2023-05-27 14:29 UTC, NiKuma0 commented on src/core/db/repository/user.py
> +        ).scalars().first()
```suggestion
        user = await self._session.scalar(
            select(User)
            .options(selectinload(User.categories))
            .where(User.telegram_id == telegram_id)
        )
```

2023-05-27 14:29 UTC, NiKuma0 commented on src/core/db/repository/user.py
> +        ).scalars().all() if categories_ids else []
```suggestion
        categories = await self._session.sclalars(
            select(Category)
            .where(Category.id.in_(categories_ids))
        ) if categories_ids else []
```

2023-05-27 14:29 UTC, NiKuma0 commented on src/core/db/repository/user.py
> +        ).scalars().all()
```suggestion
        return await self._session.scalars(
            select(Category)
            .join(User.categories)
            .where(User.id == user.id)
        )
```

2023-05-27 18:42 UTC, NiKuma0 requested changes

2023-05-27 18:42 UTC, NiKuma0 commented on src/core/db/models.py
> +    """Базовый класс для сущностей."""
```suggestion
    """Базовый класс для контента."""
```

2023-05-27 18:42 UTC, NiKuma0 commented on src/core/db/models.py
> +class ContentBase(AbstractConcreteBase, Base):
Это класс для контента - задачи и категории. У нас для всех моделей если `Base`. Тут должно быть только поля `is_archived`.

2023-05-27 21:08 UTC, Legyan commented on src/core/db/models.py
> +    __abstract__ = True
Два иерархичных абстрактных класса у меня не получилось сделать через AbstractConcreteBase, из за ошибки MRO.

2023-05-28 13:20 UTC, NiKuma0 commented on src/core/db/models.py
> +    __abstract__ = True
Ну это точно не решение - можно через [mixin](https://docs.sqlalchemy.org/en/13/orm/extensions/declarative/mixins.html#mixin-and-custom-base-classes)

2023-05-29 17:33 UTC, Legyan commented on src/core/db/models.py
> +class EntityBase:
Но UsersCategories должен же от чего то наследоваться, чтобы создалась таблица?

2023-05-30 09:25 UTC, AleksandrLyo commented on src/core/db/models.py
> +class EntityBase:
Так хорошо, а что нам мешает наследоваться от Base в его исходном варианте?

2023-05-30 10:15 UTC, NiKuma0 commented on src/core/db/models.py
> +class EntityBase:
Наследуй `UserCategories` от старого варианта `Base` -  поля `create_date` и т.п тут не помешают. 
Наш техлид посоветовал добавить эти поля для каждой модели, так легче отслеживать баги.

2023-05-31 13:54 UTC, AleksandrLyo commented on src/bot/handlers.py
> +        text=f"Спасибо, я передал информацию команде ProCharity!" f"Ответ придет на почту {user_data['email']}",
```suggestion
        text="Спасибо, я передал информацию команде ProCharity!"
        f"Ответ придет на почту {user_data['email']}",

```

2023-06-01 10:05 UTC, AleksandrLyo approved these changes

2023-06-01 10:46 UTC, NiKuma0 approved these changes
Ну вроде все хорошо. Расскажи как тестировал и можешь мержить.

2023-06-01 11:32 UTC, Legyan commented
Как тестировал:
1. Заполнил базу данных категориями и подкатегориями
2. Запустил бота
3. Написал боту /categories, в меню выбрал несколько категорий и нажал "Готово"
4. Проверил что в ответном сообщении в telegram приведены выбранные категории и что в базе данных в таблице users_categories сохранены соответствующие отношения user_id / category_id
5. Перезапустил бота
6. Написал боту /categories, убедился что категории моего пользователя подгрузились в контекст по галочкам рядом с кнопками выбора категорий в меню.
7. Снял все галочки и нажал "Готово"
8. Проверил что в ответном сообщении в telegram нет категорий и что в базе данных в таблице users_categories удалены все отношения с user_id моего пользователя
9. Повторил пункты 3, 4 несколько раз с различным количеством выбранных категорий

2023-06-01 12:32 UTC, merged