endpoint/external_fund_registration
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #476
Opened 2024-04-10 15:03 UTC by Genek91

### Что сделано
Добавлен эндпоинт `api/auth/external_fund_registration`.
Добавлены схемы `ExternalSiteFundRequest` и `BaseExternalSiteUserRequest`.
В `UserRepository` добавлен метод `set_role`, для присвоения пользователю роли.
### Как проверял
Пробовал менять роли через ендпоинты `external_fund_registration` и `external_user_registration`. Проверял изменения в БД.

2024-04-10 19:04 UTC, eugemos requested changes

2024-04-10 19:04 UTC, eugemos commented on src/api/schemas/external_site_user.py
> +        return ExternalSiteUser(
Получилось дублирование кода, надо вынести повторяющийся код в базовый класс.

2024-04-10 19:04 UTC, eugemos commented on src/api/services/external_site_user.py
> +        self, site_user_schema: ExternalSiteUserRequest | ExternalSiteFundRequest, user_role: str
Наверное, можно обойтись без поля `user_role`, просто проверяя тип параметра `site_user_schema`. Сильно это код, конечно, не упростит, но будет защитой от гипотетической ошибки, когда тип `site_user_schema` не соответствует значению  `user_role`.

2024-04-10 19:04 UTC, eugemos commented on src/api/services/external_site_user.py
>          user = await self._user_repository.get_by_user_id(site_user_schema.user_id)
По-моему, эта строка содержит ошибку, так как `user_id` никакого отношения к таблице user, на самом деле, не имеет. Здесь надо просто использовать атрибут user модели ExternalSiteUser.

2024-04-10 19:04 UTC, eugemos commented on src/api/services/external_site_user.py
> +            await self._user_repository.set_role(user, user_role)
Это место изначально содержало ошибку. При обновлении данных для внешнего пользователя у соответствующего ему пользователя обновлялись только категории, а всё остальное нет. Теперь ты добавил обновление роли, а всё остальное так и не обновляется.

2024-04-10 19:04 UTC, eugemos commented on src/api/schemas/external_site_user.py
> +class ExternalSiteUserRequest(BaseExternalSiteUserRequest):
Может, стоит теперь уже использовать слово `Volunteer` в названии (и не только здесь)? URL эндпойнта менять, конечно, не предлагаю.

2024-04-11 10:17 UTC, gorskyolga commented on src/api/services/external_site_user.py
>          user = await self._user_repository.get_by_user_id(site_user_schema.user_id)
Верно, здесь ошибка.
site_user_schema.user_id - это наш будущий external_id из таблицы external_site_users.
Если self._user_repository.get_by_user_id() и найдет пользователя с таким id в таблице users, то это будет совершенно не тот user.

2024-04-11 17:34 UTC, eugemos submitted a review, later dismissed

2024-04-11 17:34 UTC, eugemos commented on src/api/endpoints/external_site_user.py
>  @site_user_router.post("/external_user_registration", description="Актуализирует пользователя с сайта ProCharity.")
В `description` тоже надо пользователя на волонтёра заменить.

2024-04-11 17:34 UTC, eugemos commented on src/api/schemas/external_site_user.py
> +    """Базовый класс модели запроса для ExternalSiteUser."""
Вот беда - чем пристальнее вглядываешься, тем больше несуразностей замечаешь.
В этом файле у нас собраны схемы. Зачем схемы называть моделями? Ведь модели - это другое. Конечно, это не ты придумал, но всё же стоит исправить.

2024-04-11 17:34 UTC, eugemos commented on src/api/schemas/external_site_user.py
> +        to_orm = super().to_orm()
Сомнительная идея - называть локальную переменную так же, как и функцию. К тому же, имя переменной должно быть существительным (user, volunteer и т.д.).

2024-04-11 17:34 UTC, eugemos commented on src/api/services/external_site_user.py
> +                site_user.user.role = UserRoles.VOLUNTEER
Значение `role` можно получить из `site_user`, и тип проверять не нужно будет.

2024-04-11 17:34 UTC, eugemos commented on src/api/services/external_site_user.py
> +                site_user.user.role = UserRoles.FUND
Для надёжности категории у фонда надо обнулить на тот случай, если это раньше волонтёр был. Ведь по условиям задачи такой вариант предусматривается.

2024-04-11 17:41 UTC, eugemos requested changes
Всё написал в комментариях выше.

2024-04-12 13:09 UTC, eugemos requested changes

2024-04-12 13:09 UTC, eugemos commented on src/api/services/external_site_user.py
> +        if site_user.user:
Вместо того, чтобы много раз писать `site_user.user`, не лучше ли ввести переменную `user = site_user.user`?

2024-04-12 13:09 UTC, eugemos commented on src/api/services/external_site_user.py
> +                site_user.user.role = UserRoles.VOLUNTEER
Эту строку и строку 38 можно заменить одной строкой вне условного оператора.

2024-04-12 13:09 UTC, eugemos commented on src/core/db/repository/user.py
> +    async def delete_all_categorys_from_user(self, user: User) -> None:
Правильно categories

2024-04-12 13:09 UTC, eugemos commented on src/core/db/repository/user.py
> +        """Удаляет все категорию у пользователя."""
И тут опечатка: категорию.

2024-04-12 13:09 UTC, eugemos commented on src/api/services/external_site_user.py
> +                site_user.specializations = None
Это лишнее. Ведь, если к API обратились через эндпойнт фонда, то специализации у `site_user` должны уже обнулиться в строке 25. К тому же, ты это только в памяти меняешь, а в БД не сохраняешь потом.

2024-04-12 14:48 UTC, Genek91 commented on src/api/services/external_site_user.py
> +                site_user.specializations = None
Перепроверил, изменения в БД сохраняются при таком варианте, но вот в схеме для фондов не было specializations. Поправил.

2024-04-12 18:13 UTC, eugemos requested changes

2024-04-12 18:13 UTC, eugemos commented on src/api/services/external_site_user.py
> +        user = site_user.user
В этом месте `site_user` может быть `None` и обращение к атрибуту вызовет исключение. Это нужно делать ниже, после того, как `site_user` создан или обновлён.

2024-04-12 18:13 UTC, eugemos commented on src/api/services/external_site_user.py
> +                await self._user_repository.set_categories_to_user(user.id, site_user_schema.specializations)
А вот интересно, что будет если у волонтёра не будет задано категорий при обновлении? Как в этом случае отработает `set_categories_to_user()`, обнулит ли категории?
Проверь на всякий случай. Возможно, для правильной работы в этом случае ей нужно передавать `[ ]` вместо  `None`, или нужно её подкорректировать.
И, кстати, если `set_categories_to_user()` способна обнулять категории у пользователя, тогда `delete_all_categories_from_user` не нужна.

2024-04-13 15:01 UTC, Genek91 commented on src/api/services/external_site_user.py
> +                await self._user_repository.set_categories_to_user(user.id, site_user_schema.specializations)
Немного поправил `set_categories_to_user()`, теперь если `categories_ids = None`, то все категории сбрасываются. Если в запросе не передавать `"specializations"`, то категории так же сбросятся.
Но если передать `"specializations": [ ]`, то создастся пустой список, стоит добавить проверку на этот случай?

2024-04-13 19:48 UTC, eugemos requested changes

2024-04-13 19:48 UTC, eugemos commented on src/core/db/repository/user.py
>              await logger.ainfo("Изменены категории у пользователя")
Нехорошо получилось с сообщением - раньше оно выводилось строго после успешного выполнения операции, а теперь посередине. А вдруг exception? Тогда категории не будут изменены и сообщение получится ложным.
Думаю, его надо выводить после блока `with`. И `return` делать внутри этого блока тогда нельзя.
Кстати, при использовании `with session.begin():` явный вызов `commit()` не нужен, он и так вызывается при выходе из блока `with`.

2024-04-13 19:48 UTC, eugemos commented on src/api/services/external_site_user.py
> +                await self._user_repository.set_categories_to_user(user.id, site_user_schema.specializations)
Непонятно, почему вдруг создастся пустой список. Ведь оператор `if categories_ids:`, который ты написал, одинаково обходит оба случая: и `None` и `[ ]`. Ты проверял это?

2024-04-13 19:48 UTC, eugemos commented on src/api/services/external_site_user.py
> +            user = site_user.user
Надо вынести это перед условным оператором, тогда можно будет написать `if user:`.

2024-04-13 19:48 UTC, eugemos commented on src/api/services/external_site_user.py
> +            if site_user.role == UserRoles.VOLUNTEER:
1. Условный оператор здесь не нужен. Ведь для фонда `specializations` и так равно `None`. Только его значение нужно брать из `site_user`, а не из `site_user_schema`, в котором его может не быть.
2. Давай изменение категорий у пользователя поставим после обновления самого пользователя (в самый конец то есть), а то телега впереди лошади получилась.

2024-04-13 20:23 UTC, Genek91 commented on src/api/services/external_site_user.py
> +                await self._user_repository.set_categories_to_user(user.id, site_user_schema.specializations)
`if categories_ids:` - это условие у внутреннего пользователя и тут всё нормально, а вот у внешнего пользователя через схему попадает `[ ]`. Вот я и подумал может валидатор какой нужен?

2024-04-14 08:08 UTC, eugemos commented on src/api/services/external_site_user.py
> +                await self._user_repository.set_categories_to_user(user.id, site_user_schema.specializations)
Теперь понял. Я думаю, `[ ]` у внешнего пользователя нам не страшен. По смыслу это эквивалентно `None`, и именно так мы его и обрабатываем в дальнейшем. Так что, нет смысла тратиться на валидацию.

2024-04-14 09:12 UTC, eugemos requested changes

2024-04-14 09:12 UTC, eugemos commented on src/core/db/repository/user.py
> -        return user_categories.all()
Получается, теперь эта функция всегда возвращает `None`. К счастью,  возвращаемое ею значение нигде не используется, так что можно так и оставить. Но надо поправить аннотацию .

2024-04-14 09:12 UTC, eugemos commented on src/core/db/repository/user.py
>              await logger.ainfo("Изменены категории у пользователя")
Этот оператор должен исполняться только после того, как изменения попадут в БД, а значит он должен быть после блока `with`, а не в его конце.

2024-04-14 18:07 UTC, eugemos approved these changes

2024-04-15 10:12 UTC, gorskyolga commented on src/api/services/external_site_user.py
> +        user = site_user.user
Сейчас вмержила в develop фичу по авторизации пользователя. В ней Евгений создал get_by_external_id в UserRepository, поскольку получение user как ext_site_user.user приводило к багу.
Давай здесь тоже исправим на `user = await self._user_repository.get_by_external_id(site_user.id)`.

2024-04-15 13:50 UTC, gorskyolga commented on src/api/schemas/external_site_user.py
> +class BaseExternalSiteUserRequest(RequestBase):
Поменяй еще, пожалуйста, в этом классе тип поля email со str на EmailStr из pydantic.

2024-04-15 16:46 UTC, gorskyolga approved these changes

2024-04-16 09:41 UTC, merged