Feature/include pyngrok
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #49
Opened 2023-05-28 20:57 UTC by Andrey-Kugubaev

add pyngrok

2023-05-29 12:57 UTC, NiKuma0 requested changes

2023-05-29 12:57 UTC, NiKuma0 commented on requirements.txt
> +pyngrok==6.0.0 ; python_version >= "3.11" and python_version < "4.0"
Оставь как было. Это не нужно в продакшене.

2023-05-29 12:57 UTC, NiKuma0 commented on src/application.py
> +if settings.USE_NGROK:
Это очень плохо выносить какую либо логику в глобал. Она будет запускается каждый раз как импортируется этот модуль. 

Оберни настройку ngrok в отдельную функцию, и запускай ее в on_startup

2023-05-29 12:57 UTC, NiKuma0 commented on src/application.py
> +    logger.info("ngrok tunnel \"{}\" -> \"http://127.0.0.1:{}\"".format(public_url, port))
Мы используем structlog

2023-05-29 12:57 UTC, NiKuma0 commented on src/settings.py
> +def init_webhooks(base_url):
Это зачем?

2023-05-29 12:57 UTC, NiKuma0 commented on .env.example
> +BASE_URL=http://localhost:8000 # Базовый урл для pyngrok
Кажется это не нужная надстройка. У нас в любом случае будет `localhost`

2023-06-01 11:01 UTC, NiKuma0 requested changes

2023-06-01 11:01 UTC, NiKuma0 commented on src/core/services/set_ngrok.py
Сам файл в очень странном месте. В папке `services` - (от business services - это пошло еще с java) хранится бизнес логика, никак не инициализация приложения. Можно его запихнуть в core/utils.py к примеру.

2023-06-01 17:10 UTC, NiKuma0 approved these changes
Так уже лучше! Понажимай на "Resolve Conversation" и расскажи как тестировал.

2023-06-01 17:10 UTC, NiKuma0 commented on pyproject.toml
> +pyngrok = "^6.0.0"
Это должно быть в dev dependencies `poetry add -G dev pyngrok`
Перемести эти строки ниже

2023-06-01 17:10 UTC, NiKuma0 commented on src/core/utils.py
> +    public_url = ngrok.connect(port).public_url
```suggestion
    settings.APPLICATION_URL = ngrok.connect(port).public_url
```

2023-06-01 20:03 UTC, Andrey-Kugubaev commented
Проверял работу ngrok так:
1. При запуске проекта инициализация ngrok без ошибок
2. Проект запускается, работает. Бот реагирует на "/start"
3. Установил себе ngrok на компе. Запустил при работающем проекте
4. Получил url ngrok, при обращении к этому урлу, получаем все то же, что и при обращении к локалхосту.

2023-06-02 13:51 UTC, NiKuma0 commented on pyproject.toml
>  pre-commit = "^3.3.2"
`pre-commit` тоже, это исключительно для разработки

2023-06-04 08:34 UTC, NiKuma0 approved these changes

2023-06-04 08:34 UTC, NiKuma0 commented on pyproject.toml
>  pre-commit = "^3.3.2"
Перемести pre-commit, и можешь мержить.

2023-06-06 11:30 UTC, merged