Feature/endpoints_users
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #497
Opened 2024-04-20 14:59 UTC by Genek91

### Что сделано
Добавлено два новых эндпоинта `/api/users` и `/api/users/{user_id}`.
В `api/service/users` добавлен сервис `UserService` для работы с моделью User.
В `UserRepository` добавлен новый метод `get_users_by_page` для получения limit-выборки всех пользователей.
Добавлена схема `UserResponse`, поле `created_at` из модели заменяется на `date_registration`.
### Как проверял
Проверил: работоспособность ручек и результаты ответа в Thunder Client, возможность ограничения выборки и пагинацию, при отсутствии данных выводится `[ ]` и `null` соответственно.

2024-04-24 21:20 UTC, gorskyolga commented on src/api/services/users.py
> +class UserService(ContentService):
Лучше не наследоваться от ContentService. Он специфический, для заданий и категорий. Тем более что оба его метода нигде пока не используются.

2024-04-24 21:20 UTC, gorskyolga commented on src/api/schemas/users.py
> +class UserResponse(ResponseBase):
Судя по [схеме первой версии проекта](https://github.com/ProCharity/ProCharity_bot/blob/develop/app/formatter.py), нужно еще добавить поле external_id.

2024-04-24 21:20 UTC, gorskyolga commented on src/api/endpoints/users.py
> +    "/{user_id}",
Нужно переделать на {telegram_id}.
Как этот эндпоинт был реализован в первой версии проекта можно посмотреть [тут](https://github.com/ProCharity/ProCharity_bot/blob/develop/app/front/users.py#L91).

2024-04-24 21:20 UTC, gorskyolga commented on src/api/endpoints/users.py
> +    response_model=list[UserResponse],
Чтобы админка работала, response_model должна быть как [тут](https://github.com/ProCharity/ProCharity_bot/blob/develop/app/front/swagger_schemas.py).

2024-04-24 21:20 UTC, gorskyolga commented on src/api/endpoints/users.py
> +    return await user_service.get_users_by_page(page, limit)
Пагинацию нужно сделать, как [здесь](https://github.com/ProCharity/ProCharity_bot/blob/develop/app/front/users.py#L55)).

Нашла, что есть библиотека [fastapi-pagination](https://uriyyo-fastapi-pagination.netlify.app/). Может получится её использовать.

2024-04-25 08:20 UTC, gorskyolga commented on src/api/endpoints/users.py
> +    response_model=list[UserResponse],
Поправка:
В схеме ошибка. Нашла, что там не хватает одно поля current_page.
[Здесь](https://github.com/ProCharity/ProCharity_bot/blob/develop/app/front/users.py#L72) его добавляют, а [здесь](https://github.com/ProCharity/procharity-front/blob/main/src/pages/Dashboard/Dashboard.tsx#L90) он используется.

2024-04-30 11:30 UTC, gorskyolga commented on src/api/endpoints/users.py
> +    response_model=list[UserResponse],
Тут я погорячилась, USERS_SCHEMA - это не response_model, это пример для документации. Распишу в ревью, как надо изменить.

2024-04-30 11:37 UTC, gorskyolga commented
Для тестирования работы нужно развренуть локально фронт админки:
1. Склонировать репозиторий https://github.com/ProCharity/procharity-front
2. Следовать инструкции в README.md.
Единственное различие, которое я сделала, касалось пункта 3. Вместо команды `yarn set version latest` я использовала `yarn set version 3.0.0`.
3. Добавить файл .env с REACT_APP_API_URL=http://localhost:8000
4. В репозитории с ботом установить для ROOT_PATH значение "/api/v1".

2024-04-30 15:21 UTC, gorskyolga commented on src/api/utils.py
> +    return {"200": {"description": "ok", "examples": {"RESULT": pagination_data}}}
Чтобы фронт отображал пользователей, нужно поменять на `return pagination_data`.
Я погорячилась, предложив замену на USERS_SCHEMA из старого проекта. Там это был пример для документации.

2024-04-30 15:21 UTC, gorskyolga commented on src/api/endpoints/users.py
> +    response_model=dict,
Лучше сделать класс UsersPaginateResponce.

2024-04-30 15:21 UTC, gorskyolga commented on src/api/services/users.py
> +        count_users = await self._user_repository.get_count_all_users()
UserRepository наследуется от AbstractRepository, в котором есть функция count_all. Лучше использовать её.

2024-04-30 15:21 UTC, gorskyolga commented on src/api/services/users.py
> +        return users_paginate_responce(pagination_data)
Пагинацию лучше сразу вынести в отдельную функцию. Пагинация точно понадобится для отображения истории сообщений в админке бота. И возможно захотят добавить актуальные задания, список админов, историю действий админов и что-нибудь еще, тогда она и там понадобится.

2024-04-30 15:21 UTC, gorskyolga commented on src/core/db/repository/user.py
> +    async def get_users_by_page(self, limit: int = 20, offset: int = 0) -> Sequence[User]:
Лучше переделать в get_objects_by_page в AbstractRepository.
И хорошо будет добавить сортировку. Чтобы метод принимал имя столбца, по которому нужно сортировать, и направление сортировки.
В AbstractRepository есть get_statistics_by_days, который тоже принимает имя столбца. Можно посмотреть, как это там сделано.
В первой версии бота сортировка пользователей была по дате регистрации в порядке убывания.

2024-04-30 19:24 UTC, gorskyolga commented on src/core/db/repository/user.py
> +    async def get_users_by_page(self, limit: int = 20, offset: int = 0) -> Sequence[User]:
Лучше пока сделать одинаковую сортировку по created_at в порядке убывания, т.к. всё, что позже будет с помощью пагинации отображаться, скорее всего будет также сортироваться. Если будет необходимо, то потом добавим настраиваемую сортировку.

2024-05-05 17:20 UTC, gorskyolga commented
Добавила "/" к эндпоинту users, т.к. без него при попытке открыть в админке страницу "Пользователи" возникала ошибка "mixed content" и выбрасывало из админки. Когда будет доступ к репозиторию фронта, уберем там и здесь.

2024-05-05 20:02 UTC, eugemos requested changes

2024-05-05 20:02 UTC, eugemos commented on src/api/services/users.py
> +class UserService:
В `bot` имеется аналогичный сервис. Надо эти два сервиса сделать братьями и метод `get_by_telegram_id` вынести в базовый класс.

2024-05-05 20:02 UTC, eugemos commented on src/api/services/users.py
> +        self._session: AsyncSession = session
Не видно, чтобы этот атрибут где-либо использовался.

2024-05-05 20:02 UTC, eugemos commented on src/api/pagination.py
> +    next_page = page + 1 if page != pages else None
Здесь я бы предпочёл параноидальный подход и записал бы условие, как `page < pages`, а в следующей строке, соответственно, как `page > 1`.
Это, конечно, будет работать, если учесть замечание к предыдущей строке.

2024-05-05 20:02 UTC, eugemos commented on src/api/pagination.py
> +    pagination_data = {
Лишняя переменная. Можно ведь просто словарь в return поместить.

2024-05-05 20:02 UTC, eugemos commented on src/api/pagination.py
> +    pages = math.ceil(count_objects / limit) if count_objects else None
Следующая строка не учитывает того, что в этой строке `pages` может быть установлен в `None`. Я бы не преобразовывал здесь нуль в `None`. Это можно сделать в самом конце, если это так уж необходимо.

2024-05-05 20:02 UTC, eugemos commented on src/api/services/users.py
> +        count_users = await self._user_repository.count_all()
Очень некрасиво получилось, что этот сервис занимается навешиванием рюшечек на пагинированные данные. Ведь, если мы будем выводить в админку с пагинацией не только пользователей, но и другие сущности, тогда у нас появятся аналогичные методы вида `get_xxx_by_page`. И что же, там повторять эту логику? Надо её куда-то вынести.

2024-05-05 20:02 UTC, eugemos commented on src/api/services/users.py
> +        return paginate(result, count_users, page, limit, settings.users_url)
Можно попробовать избежать введения новой переменной в `settings`, если использовать механизм реверса. В Starlett, на котором основан FastAPI, для этого есть функция `url_for` (https://www.starlette.io/routing/#reverse-url-lookups), которая теоретически должна быть доступна в FastAPI (а может и своя есть, надо поискать). Но, может быть, лучше это делать в отдельной задаче, так как успех не гарантирован (@gorskyolga). Это особенно будет полезно, если у нас будет пагинированный вывод и для других объектов.

2024-05-05 20:02 UTC, eugemos commented on src/api/utils.py
> +def user_formatter(user: User) -> dict:
Неудачное название для функции. Надо использовать глагол.

2024-05-05 20:02 UTC, eugemos commented on src/api/schemas/users.py
> +class UsersPaginateResponce(ResponseBase):
Тут орфографическая ошибка - правильно `Response`, да и `Paginate` тут не к месту, ведь это глагол. Правильнее будет `UsersPaginatedResponse`.

2024-05-05 20:02 UTC, eugemos commented on src/api/schemas/users.py
> +    result: list[dict] | None
А не лучше ли использовать list[UserResponse]?

2024-05-06 10:12 UTC, gorskyolga commented on src/api/services/users.py
> +        return paginate(result, count_users, page, limit, settings.users_url)
Да, это лучше делать отдельной задачей.

2024-05-07 14:31 UTC, Genek91 commented on src/api/services/users.py
> +        count_users = await self._user_repository.count_all()
Перенёс в paginate, но не уверен что правильно всё сделал.

2024-05-07 18:09 UTC, eugemos requested changes

2024-05-07 18:09 UTC, eugemos commented on src/bot/services/user.py
>          self._user_repository = user_repository
Вместо этого должен быть вызов `__init__` из базового класса.

2024-05-07 18:09 UTC, eugemos commented on src/core/services/users.py
> +        session: AsyncSession,
Это лишнее. Нигде ведь не используется.

2024-05-07 18:09 UTC, eugemos commented on src/api/services/users.py
> +        session: AsyncSession,
Это не используется.

2024-05-07 18:09 UTC, eugemos commented on src/api/services/users.py
> +        self._user_repository: UserRepository = user_repository
Вместо этого должен быть вызов `__init__` из базового класса.

2024-05-07 18:09 UTC, eugemos commented on src/core/db/repository/base.py
> +        """Получает limit-выборку из базы данных отфильтрованную по полю column_name."""
Какой-то странный докстринг. Что такое limit-выборка, и почему она отфильтрована, хотя тут вроде сортировка выполняется?
Метод, вроде, возвращает данные, расположенные на странице `page` с размером `limit`. Что-то такое и в докстринге должно быть.

2024-05-07 18:09 UTC, eugemos commented on src/api/services/users.py
> +        return await paginate(self._user_repository, page, limit, settings.users_url, format_user)
Так дублирования кода в будущем мы, конечно, избежим, но вот выполнение этим сервисом не присущих ему функций останется. Он по-прежнему занимается внешним представлением данных, хотя должен только лишь предоставлять их. 
У тебя сейчас такая последовательность слоёв: эндпойнт - сервис - пагинация, а надо сделать: эндпойнт - пагинация - сервис. Причём, пагинацию желательно реализовать не в виде функции, а в виде класса с методами `paginate` (публичный) и `format_objects` (приватный).
Скажу больше, надо сделать базовый класс пагинатора только лишь с методом `paginate`, а вот `format_objects` реализовывать в его наследниках для конкретных типов данных, для которых они будут предназначены (в твоём случае - для пользователей, например, `class UserPaginator(BasePaginator)` ).

2024-05-07 18:09 UTC, eugemos commented on src/api/pagination.py
> +        "pages": pages,
Вот здесь надо было преобразовать нуль в  `None`.
Забыл или это не требуется?

2024-05-07 19:41 UTC, Genek91 commented on src/api/pagination.py
> +        "pages": pages,
Можно не преобразовывать

2024-05-08 13:36 UTC, Genek91 commented on src/api/services/users.py
> +        return await paginate(self._user_repository, page, limit, settings.users_url, format_user)
@eugemos 
Я правильно понимаю, что в эндпоинтах подключать пагинацию, в таком варианте, нужно будет через dependency_injector?

2024-05-08 15:54 UTC, eugemos commented on src/api/services/users.py
> +        return await paginate(self._user_repository, page, limit, settings.users_url, format_user)
Давай для начала обойдёмся без этого, чтобы не перемудрить. Сначала саму схему реализуем, а потом применение dependency_injector рассмотрим. Работать и без него должно.
Кстати, если со схемой "эндпойнт - пагинация - сервис" возникнут сложности, то можно чуть по-другому сделать: эндпойнт получает данные у сервиса и передаёт их в пагинатор, а результат отправляет. Возможно, такой вариант даже лучше (точно проще, так как позволяет пагинатору ничего не знать про сервис).

2024-05-09 13:25 UTC, Genek91 commented on src/api/services/users.py
> +        return await paginate(self._user_repository, page, limit, settings.users_url, format_user)
В итоге не удержался и добавил DI (наверное будет лишний код дублироваться, хотя если не использовать его, то в эндпоинтах нужно будет создавать объект класса `XxxPaginate` и тоже будет дублирование или я не так понял).
Убрал `format_objects`, в нём вроде нет необходимости, так как используется схема `UserResponse` для вывода нужных данных.

2024-05-10 07:56 UTC, eugemos requested changes

2024-05-10 07:56 UTC, eugemos commented on src/api/schemas/users.py
> +    telegram_id: int = Field(...)
Просто `Field(...)` ничего не добавляет, без него будет тоже самое. Лучше убрать, как избыточный код.

2024-05-10 07:56 UTC, eugemos commented on src/api/pagination.py
> +        self.repository = user_repository
Вместо этого должен быть вызов `__init__` из базового класса.

2024-05-10 07:56 UTC, eugemos commented on src/api/pagination.py
> +    def __init__(self, user_repository: UserRepository) -> None:
Не стоит ли `user_repository` сделать зависимостью, как это в сервисах делается? Хотя бы для однообразия.

2024-05-10 07:56 UTC, eugemos commented on src/api/pagination.py
> +class UserPaginator(BasePaginator):
Не стоит ли конкретизировать обобщённый класс `BasePaginator` для большей строгости?

2024-05-10 07:56 UTC, eugemos commented on src/core/pagination.py
> +        repository: AbstractRepository,
Обобщённый класс `AbstractRepository ` стоит конкретизировать для большей строгости.

2024-05-10 07:56 UTC, eugemos commented on src/core/pagination.py
> +import math
Не стоит ли этот файл переместить в `api`, ведь пагинация только там используется?

2024-05-10 07:56 UTC, eugemos commented on src/api/services/users.py
> +        return await paginate(self._user_repository, page, limit, settings.users_url, format_user)
Неплохо, кстати, получилось.

2024-05-11 12:32 UTC, Genek91 commented on src/api/pagination.py
> +    def __init__(self, user_repository: UserRepository) -> None:
В `src\core\depends\pagination.py` для `UserPaginator` создаётся зависимость с `user_repository` или я не так понял?

2024-05-11 19:06 UTC, eugemos approved these changes

2024-05-11 19:06 UTC, eugemos commented on src/api/pagination.py
> +    def __init__(self, user_repository: UserRepository) -> None:
Да, действительно, всё у тебя так, как в сервисах, собственно и сделано.
Чего-то я загнался. Понять и простить.

2024-05-14 08:53 UTC, gorskyolga commented on src/api/schemas/users.py
> +class UserResponse(ResponseBase):
Для истории:
поле external_id было добавлено по аналогии с первой версией проекта, а потом во время изменений удалено. Так как фронт админки его не использует, то пока нет смысла его добавлять.

2024-05-14 09:41 UTC, gorskyolga commented on src/settings.py
> +        return urljoin(self.ROOT_PATH + "/", "users")
Посмотри ради интереса обсуждение в [этом PR](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/pull/514), если еще не смотрел. Там тоже про urljoin и последний слэш.
Менять ничего не нужно. После мержа этой ветки я в том PR это отрефакторю.

2024-05-14 10:12 UTC, gorskyolga commented on src/core/depends/__init__.py
> +    "PaginateContainer",
Кажется, нужно еще выше добавить импорт `from .pagination import PaginateContainer`.

2024-05-14 14:29 UTC, gorskyolga approved these changes

2024-05-14 14:38 UTC, gorskyolga commented
По-моему, круто получилось!

2024-05-14 14:38 UTC, merged

2024-05-14 16:28 UTC, Genek91 commented
@gorskyolga @eugemos 
Спасибо за ревью.