Feat/send bot status 495
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #506
Opened 2024-04-25 16:45 UTC by ASTimch

Добавлена отправка bot_status на сервер при изменении параметра User.has_mailing или User.banned

Как проверял:
Вручную изменяя отписку/подписку, и блокируя/снова присоединившись к боту наблюдал сообщение статусом 401 в логах.

2024-04-26 09:31 UTC, gorskyolga commented on src/core/services/procharity_api.py
> +        try:
Блок try-except сильно пересекается с таким же блоком в send_user_categories. Он же будет использоваться при передаче данных на внешний api о нажатии кнопки "Откликнуться" и возможно еще чего-нибудь при расширении функционала бота.
Нужно его вынести в отдельную функцию, которая будет принимать url, body и переменную для "режима" работы функции, чтобы она понимала, какие тексты использовать при логировании. Соответственно тексты для логирования вынести в словарь и получать по названию режима.

Либо унифицировать тексты для логирования так, чтобы в функцию с try-except передавать часть текста и использовать в f-строках:
f"Ошибка передачи данных из бота: {"статус бота"} пользователя {user_id}: status = {response.status}"
f"Ошибка передачи данных из бота: {"категории"} пользователя {user_id}: status = {response.status}"
f"Успешная передача данных из бота: {"статус бота"} пользователя {user_id}. Ответ: {data}"
f"Успешная передача данных из бота: {"категории"} пользователя {user_id}. Ответ: {data}"

2024-04-26 10:34 UTC, ASTimch commented on src/core/services/procharity_api.py
> +        try:
> Блок try-except сильно пересекается с таким же блоком в send_user_categories. Он же будет использоваться при передаче данных на внешний api о нажатии кнопки "Откликнуться" и возможно еще чего-нибудь при расширении функционала бота. Нужно его вынести в отдельную функцию, которая будет принимать url, body и переменную для "режима" работы функции, чтобы она понимала, какие тексты использовать при логировании. Соответственно тексты для логирования вынести в словарь и получать по названию режима.
> 
> Либо унифицировать тексты для логирования так, чтобы в функцию с try-except передавать часть текста и использовать в f-строках: f"Ошибка передачи данных из бота: {"статус бота"} пользователя {user_id}: status = {response.status}" f"Ошибка передачи данных из бота: {"категории"} пользователя {user_id}: status = {response.status}" f"Успешная передача данных из бота: {"статус бота"} пользователя {user_id}. Ответ: {data}" f"Успешная передача данных из бота: {"категории"} пользователя {user_id}. Ответ: {data}"

Выполнил отправку и логирование отдельной функцией.
Заводить отдельный словарь, который будет использоваться единожды пока не вижу необходимости (может быть потом после расширения апи)

2024-05-06 11:45 UTC, gorskyolga requested changes

2024-05-06 11:45 UTC, gorskyolga commented on src/core/services/procharity_api.py
> +            await self.send_bot_status(
Есть ли польза от вынесения всей логики в доп.функцию send_bot_status?

2024-05-06 11:45 UTC, gorskyolga commented on src/core/services/procharity_api.py
> +        status = "on" if has_mailing and not banned else "off"
Для фондов такое условие порождает ошибку.
has_mailing - это включение / отключение рассылки новых заданий. У фондов значение has_mailing всегда False. Возможно что-то будет меняться при расширении функционал бота для фондов, но пока так. Получается, если фонд заблокирует и разблокирует бота, его статус останется "off".

2024-05-06 11:51 UTC, ASTimch commented on src/core/services/procharity_api.py
> +        status = "on" if has_mailing and not banned else "off"
Правильно ли я понял, что для фондов условие такое:
status = "on" if not banned else "off"
а для волонтеров такое:
status = "on" if has_mailing and not banned else "off"

2024-05-06 11:52 UTC, ASTimch commented on src/core/services/procharity_api.py
> +        status = "on" if has_mailing and not banned else "off"
> Для фондов такое условие порождает ошибку. has_mailing - это включение / отключение рассылки новых заданий. У фондов значение has_mailing всегда False. Возможно что-то будет меняться при расширении функционал бота для фондов, но пока так. Получается, если фонд заблокирует и разблокирует бота, его статус останется "off".

Правильно ли я понял, что для фондов условие такое:
status = "on" if not banned else "off"
а для волонтеров такое:
status = "on" if has_mailing and not banned else "off"

2024-05-06 13:51 UTC, gorskyolga commented on src/core/services/procharity_api.py
> +        status = "on" if has_mailing and not banned else "off"
Да, правильно.

2024-05-06 13:55 UTC, gorskyolga commented on src/core/services/procharity_api.py
> +        status = "on" if has_mailing and not banned else "off"
Или можно так:
status = "off" if banned or (is_volunteer and not has_mailing) else "on"

2024-05-12 09:59 UTC, gorskyolga commented
Меня смущает, что в `await procharity_api.send_user_bot_status(user)` по-разному передается user.

Здесь мы получаем объект user, отдельной функцией меняем у него поле (has_mailing или banned) и вызываем procharity_api.send_user_bot_status для user (без присваивания измененного поля объекту user):
- src/bot/handlers/categories.py;
- src/bot/handlers/registration.py (строки 66 и 70).

А здесь получаем объект user, отдельной функцией меняем у него поле (has_mailing), присваиваем измененное поле объекту user и вызываем procharity_api.send_user_bot_status для user:
- src/bot/handlers/menu.py (строки 67 и 115).

Судя по тестам, разницы в работе никакой. Но мне кажется, что принцип вызова должен быть одинаков.
Вариант с присваиванием user.has_mailing в `src/bot/handlers/menu.py` мне не очень нравится. По двум причинам:
- если для user.banned всё работает без присваивания, тогда зачем нужно присваивать user.has_mailing какое-то значение;
- если присваивание нужно, то оно ведь должно происходить на уровне репозитория, а не сервиса.

2024-05-12 10:27 UTC, ASTimch commented
> Меня смущает, что в `await procharity_api.send_user_bot_status(user)` по-разному передается user.
> 
> Здесь мы получаем объект user, отдельной функцией меняем у него поле (has_mailing или banned) и вызываем procharity_api.send_user_bot_status для user (без присваивания измененного поля объекту user):
> 
> * src/bot/handlers/categories.py;
> * src/bot/handlers/registration.py (строки 66 и 70).
> 
> А здесь получаем объект user, отдельной функцией меняем у него поле (has_mailing), присваиваем измененное поле объекту user и вызываем procharity_api.send_user_bot_status для user:
> 
> * src/bot/handlers/menu.py (строки 67 и 115).
> 
> Судя по тестам, разницы в работе никакой. Но мне кажется, что принцип вызова должен быть одинаков. Вариант с присваиванием user.has_mailing в `src/bot/handlers/menu.py` мне не очень нравится. По двум причинам:
> 
> * если для user.banned всё работает без присваивания, тогда зачем нужно присваивать user.has_mailing какое-то значение;
> * если присваивание нужно, то оно ведь должно происходить на уровне репозитория, а не сервиса.

1. Данные расхождения не относятся к функции отправки статуса бота , т.е. не относятся к данной задаче. Если есть желание что-то рефакторить, то целесобразно для этого сделать отдельную задачу.
2. Касаемо расхождений:
- сами сервисы user_service.bot_banned(user), user_service.bot_unbanned(user) реализованы таким образом, что они обновляют значение поля user.banned при выполнении и ничего не возвращают (поэтому тут никакого присваивания и не требуется)
- сервис user_service.toggle_mailing(telegram_id) меняет значение в базе, причем предварительно повторно вычитывает пользователя из базы. 
Если есть желание унифицировать, то имеет смысл переписать сервис в виде user_service.toggle_mailing(user) и в нем менять соответствующее поле user.has_mailing.
Опять же, в моем понимании, это следует оформить отдельной задачей.

2024-05-12 11:25 UTC, gorskyolga commented on src/bot/handlers/menu.py
> +    user.has_mailing = await user_service.toggle_mailing(telegram_id)
Получается, ты здесь добавил присваивание результата user.has_mailing для перестраховки?
Если убрать присваивание и распечатывать значение user.has_mailing до и после, то видно, что оно меняется и без присваивания.

Рефакторить toggle_mailing в рамках этой задачи точно не нужно.

2024-05-12 12:31 UTC, ASTimch commented on src/bot/handlers/menu.py
> +    user.has_mailing = await user_service.toggle_mailing(telegram_id)
Но для оптимизации его отрефачить полезно (или создать другую функцию в сервисе), т.к. в текущей реализации получается лишнее обращение в базу и получение user по telegram_id

2024-05-13 10:04 UTC, gorskyolga commented on src/bot/handlers/menu.py
> +    user.has_mailing = await user_service.toggle_mailing(telegram_id)
Создала отдельную задачу по рефакторингу toggle_mailing.

2024-05-13 10:06 UTC, gorskyolga commented on src/bot/handlers/menu.py
> +    user.has_mailing = await user_service.toggle_mailing(telegram_id)
Но мне кажется, что нужно вернуть, чтобы было просто `await user_service.toggle_mailing(telegram_id)` без присваивания.

2024-05-13 10:06 UTC, gorskyolga commented on src/bot/handlers/menu.py
> +        user.has_mailing = await user_service.toggle_mailing(telegram_id)
И здесь тоже можно сделать просто `await user_service.toggle_mailing(telegram_id)`

2024-05-13 10:23 UTC, gorskyolga commented
Проверила. Всё отлично, только присваивания user.has_mailing, которые ты добавил, смущают.
И, к сожалению, пока не получается проверить, принимает ли эндпоинты внешнего сайта данные. Они сейчас возвращают либо 401, либо 500. Но думаю, что body мы передаем корректно. Так что не будем ждать, пока эндпоинты починят.

2024-05-14 17:52 UTC, gorskyolga approved these changes

2024-05-14 18:06 UTC, merged