Fixed keyboards
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #51
Opened 2023-05-29 09:22 UTC by anastasiakorolyova97

Задача https://www.notion.so/b0e79798b82c4c23b89cc720b4b36859?pvs=4

Константы вынесла отдельными файлами, по хендлеру categories посмотрела - вроде там есть всё)

2023-05-29 12:49 UTC, NiKuma0 requested changes
Не много не верно поняла задачку, в следующий раз пиши, я уточню)

Не вижу основной части задачи - сейчас категории открываются по команде `/categories`, а должны по inline кнопке. Также вместо `CommandHandler("start", start_command)` должно быть `CommandHandler(commands.START, start_command)`

Надеюсь стало понятнее)

2023-05-29 12:49 UTC, NiKuma0 commented on src/bot/handlers.py
> +        text=keyboards_const.WELCOME_TEXT,
Нам нужно спрятать в константы не текст сообщений, а текст кнопок - `ReplyMarkupButton.text`. При этом нам не нунжны тексты `InlineReplyButton`. 
Именно эти значения мы используем несколько раз, тексты пусть пока остаются как есть.

2023-05-29 13:54 UTC, anastasiakorolyova97 commented on src/bot/handlers.py
> +        text=keyboards_const.WELCOME_TEXT,
Никита, не совсем поняла - значительная часть кнопок сделана через InlineKeyboardButton, мне вообще их не трогать, получается? По хендлерам, кажется, поняла, что нужно сделать)

2023-05-30 10:32 UTC, NiKuma0 commented on src/bot/handlers.py
> +        text=keyboards_const.WELCOME_TEXT,
Не совсем. От InlineKeyboardButton мы записываем `callback_data`-у в константы.

2023-06-01 11:47 UTC, NiKuma0 requested changes
Ви

2023-06-01 11:47 UTC, NiKuma0 commented on src/bot/bot.py
> +from src.bot.constants.callback_data import (
Импортируй сразу модуль, чтоб можно было так обращается `callback_data.ASK_YOUR_QUESTION`

2023-06-01 11:47 UTC, NiKuma0 commented on src/bot/bot.py
>      bot.add_handler(CallbackQueryHandler(subcategories_callback, pattern=r"category_\d+"))
Вот тут не хватает переменной .

2023-06-01 11:47 UTC, NiKuma0 commented on src/bot/bot.py
> +    bot.add_handler(CallbackQueryHandler(start_command, pattern=GET_CATEGORIES))
Эта функция должна срабатывать по команде `start`, оставь как было, просто добавь в файл `constains.commands`

2023-06-01 11:47 UTC, NiKuma0 commented on src/bot/bot.py
> +    bot.add_handler(CallbackQueryHandler(menu_callback, pattern=MENU))
Тут тоже должна быть команда.

2023-06-01 11:56 UTC, AleksandrLyo commented on src/bot/handlers.py
Если мы вызываем колбэк через кнопку то update.message.reply_text уже работать не будет, нужено везде где вызываем через кнопку заменить на context.bot.send_message

2023-06-02 13:41 UTC, NiKuma0 reviewed
Уже гораздо лучше! Поправь конфликт

2023-06-02 13:41 UTC, NiKuma0 commented on src/bot/bot.py
> +    bot.add_handler(CallbackQueryHandler(handlers.back_subcategory_callback, pattern=r"back_to_(\d+)"))
Эти паттерны тоже спрячь в переменные.

2023-06-02 13:41 UTC, NiKuma0 commented on src/bot/constants/keyboards_const.py
> +WELCOME_TEXT = "Привет! 👋 \n\n"
Убери не нужные переменные.

2023-06-05 10:57 UTC, NiKuma0 approved these changes

2023-06-05 10:58 UTC, merged