Замена декораторов validator и root_validator
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #514
Opened 2024-05-08 20:02 UTC by gorskyolga

**Что сделано:**

1. В соответствии с [гайдом по миграции](https://docs.pydantic.dev/latest/migration/#validator-and-root_validator-are-deprecated):
- декоратор validator заменен на field_validator;
- декоратор root_validator заменен на model_validator.

2. В соответствие с рекомендациями документации pydantic добавлен декоратор classmethod после [field_validator](https://docs.pydantic.dev/latest/concepts/validators/#field-validators) и после [model_validator](https://docs.pydantic.dev/latest/concepts/validators/#model-validators).

3. Исправлены названия декораторов в setup.cfg.

**Как тестировала:**
Проверяла работу функций, которые используют эти декораторы, до и после изменения. Всё работает, как ожидается.

2024-05-09 08:51 UTC, ASTimch commented on src/settings.py
>          if "https://" in v or "http://" in v:
Может тут стоит все-таки анализировать v.startswith("https://") or v.startswith("http://"). Смысл то валидатора, что указанная строка должна быть в начале.

2024-05-09 09:57 UTC, gorskyolga commented on src/settings.py
>          if "https://" in v or "http://" in v:
Да, точно. Заменю.

2024-05-10 20:08 UTC, eugemos requested changes

2024-05-10 20:08 UTC, eugemos commented on src/settings.py
>      @field_validator("PROCHARITY_URL", "HELP_PROCHARITY_URL")
Смотрю я на этот валидатор и возникает у меня вопрос: а как же `APPLICATION_URL` без него обходится (у него, кстати, сейчас нет слэша в конце)? Ответ: а потому что `urljoin`  эту проблему прекрасно решает.
И возникает тогда другой вопрос: а нафига это валидатор вообще нужен, если у нас везде `urljoin` используется?

2024-05-11 07:31 UTC, ASTimch commented on src/settings.py
>      @field_validator("PROCHARITY_URL", "HELP_PROCHARITY_URL")
> Смотрю я на этот валидатор и возникает у меня вопрос: а как же `APPLICATION_URL` без него обходится (у него, кстати, сейчас нет слэша в конце)? Ответ: а потому что `urljoin` эту проблему прекрасно решает. И возникает тогда другой вопрос: а нафига это валидатор вообще нужен, если у нас везде `urljoin` используется?

urljoin проблему решает, но только в нашем частном случае. Например, если бы базовый URL имел какой-то путь после базового урла (например PROCHARITY_URL=http://test6.procharity.corptest.ru/api"), то urljon(PROCHARITY_URL, "index.html") отбросит последний "api" (часть после последнего "/") и вернет урл "http://test6.procharity.corptest.ru/index.html" вместо ожидаемого (возможно) "http://test6.procharity.corptest.ru/api/index.html". И об этом следует помнить.

2024-05-11 10:45 UTC, gorskyolga commented on src/settings.py
>      @field_validator("PROCHARITY_URL", "HELP_PROCHARITY_URL")
Поупражнялась: https://trinket.io/python3/4a171739d4
Если проверяемый url (например, PROCHARITY_URL) будет иметь вид "https://base.ru/api", то этот валидатор отбросит последнюю часть и вернет "https://base.ru/". То есть в таком случае он только добавит проблем.

2024-05-11 11:09 UTC, ASTimch commented on src/settings.py
>      @field_validator("PROCHARITY_URL", "HELP_PROCHARITY_URL")
> Поупражнялась: https://trinket.io/python3/4a171739d4 Если проверяемый url (например, PROCHARITY_URL) будет иметь вид `https://base.ru/api`, то этот валидатор отбросит последнюю часть и вернет `https://base.ru/`. То есть в таком случае он только добавит проблем.

Ну да, т.к. внутри этого валидатора опять же используется urljoin(), а не просто добавляется "/" в конец, поэтому в текущем виде валидатор как бы и не нужен.

2024-05-11 11:41 UTC, gorskyolga commented on src/settings.py
>      @field_validator("PROCHARITY_URL", "HELP_PROCHARITY_URL")
Посмотрела, `urljoin` не везде используется. Есть f-строки:
APPLICATION_URL в src\core\services\email.py в EmailProvider метод create_temp_body (используется в двух других методах класса EmailProvider, которые пока нигде не используются);
PROCHARITY_URL в src\bot\utils.py в get_connection_url (нигде не используется).

2024-05-11 18:23 UTC, eugemos commented on src/settings.py
>      @field_validator("PROCHARITY_URL", "HELP_PROCHARITY_URL")
М-да, это прекрасно... Что я вижу:
- я имею превратное представление об `urljoin`. Это печально, но я исправлюсь;
- валидатор `check_last_slash_url` по задумке полезен, но его надо исправить (не использовать  `urljoin`);
- для однообразия этот валидатор надо применять ко всем URL  и, соответственно, во всех местах, где эти URL используются, исходить из того, что завершающий слэш в них есть (в том числе и во всех f-строках), а где это не так - поправить.

По поводу неиспользуемого кода - отдельная песня. В нашей кодовой базе его полным-полно, на каждом углу натыкаешься. Может начать кампанию по его отстрелу?

2024-05-11 21:32 UTC, gorskyolga commented on src/settings.py
>      @field_validator("PROCHARITY_URL", "HELP_PROCHARITY_URL")
Исправила. Пришлось добавить проверку, что проверяемый url не пустой. Во время Check app возникала ошибка IndexError: string index out of range для APPLICATION_URL.

По неиспользуемому коду.
Нужно запоминать места, где он встречается. Удалять его пока рано, возможно какой-то будем использовать. Например, методы в `EmailProvider`, о которых я писала выше, могут использоваться для админки бота.
Я создала черновик в бэклоге, туда можно писать, где такой код был обнаружен.

2024-05-12 07:01 UTC, eugemos requested changes

2024-05-12 07:01 UTC, eugemos commented on src/settings.py
> +        if v and v[-1] != "/":
Так получается, что если `v` - пустая строка, то оно не будет заменено на `"/"`.
Так, наверное, не должно быть?

2024-05-12 08:17 UTC, gorskyolga commented on src/settings.py
> +        if v and v[-1] != "/":
Да, точно. Иначе сломается там, где я в f-строке для APPLICATION_URL убирала слэш.

2024-05-12 18:53 UTC, eugemos approved these changes

2024-05-16 08:21 UTC, gorskyolga commented
Решила еще отрефакторить и применить валидатор check_last_slash_url также к STATIC_URL и ROOT_PATH.
Оказалось, что для ROOT_PATH наоборот последнего слэша не должно быть, т.к. он используется в APIRouter и с последним слэшем возникает ошибка:
AssertionError: A path prefix must not end with '/', as the routes will start with '/'
Соответственно добавила валидатор для проверки ROOT_PATH.

2024-05-17 12:19 UTC, eugemos requested changes

2024-05-17 12:19 UTC, eugemos commented on src/settings.py
> +    def check_prefix_not_end_with_slash(cls, v: str) -> str:
Надо бы подкорректировать название:
- у глагола end должно быть окончание s: ends;
- у валидатора ниже написано слитно startswith, а здесь раздельно: end_with. Надо сделать одинаково для однообразия.

2024-05-17 12:19 UTC, eugemos commented on src/settings.py
> +        return urljoin(self.PROCHARITY_URL, "tasks/")
Тут выше по тексту ещё куча аналогичных свойств и во многих нет завершающего `/`, но ты их не стала исправлять. Может и здесь не стоило? Или, наоборот, все исправить для однообразия (ну, кроме *.html)?

2024-05-17 17:34 UTC, gorskyolga commented on src/settings.py
> +        return urljoin(self.PROCHARITY_URL, "tasks/")
Я их все отдельно посмотрела, стоит им добавлять завершающий `/` или нет.
И только для этого случая исправление мне показалось оправданным:
- если вызывать этот url без `/`, то редиректит на url со `/`;
- это единственный url, который потом можно использовать в urljoin;
- в схеме Миро этот url указан со `/`.

2024-05-18 19:17 UTC, eugemos approved these changes

2024-05-18 21:13 UTC, merged