Корректировка API для вебапа с информацией о задании.
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #515
Opened 2024-05-12 18:40 UTC by eugemos

### Что сделано
Добавлен роутер `task_detail_router` с одним эндпойнтом для получения подробной информации о задании по его `id` (`GET task_detail/{task_id}`).
Изменён набор query-параметров, передаваемых в вебап, как указано в  #511.

### Как проверял
Локально.
На странице документации API тестировал новый эндпойнт. Задавал ему как существующие `id` задач, так и несуществующие.
В боте (menu/Посмотреть актуальные задания/Посмотреть задание) вызывал вебап и проверял переданные ему параметры.
_Примечание._ Тестовый вебап, отображающий переданные ему query-параметры, загружен на тестовый сервер ранее, при решении задачи #477.

2024-05-13 20:28 UTC, gorskyolga requested changes

2024-05-13 20:28 UTC, gorskyolga commented on src/api/endpoints/tasks.py
> +task_detail_router = APIRouter(dependencies=[Depends(check_header_contains_token)])
Эндпоинт должен быть доступен всем, без передачи токена. При check_header_contains_token он доступен только основному сайту.

Я пока не уточняла у заказчика, нужно ли ограничивать доступ к эндпоинту, учитывая, что та же информация по заданиям доступна без регистрации на основном сайте.
Если будет решено ограничивать, то потом поменяем на передачу id_hash пользователей.

2024-05-14 19:02 UTC, eugemos commented
Добавил ещё один небольшой рефакторинг (см. п. 3 описания).

2024-05-15 10:45 UTC, gorskyolga commented
> Добавил ещё один небольшой рефакторинг (см. п. 3 описания).

Главное, чтобы изменения в этой функции не повлияли на передачу данных со стороны сайта.
Сделала cherry-pick коммита в отдельную ветку, оттестировала на примере `auth/external_user_registration` (его проще всего из личного кабинета сайта вызвать). Вроде нормально токен читается.
Если на проде потом сломается, то откатим.

2024-05-15 11:07 UTC, eugemos commented
> > Добавил ещё один небольшой рефакторинг (см. п. 3 описания).
> 
> Главное, чтобы изменения в этой функции не повлияли на передачу данных со стороны сайта. Сделала cherry-pick коммита в отдельную ветку, оттестировала на примере `auth/external_user_registration` (его проще всего из личного кабинета сайта вызвать). Вроде нормально токен читается. Если на проде потом сломается, то откатим.

Что мне теперь делать, откатить этот коммит из моей ветки?

2024-05-15 11:11 UTC, gorskyolga commented
> > > Добавил ещё один небольшой рефакторинг (см. п. 3 описания).
> > 
> > 
> > Главное, чтобы изменения в этой функции не повлияли на передачу данных со стороны сайта. Сделала cherry-pick коммита в отдельную ветку, оттестировала на примере `auth/external_user_registration` (его проще всего из личного кабинета сайта вызвать). Вроде нормально токен читается. Если на проде потом сломается, то откатим.
> 
> Что мне теперь делать, откатить этот коммит из моей ветки?

Нет, не надо. Я отдельную ветку не буду мержить. Смержу этот коммит в составе этой ветки.

2024-05-15 11:24 UTC, gorskyolga approved these changes

2024-05-15 14:25 UTC, merged