feature/bot_update_logging
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #52
Opened 2023-05-29 09:54 UTC by KonstKorn

2023-05-29 12:37 UTC, NiKuma0 requested changes

2023-05-29 12:37 UTC, NiKuma0 commented on src/core/logging/setup.py
> +def logger_decor(func):
Функции точно здесь не место. Создай отдельный файл `src/core/logging/utils.py`

2023-05-29 12:37 UTC, NiKuma0 commented on src/core/logging/setup.py
> +            logging.config.dictConfig(LOGGING_DICTCONFIG)
А это зачем? Воспользуйся `structlog.get_logger`.

2023-05-29 12:37 UTC, NiKuma0 commented on src/core/logging/setup.py
> +            logging.info(f'Получено обновление: {update}')
Давай логгировать все что принимает функция.

2023-05-29 12:37 UTC, NiKuma0 commented on src/core/logging/setup.py
> +        except Exception as error:
Этого не надо.

2023-05-29 20:24 UTC, KonstKorn commented on src/core/logging/setup.py
> +        except Exception as error:
@NiKuma0 Привет! А как тогда отлавливать не пойманный update?

2023-05-29 20:27 UTC, KonstKorn commented on src/core/logging/setup.py
> +        except Exception as error:
что-то типа:
except:
            logging.error(f'Ошибка при обработке обновления: {}')
            not_caught_update(update)
и потом описать функцию not_caught_update, чтобы логировала этот случай?

2023-05-30 21:24 UTC, NiKuma0 requested changes
В целом первая часть таски готова, но я не вижу вторую - функция которая логгирует не пойманные update-s. Ее можно сделать из простого хендлера, который регистрируешь в самую последнюю очередь.

2023-05-30 21:24 UTC, NiKuma0 commented on src/core/logging/utils.py
> +        log.info(f"Получено обновление: Update - {update}; Context - {context}")
Лучше принимать `*args, **kwargs` и просто передать их отдельным аргументом, также воспользуйся асинхронной версией. Будет неплохо если еще допишешь имя функции, которая поймала этот update
```python
await log.ainfo(f"Запущенна функция {func.__name__}", args=args, kwargs=kwargs)
```

2023-05-30 21:24 UTC, NiKuma0 commented on src/core/logging/utils.py
>      def wrapper(update, context):
Тут должна быть асинхронная функция.

2023-06-02 12:47 UTC, KonstKorn commented
@NiKuma0 Привет! Посмотри, пожалуйста, обновленный PR. А то у меня не так много времени останется  исправлений.

2023-06-02 19:05 UTC, KonstKorn commented
@NiKuma0 Обновил PR. Оставил только логирование пойманных updates. Следующую таску знаю, поэтому сразу  начну думать как написать) спасибо за подсказку! Такого пока не  делал, но надеюсь разберусь)

2023-06-02 19:29 UTC, NiKuma0 approved these changes
Выглядит хорошо. Расскажи как тестировал и приложи скрин логов.

2023-06-02 19:43 UTC, KonstKorn commented
@NiKuma0 Запустил проект. Через свой телеграм-бот вводил команды /start и /categories.
Логи в терминале и в файле:
![image](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/104132844/152d086c-af78-463d-8985-eb3524fe8703)

2023-06-02 20:51 UTC, merged