feature: added auth/invitation for admin invitation emailing
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #523
Opened 2024-05-19 15:04 UTC by ASTimch

2024-05-20 17:47 UTC, gorskyolga requested changes

2024-05-20 17:47 UTC, gorskyolga commented on templates/email/invitation_email.html
> +<p>Токен для регистрации: {{ token }}</p>
Думаю, указывать отдельно значение токена не нужно.
Будущий админ будет переходить по полученной ссылке и заполнять регистрационную форму в админке бота.

2024-05-20 17:47 UTC, gorskyolga commented on src/core/services/email.py
> +            "token": token,
Передачу токена нужно убрать, т.к. в письме она не нужна.

2024-05-20 17:47 UTC, gorskyolga commented on src/core/services/email.py
>              "expiration": token_expiration,
Здесь token_expiration в секундах, а в письме нужно в часах. Может быть будет лучше в Settings сделать значение в часах, только тогда нужно при создании токена не забыть это учесть.

2024-05-20 17:47 UTC, gorskyolga commented on src/core/services/email.py
> +    def create_temp_body(self, path: str, token: str) -> dict:
Поменяй, пожалуйста, в функции send_invitation_link при вызове этой функции передаваемое значение для path с "invitation_link" на "register". Во фронте админки так предусмотрено.
Нужно изменить в этой строке:
template_body = self.create_temp_body("invitation_link", token)
Не могу для неё добавить комментарий, т.к. она за пределами изменяемого кода.

2024-05-21 17:11 UTC, ASTimch commented on src/core/services/email.py
> +    def create_temp_body(self, path: str, token: str) -> dict:
Поменял.

2024-05-25 09:18 UTC, gorskyolga requested changes

2024-05-25 09:18 UTC, gorskyolga commented on src/api/endpoints/admin_routers/invitation.py
> +class InvitationManager(UserManager):
Не уверена, что стоит заводить отдельный InvitationManager. Может в UserManager это добавить?
Ты так сделал просто, чтобы меньше переписывать код из старой ветки?
Менять не надо, предлагаю обсудить.

2024-05-25 09:18 UTC, gorskyolga commented on src/api/endpoints/admin_routers/invitation.py
> +        if existing_user:
Нужно поменять это условие. Иначе получится, что если новый админ не успел пройти по ссылке из письма в течение срока действия токена, будет невозможно для него создать токен-приглашение повторно для той же почты.

2024-05-25 14:20 UTC, ASTimch commented on src/api/endpoints/admin_routers/invitation.py
> +        if existing_user:
> Нужно поменять это условие. Иначе получится, что если новый админ не успел пройти по ссылке из письма в течение срока действия токена, будет невозможно для него создать токен-приглашение повторно для той же почты.

user_db (admin_users) - это уже база админов пользователей (когда он уже стал админом), а привязка email - token хранится в другой таблице admin_token_requests.

2024-05-26 10:02 UTC, ASTimch commented on src/api/endpoints/admin_routers/invitation.py
> +class InvitationManager(UserManager):
> Не уверена, что стоит заводить отдельный InvitationManager. Может в UserManager это добавить? Ты так сделал просто, чтобы меньше переписывать код из старой ветки? Менять не надо, предлагаю обсудить.

Делал, пытаясь по максимуму сохранить прежние наработки (на сколько это было возможно после всех рефакторингов)

2024-05-26 16:29 UTC, gorskyolga requested changes

2024-05-26 16:29 UTC, gorskyolga commented on src/api/endpoints/admin_routers/invitation.py
> +class InvitationManager(UserManager):
Поняла.
Оставляем пока так. После реализации остальных эндпоинтов для админки бота проведем рефакторинг, если посчитаем нужным.

2024-05-26 16:29 UTC, gorskyolga commented on src/api/endpoints/admin_routers/invitation.py
> +        if existing_user:
Да, точно. Здесь всё верно.

2024-05-26 16:29 UTC, gorskyolga commented on src/api/endpoints/admin_routers/invitation.py
> +invitation_router = APIRouter()
Нужно защитить этот роутер также, как сделано для user_router в `src\api\endpoints\users.py.

2024-05-26 16:59 UTC, ASTimch commented on src/api/endpoints/admin_routers/invitation.py
> +invitation_router = APIRouter()
Поправил

2024-05-26 16:59 UTC, ASTimch commented on src/api/endpoints/admin_routers/invitation.py
> +invitation_router = APIRouter()
> Нужно защитить этот роутер также, как сделано для user_router в `src\api\endpoints\users.py.

Поправил

2024-05-27 22:43 UTC, gorskyolga approved these changes

2024-05-27 23:08 UTC, merged