feature/add_task_volunteer_model
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #536
Opened 2024-05-23 13:50 UTC by Genek91

### Что сделано
`src\core\db\models.py`:
Добавлена промежуточная модель `TaskVolunteer` связь M2M.

`src\core\db\migrations\versions\`:
Создана миграция `2024-05-23_16.08.11_add_task_volunteer_model.py`

### Как проверял
Применил новую миграцию и проверил её создание в БД.

2024-06-01 12:22 UTC, gorskyolga requested changes

2024-06-01 12:22 UTC, gorskyolga commented on src/core/db/models.py
> +class TaskVolunteer(Base):
Переименуй, пожалуйста, модель в TaskResponseVolunteer.
Я поняла, что для хранения информации о волонтере, выбранном для выполнения задания, эффективнее будет использовать отдельную таблицу, если понадобится. Так что создаваемую сейчас модель будем использовать только для откликов. Соответственно лучше явно отразить это в названии и докстринге.

2024-06-01 12:22 UTC, gorskyolga commented on src/core/db/models.py
> +
Нужно добавить "id = None", как сделано в UsersCategories.
Т.к. не будем использовать модель для других сущностей кроме откликов, в таблице точно будет только одно сочетание для user_id и task_id, а значит дополнительный id записи будет лишним.

2024-06-01 12:22 UTC, gorskyolga commented on src/core/db/models.py
> +    tasks: Mapped[list["Task"]] = relationship(secondary="task_volunteer", back_populates="volunteers")
Мне кажется, с учетом изменения имени модели здесь лучше переименовать tasks в task_responses, а volunteers в responded_volunteers.
И соответственно в модели Task нужно аналогично переименовать.

2024-06-02 10:41 UTC, Genek91 commented on src/core/db/models.py
> +class TaskVolunteer(Base):
Переименовал

2024-06-02 11:20 UTC, gorskyolga approved these changes

2024-06-02 11:20 UTC, merged