feautre: add endpoints for task/post task/put
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #539
Opened 2024-05-26 16:31 UTC by ASTimch

2024-06-01 19:19 UTC, gorskyolga reviewed
Для инфо:
Пока поставила ревью на паузу. Есть ощущение, что в таком виде обновление задач будет неудобно вызывать со стороны сайта. Уточню это у разработчика сайта.
Плюс лучше сначала вмержить ветку с методом delete, чтобы можно было использовать новые названия роутеров.

2024-06-01 19:19 UTC, gorskyolga commented on src/api/endpoints/tasks.py
> +task_detail_router = APIRouter(dependencies=[Depends(check_header_contains_token)])
Если так сделать, то вэб-апп для заданий станет недоступным в боте.
Евгений в [PR по методу delete для нового эндпоинта "task"](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/pull/543) делает рефакторинг названий роутеров. Можно использовать название "task_write_router", которое он вводит.

2024-06-05 09:03 UTC, gorskyolga commented
Получила ответ от разработчика сайта:
- Put-запрос не нужен.
- Нужно сделать так, чтобы эндпоинт принимал информацию по заданию (и по новому для бота, и по ранее переданному) post -запросом.

Также в основную ветку были вмержены новые названия роутеров, можно их использовать.

2024-06-09 11:42 UTC, ASTimch commented
> Получила ответ от разработчика сайта:
> 
> * Put-запрос не нужен.
> * Нужно сделать так, чтобы эндпоинт принимал информацию по заданию (и по новому для бота, и по ранее переданному) post -запросом.
> 
> Также в основную ветку были вмержены новые названия роутеров, можно их использовать.

Как передавать task.id для этого post? Как и для группового обновления задач внутри json или как для методов get, delete в самому маршруте /{task_id}? Если в маршруте, то останется ли это поле внутри json и что делать, если они будут различаться?

2024-06-09 15:59 UTC, gorskyolga commented
> Как передавать task.id для этого post? Как и для группового обновления задач внутри json или как для методов get, delete в самом маршруте /{task_id}? Если в маршруте, то останется ли это поле внутри json и что делать, если они будут различаться?

Схема не меняется, task.id будет приходить в теле запроса, как и в групповом.

2024-06-13 16:42 UTC, gorskyolga requested changes

2024-06-13 16:42 UTC, gorskyolga commented on src/api/endpoints/tasks.py
> +from src.api.schemas.tasks import TaskRequest
Лучше импортировать из src.api.schemas, как две схемы строчкой выше.

2024-06-13 16:42 UTC, gorskyolga commented on src/api/endpoints/tasks.py
> +        # обновление существующей задачи
Лучше убрать комментарии здесь и ниже.

2024-06-13 16:42 UTC, gorskyolga commented on src/core/db/repository/task.py
> +        """Получить задачу по id с привязанными полями категорий."""
Здесь правильнее "категории" вместо "категорий".
По-хорошему, тут и названия методов нужно исправлять. Но лучше этот рефакторинг потом сделать отдельно.

2024-06-13 16:42 UTC, gorskyolga commented on src/api/services/task.py
> +        changed = any(attrs.get(name) and attrs.get(name) != old_task_dict.get(name) for name in trigger_fields)
Нужно предусмотреть обработку случая, когда trigger_fields = None.

2024-06-13 16:42 UTC, gorskyolga commented on src/api/endpoints/tasks.py
> +    task_obj = await task_service.get_user_task_id(task.id)
get_user_task_id делает лишний join. Лучше добавить в TaskService метод get_or_none и использовать вместо get_user_task_id. В репозитории уже есть метод get_or_none для него (Евгений недавно добавил в ContentRepository).

2024-06-13 16:42 UTC, gorskyolga commented on src/api/endpoints/tasks.py
> +        trigger_fields_changed = await task_service.update(task_obj, trigger_mailing_fields, **task.model_dump())
Нужно учесть, что если задача была архивная и по ней пришли обновления, то она должна стать не архивной. При актуализации заданий списком реализована такая логика.

2024-06-16 19:45 UTC, gorskyolga approved these changes

2024-06-16 19:52 UTC, merged