Добавление эндпойнтов для удаления пользователя сайта из БД бота
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #540
Opened 2024-05-26 19:59 UTC by eugemos

### Что сделано
1. В таблицу  `external_site_user` добавлен столбец  `is_archived` в соответствии с условиями задачи #516.
2. Добавлены два эндпойнта `DELETE(/external_user_registration/{user_id})` и `DELETE(/external_fund_registration/{user_id})`, которые выполняют одно и то же:
* при наличии в таблице `external_site_user` записи с заданным `external_id`, у которой в поле `is_archived` содержится `False`, в поле `is_archive` этой записи заносится `True`;
* при наличии у найденной записи связи с записью из таблицы `user` эта связь обнуляется, то есть уничтожается привязка этого пользователя в боте;
* при успешном выполнении команды возвращается статус 204, а если необходимая запись в таблице  `external_site_user` отсутствует, то 404.
3. Теперь при выполнении в боте команды `/start id_hash` также выполняется проверка, что у записи с заданным id_hash (если она есть) в поле  `is_archived` содержится `False`, и, если это не так, то привязка в боте не выполняется и выводится сообщение о необходимости авторизации на сайте.
4. Исправлена ошибка в методе `__init__` исключения  `NotFoundException`, из-за которой он падал при попытке его использования с ключевыми параметрами (видимо, я первый, кто попробовал его так использовать).
5. Дополнительный эффект: если после удаления пользователя попробовать зарегистрировать его снова, то для него создаётся новая запись в БД. Это получилось само, но, наверное, так и должно быть.

### Как тестировал
Локально. Использовал страницу документации API.
1. Создавал в БД бота нового пользователя сайта через эндпойнт `POST(/external_user_registration)`, и привязывал к нему текущего пользователя Телеграм командой `/start id_hash`. Проверял, что в боте всё работает.
2. Применял к этому пользователю один из новосозданных эндпойнтов. Проверял, что теперь в боте ничего не работает - по командам `/start`, `/start id_hash`, `menu` и при нажатии на inline-кнопки выводится предложение авторизоваться на сайте.
3. Также дополнительно проверял содержимое БД через DBeaver.
4. Проверял также ошибочные ситуации: что требуемого пользователя нет в БД или он уже был удалён ранее.

2024-06-01 10:07 UTC, Genek91 commented on src/core/db/repository/external_site_user.py
> +    async def archive(self, external_id: int) -> None:
Может стоит добавить докстринг?
Например как то так:
"""Архивирование пользователя сайта и удаление связи с ботом"""
или так:
"""Присваивает пользователю сайта статус is_archived и удаляет связь с ботом"""

2024-06-01 20:42 UTC, Genek91 approved these changes

2024-06-07 14:40 UTC, gorskyolga requested changes

2024-06-07 14:40 UTC, gorskyolga commented on src/core/db/migrations/versions/2024-05-24_20.54.50_add_is_archived_field_to_ext_site_user.py
> +"""add field is_archived to external_site_users
Миграцию нужно переделать, т.к. я вмержила в develop другие ветки с миграциями.

2024-06-07 14:40 UTC, gorskyolga commented on src/api/endpoints/external_site_user.py
> +    "/external_fund_registration/{user_id}",
Update по задаче:
нужно сделать только один эндпоинт для удаления и волонтеров, и фондов (/external_user_registration/{user_id}).

Так что нужно удалить второй эндпоинт.

2024-06-08 10:12 UTC, gorskyolga commented
По поводу п. 5 "Дополнительный эффект: если после удаления пользователя попробовать зарегистрировать его снова, то для него создаётся новая запись в БД. Это получилось само, но, наверное, так и должно быть."

Со стороны сайта такое поведение не требуется. По информации от заказчика, пользователь не может восстановить аккаунт на сайте после его удаления. Ему придётся регистрировать новый аккаунт, соответственно у него будет новый user_id и id_hash.
Так что, если сайт обратится к эндпоинту с таким же id_hash как у архивной записи, это будет ошибкой со стороны сайта.

По идее user_id и id_hash должны быть уникальными, но сейчас на уровне модели такого ограничения нет. Я создам отдельную задачу в бэклоге, т.к. перед этим нужно посмотреть, вдруг в БД на продакшен-сервере уже есть дубликаты.

В рамках этой задачи нужно ограничить возможность создать вторую запись с тем же id_hash. По коду оставлю комментарий об этом.

2024-06-08 10:13 UTC, gorskyolga commented on src/api/services/external_site_user.py
>          site_user = await self._site_user_repository.get_by_id_hash(site_user_schema.id_hash)
Мне кажется, вот здесь в вызов нужно добавить with_archived=True и затем проверять, если найденная запись архивная, то возвращать ошибку "Пользователь удален. Обновление не возможно".

2024-06-24 18:38 UTC, eugemos commented
Замечание.
В этом PR в `ExternalSiteUserRepository` добавлен метод `_add_test_not_archived_to_select`, а ранее в PR #543 в `ContentRepository` был добавлен метод `_add_archiveness_test_to_select`. Эти методы делают практически одно и тоже, но приводят к отличающемуся интерфейсу использующих их публичных методов.
Наверное, стоит провести унификацию и оставить только один из этих методов, разместив его в  `ContentRepository`.

2024-06-26 22:16 UTC, gorskyolga commented
> Наверное, стоит провести унификацию

Да, унификацию стоит провести, добавлю отдельную задачу в бэклог.

2024-06-27 10:25 UTC, gorskyolga approved these changes

2024-06-27 10:29 UTC, merged