Fix faulty transaction behaviour in set_categories_to_user
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #551
Opened 2024-06-08 13:03 UTC by StriderDunedain

2024-06-10 14:18 UTC, gorskyolga requested changes
Нужно переделать. Такое решение ломает обновление категорий при смене учётки (привязке телеграм-юзера к другому пользователю внешнего сайта).

Как повторить ошибку:
1. Создать через эндпоинт двух external_site_user с разным набором категорий (лучше выбирать те, что не архивные и не родительские, например, 11, 12, 13, 14).
2. Через бота привязаться к первому пользователю внешнего сайта. Проверить категории через кнопку бота "Перепроверить компетенции" (или посмотреть в БД).
3. Через бота привязаться ко второму пользователю внешнего сайта. Проверить категории.

В ветке с фичей категории не будут обновляться. Если перейти в ветку develop, то при повторении этих действий категории обновляются.

2024-06-10 14:33 UTC, gorskyolga commented
И обрати, пожалуйста, внимание, что обновление категорий должно происходить отдельной транзакцией.
Кажется, если begin убрать, то она не будет создаваться.
Почитай здесь: https://docs.sqlalchemy.org/en/20/orm/session_basics.html#framing-out-a-begin-commit-rollback-block

Чтобы разобраться, какая здесь была задумка, можно посмотреть этот PR:
https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/pull/380

2024-06-10 15:52 UTC, eugemos commented
Надо заполнить описание. Примеры можно посмотреть в других PR, например в #521 или #443 - там тоже про поиск и исправление ошибок.
Обязательно надо написать, в чём по-твоему причина ошибки, и обосновать способ исправления (если он не совсем уж очевиден).

2024-06-17 05:41 UTC, eugemos commented
Макс, не надо пытаться решить задачу с помощью шаманского бубна. Мы уже и так один раз это сделали и купировали  проблему. Теперь нам надо разобраться и от бубна избавиться (ну, или понять, что он и не бубен вовсе, а так и надо).
**Надо понять, почему в точке, где по нашему представлению не должно быть активных транзакций, она всё же есть.**
Без ответа на этот вопрос **никакое** твоё решение не будет удовлетворительным, будет просто замена шила на мыло.
Напиши лучше в коментах свои соображения по этому поводу, а кодировать не спеши.

2024-06-17 08:13 UTC, StriderDunedain commented
> Надо понять, почему в точке, где по нашему представлению не должно быть активных транзакций, она всё же есть

Стоп, а почему не должно быть транзакции? Как тогда сделать запрос? Я понял смысл задачи так - убрать вызов коммита и сделать обновление категорий отдельной транзакцией. Если этому следовать, не похоже, что мое решение просто новый костыль. Все как по документации. `.begin_nested()` создает транзакцию внутри транзакции. `self._session.in_nested_transaction()` возвращает True. Не очень понимаю, что не так

2024-06-17 10:12 UTC, eugemos commented
> Стоп, а почему не должно быть транзакции?

Если изучить код функции `bot.services.user.UserService.register_user`, то получается, что к моменту вызова `set_categories_to_user` не должно быть незавершённых транзакций. Не согласен?

> Я понял смысл задачи так - убрать вызов коммита и сделать обновление категорий отдельной транзакцией.

Думаю, что задача шире. Надо бы понять, что вообще происходит, и тогда можно будет выработать правильное решение, а не просто лучше, чем сейчас.
Возможно у @gorskyolga есть другое мнение?

2024-06-17 16:14 UTC, StriderDunedain commented
Так, как я понимаю есть два варианта решения задачи:
1. Завершить транзакцию создания пользователя до вызова `set_categories_to_user` (как раз то, что предлагаешь) и уже в самой функции присвоения категорий создать новую - этот вариант уже был сделан, еще до того, как я присоединился (хотя, возможно, есть какой-то другой способ завершить транзакцию, не через commit)
2. Сделать транзакцию присвоения категорий внутри транзакции создания пользователя - это то, что есть сейчас и оно, насколько я тестировал, работает, а потом они должны закрыться автоматически

2024-06-17 17:47 UTC, eugemos commented
Нет, не так.
Вариант №1 я не предлагаю, он просто уже **есть**. И мы его рассматриваем как костыль, который надо **устранить** - задача про это.
Вариант №2 ты как раз **предлагаешь** на замену первому.
И слишком рано ты решил, что нет других вариантов. Задача ведь не в том, чтобы заменить плохой костыль на хороший, а в том чтобы попытаться вылечить пациента, и он смог бы без костылей обходиться (если получится, конечно).
Я тебе как раз и предлагаю над этим подумать: разобраться, откуда перед вызовом `set_categories_to_user` взялась активная транзакция, и сделать так, чтобы её не было (ну, или убедиться, что это неизбежно, и тогда, да, надо выбирать между №1 и №2).
Не смотри только лишь в `set_categories_to_user`, проанализируй код, который её использует.

2024-06-30 19:53 UTC, gorskyolga commented
> Не получается ни обновить, ни присвоить те категории, которые не архивные и не родительские (например 11, 12, 13 и 14 подходят, а 21 нет), пользователь при этом создается. Не уверен, правильное ли это поведение

Эта фраза еще актуальна? Не поняла её.
То есть получается присвоить только архивные и родительские категории?

2024-07-02 10:57 UTC, StriderDunedain commented
1. Да, очень актуальна. Категории с `"is_archived": false` - присваиваются, значение "parent_id", похоже, не влияет, при смешении в запросе категорий с `"is_archived": true`  и `"is_archived": false` присваиваются категории только с `"is_archived": false`. Метод `.refresh()` из create'а не влияет на результат - что с ним, что без него поведение не меняется
2. Проверял только с категориями, потому что хорошо знаю за что и какие ручки дергать только в этих рамках, с другими функциями не очень знаком, поэтому с легкостью мог бы что-то упустить из виду. Лучше если проверит кто-то более опытный

2024-07-03 13:42 UTC, gorskyolga commented
Перечитала еще раз твой ответ по пункту 1 и протестировала.
1. Создаю через эндпоинт внешнего пользователя с категориями 1, 11, 21, 31 (1 - родительская, 11 и 31 - действующие, 21 - архивная).
2. Привязываю через бот пользователя Телеграм к внешнему пользователю. В БД в таблице users_categories отображаются все переданные категории.
3. Обновляю через эндпоинт категории у ранее созданного внешнего пользователя. Передаю сначала только категорию 11, а потом только категорию 21. Оба раза категории в users_categories обновляются для привязанного пользователя Телеграм.

Как я сказала на синке, мы не проверяем, какие категории передает сайт. В БД бота они сохранятся в таблице external_site_users в любом случае. А в users_categories успешно перекопируются, если id категории есть в БД. При этом не важно, архивная ли категория или нет, родительская или нет. 
НО: в боте категорий по кнопке "Изменить компетенции" отображаются только неархивные и дочерние. Судя по твоему ответу в пункте 1, ты мог проверять привязку категорий через бот, а не через БД.

2024-10-25 10:30 UTC, closed without merging