Добавление кнопки "Откликнуться" под сообщение с заданием
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #555
Opened 2024-06-10 18:37 UTC by eugemos

### Что сделано
1. Реализована функциональность в соответствии с условиями задачи #545.
2. Отдельный репозиторий и сервис для модели TaskResponseVolunteer создавать не стал. Поместил необходимые методы в репозиторий для модели ExternalSiteUser и соответствующий сервис. У нас уже есть аналогичный случай с моделью UsersCategories, там все методы размещены в репозитории и сервисах для модели User. Я решил не отклоняться от этой линии.

### Как тестировал
Локально. Использовал страницу документации API. Для просмотра БД использовал DBeaver.
1. Заполнил БД тестовыми данными без фейковых пользователей.
2. Через API создал пользователя сайта, связал с ним пользователя Телеграм (`/start id_hash`).
3. Вывел список актуальных заданий (`Меню/Посмотреть актуальные задания`). Затем стартовал бот ещё раз (`/start`) и вывел ещё один список актуальных заданий.
4. Проверил наличие кнопки "Откликнуться" под описаниями задач. Во втором списке проверил как работает эта кнопка - при её нажатии она превращается в кнопку "Отметить отклик", а в БД появляется соответствующая запись в таблице `task_response_volunteer `. Аналогично проверил работу кнопки  "Отметить отклик".
5. Первый список использовал для проверки реакции на устаревшие кнопки путём дублирования в нём действий, выполненных во втором списке.
6. Через API заархивировал одну из задач из списка и проверил поведение устаревших кнопок для этого случая.
7. С помощью другого устройства привязал к пользователю сайта другого пользователя Телеграм и проверил, что первый пользователь Телеграм при нажатии на старевшие кнопки получает предложение зарегистрироваться.

2024-06-18 15:42 UTC, gorskyolga requested changes

2024-06-18 15:42 UTC, gorskyolga commented on src/bot/handlers/tasks.py
> +            reply_markup=await get_task_info_keyboard(task, ext_site_user),
get_task_info_keyboard также используется в `src\api\endpoints\tasks.py` в actualize_tasks и create_update_task. Нужно подтянуть изменения из ветки debelop, create_update_task была недавно добавлена.

2024-06-18 15:42 UTC, gorskyolga commented on src/bot/handlers/tasks.py
> +    context: CallbackContext,
Заметила, что везде в хэндлерах `context: ContextTypes.DEFAULT_TYPE` и только в `src/bot/handlers/tasks.py` используется `context: CallbackContext`. Луше поменять на `context: ContextTypes.DEFAULT_TYPE` для единообразия.

2024-06-18 15:42 UTC, gorskyolga commented on src/core/db/repository/external_site_user.py
> +        если такого отклика ещё нет в БД, иначе просто возвращает False.
Мне кажется, как-то сложно читается докстринг. Может его так изменить здесь и в сервисе:

Создаёт отклик заданного пользователя на заданную задачу и возвращает True.
Если такой отклик уже есть в БД, просто возвращает False.

2024-06-18 15:42 UTC, gorskyolga commented on src/core/db/repository/external_site_user.py
> +        """
Мне кажется, сложно читается докстринг. Может его так изменить здесь и в сервисе:

Удаляет отклик заданного пользователя на заданную задачу и возвращает True.
Если такого отклика уже нет в БД, просто возвращает False.

2024-06-18 15:42 UTC, gorskyolga commented on src/core/db/repository/external_site_user.py
> +        async with self._session.begin():
Мне кажется, нужно использовать декоратор auto_commit из `src.core.utils.py` вместо этих двух строчек.

2024-06-18 15:42 UTC, gorskyolga commented on src/core/db/repository/external_site_user.py
> +        async with self._session.begin():
Мне кажется, нужно использовать декоратор auto_commit из `src.core.utils.py` вместо этих двух строчек.

2024-07-09 17:04 UTC, Xalgina commented
> У сообщений с заданиями есть кнопка "Посмотреть задание". Нужно добавить под неё кнопку "Откликнуться".

**Протестировано. ОК, кнопка есть**

> Если отклика волонтера на задание нет, то текст на кнопке "Откликнуться".

**Протестировано. ОК**

> Если отклик волонтера на задание есть, то текст на кнопке "Отменить отклик".

**Протестировано. ОК**

> Должна проверяться авторизация пользователя в боте. Пользователь Телеграм, у которого нет авторизации (связи с external_user, роли у external_user и т.д.), должен получать сообщение с требованием авторизоваться. 

**Протестировано. ОК**

> Если задание заархивировано, то должен отображаться поп-апп с текстом "Задание уже отдано в работу другому волонтеру".

**Протестировано. ОК**

> Если волонтер нажимает на кнопку "Откликнуться", то должна создаваться запись об отклике в таблице task_response_volunteer и текст на кнопке должен меняться на "Отменить отклик".

**Протестировано. ОК**

> Если волонтер нажимает на кнопку "Отменить отклик", то запись об отклике должна удаляться из таблицы task_response_volunteer и текст на кнопке должен меняться на "Откликнуться".

**Протестировано. ОК**


> при попытке откликнуться на задание, по которому волонтер уже откликнулся, нужно отображать поп-апп с текстом "Ты уже откликнулся на это задание";

**Протестировано. ОК**

> при попытке отменить отклик на задание, по которому отклик уже был отменен, нужно отображать поп-апп с текстом "Ты уже отменил отклик на это задание".

**Протестировано. ОК**

> При этом кнопки должны меняться на правильные.

**Протестировано. ОК**

2024-07-09 17:05 UTC, Xalgina approved these changes

2024-07-11 13:38 UTC, gorskyolga commented on src/core/db/repository/external_site_user.py
> +            self._session.add(response)
Я задумалась, не лучше ли будет вместо self._session.add и auto_commit использовать метод create из AbstractRepository.

2024-07-11 13:38 UTC, gorskyolga commented on src/core/db/repository/external_site_user.py
> +            await self._session.delete(response)
А здесь соответственно вместо self._session.delete и auto_commit использовать метод remove из AbstractRepository?

2024-07-11 19:09 UTC, eugemos commented on src/core/db/repository/external_site_user.py
> +            self._session.add(response)
С одной стороны, конечно, лучше воспользоваться готовым методом, что бы все объекты создавались по одной схеме независимо от их типа. А с другой стороны есть вопрос: а законно ли использовать `ExternalSiteUserRepository` для создания объекта типа `TaskResponseVolunteer`? Я именно про законность, технически-то это будет работать. Дело тут в том, что  `AbstractRepository` - обобщённый тип и при применении, по идее, должен конкретизироваться типом модели, то есть должно было быть
```
class ExternalSiteUserRepository(AbstractRepository[ExternalSiteUser]):
  ...
```
а не 
```
class ExternalSiteUserRepository(AbstractRepository):
  ...
```
как у нас, и должен применяться линтер, который бы проверял соответствие типов, и  "не позволял" бы использовать методы `AbstractRepository[ExternalSiteUser]` для работы с `TaskResponseVolunteer`. Но у нас сейчас нет ни того ни другого.

И тут надо определиться, каковы наши намерения относительно линтера и аннотаций типов. Если мы хотели бы по-честному придерживаться заданных типов, тогда надо использовать линтер и на него ориентироваться в вопросах, что можно и что нельзя. Если же нет, тогда, конечно, мы можем позволить себе ~~не соблюдать диету~~ больше, но это плохой путь с моей точки зрения.

2024-07-11 20:12 UTC, gorskyolga commented on src/core/db/repository/external_site_user.py
> +            self._session.add(response)
Добавила в бэклог.

2024-07-11 20:12 UTC, gorskyolga commented on src/core/db/repository/external_site_user.py
> +            await self._session.delete(response)
Добавила в бэклог.

2024-07-11 20:44 UTC, gorskyolga approved these changes

2024-07-11 20:48 UTC, merged