Password reset draft
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #571
Opened 2024-06-24 17:19 UTC by StriderDunedain

** ! Draft ! **
## Что сделано
Добавил `on_after_forgot_password`, добавил эндпоинты сброса паролей и попытался настроить отправку сообщений, но, как показал дебаг принтом, добавленный метод вообще не затрагивается (хотя эндпоинты появились в доке)

## Предложения по решению
Пока не очень понимаю, где не туда пошел. Возможно что-то в логике вызова методов

2024-06-24 19:42 UTC, gorskyolga commented on src/api/router.py
> +api_router.include_router(fastapi_users.get_reset_password_router(), prefix="/auth", tags=["Reset Password"])
Нужно подключать не здесь, а в admin_user_router.

2024-06-24 19:54 UTC, gorskyolga commented on src/api/router.py
> +api_router.include_router(fastapi_users.get_reset_password_router(), prefix="/auth", tags=["Reset Password"])
Нужно подключать не здесь, а в admin_user_router.

2024-06-27 16:11 UTC, StriderDunedain commented
В целом весь процесс работает, но есть несколько вопросов по задаче:

1. В письме, которое приходит на почту есть ссылка для получения токена для сброса пароля. Сейчас если по ней перейти, будет пустая страница `{"detail": "Not Found"}`. По идее так и должно быть - никакого html-шаблона по нее нет. Его добавить и подключить или так оставить? (Сам токен пока что можно взять из url)
2. За токен, использующийся при смене пароля, отвечает переменная `reset_password_token_secret`. По идее хорошо бы его привязать к какому-нибудь алгоритму шифрования - сейчас это просто константа-строка, поэтому токен каждый раз одинаковый. Как лучше такое реализовать? SHA-256 / UUID?

2024-06-30 22:08 UTC, gorskyolga commented
Ответы на вопросы:
1. Шаблон есть во фронте админке, ничего подключать не нужно.
2. У тебя точно токен каждый раз одинаковый? У меня они разные.
3. Пока не нужно добавлять, т.к. такого пожелания от заказчика не поступало.

2024-07-01 10:49 UTC, gorskyolga commented
> 2\. За токен, использующийся при смене пароля, отвечает переменная `reset_password_token_secret`. По идее хорошо бы его привязать к какому-нибудь алгоритму шифрования - сейчас это просто константа-строка, поэтому токен каждый раз одинаковый. Как лучше такое реализовать? SHA-256 / UUID?

Посмотрела код библиотеки. В `get_reset_password_router` используется `forgot_password`, а в ней для генерации токена используется функция `generate_jwt`, у которой по умолчанию JWT_ALGORITHM = "HS256".

2024-07-02 13:49 UTC, StriderDunedain commented
Да, токен оказывается разный каждый раз. Наверное поздно слишком сидел, когда разбирался. А насчет шаблона не очень понял. Если он есть, значит его надо как-то связать со страницей пароля? В общем смутно осознаю, что делать дальше. Нужна помощь

2024-07-04 08:57 UTC, gorskyolga requested changes

2024-07-04 08:57 UTC, gorskyolga commented on src/api/router.py
> +api_router.include_router(fastapi_users.get_reset_password_router(), prefix="/auth", tags=["Reset Password"])
Остальные роутеры fastapi_admin_users подключаются в admin_user_router в `src\api\endpoints\admin.py`. Нужно сделать также.

2024-07-04 08:57 UTC, gorskyolga commented on src/api/fastapi_admin_users.py
> +    verification_token_secret = SECRET
Это секрет для другого роутера (из группы "Verify router"). Его не нужно задавать.

2024-07-04 08:57 UTC, gorskyolga commented on src/api/fastapi_admin_users.py
> +SECRET = "SECRET"
Если мы добавляем какой-то секрет, то его нужно выносить в переменные окружения и в Settings в `src\settings.py`.
В env.example уже есть переменная, используемая для создания jwt-токена (при приглашении нового админа), называется SECRET_KEY. Думаю, можно её же использовать и для восстановления пароля.

2024-07-04 08:57 UTC, gorskyolga commented on src/api/fastapi_admin_users.py
> +        email_provider.send_restore_password_link(user.email, token)
По факту сейчас письмо не отправляется. Здесь не хватает await, поэтому возникает ошибка "RuntimeWarning: coroutine 'EmailProvider.send_restore_password_link' was never awaited".

2024-07-04 09:37 UTC, gorskyolga commented
> Да, токен оказывается разный каждый раз. Наверное поздно слишком сидел, когда разбирался. А насчет шаблона не очень понял. Если он есть, значит его надо как-то связать со страницей пароля? В общем смутно осознаю, что делать дальше. Нужна помощь

В рамках текущей задачи делать с шаблоном ничего не нужно.
Если хочется посмотреть, как он сейчас выглядит, то есть два варианта:
1. Установить в переменных окружения значение APPLICATION_URL как "procharity.duckdns.org". В этом случае естественно не получится завершить восстановление пароля по полученной ссылке вида (https://procharity.duckdns.org/admin/#/reset_password/some_token), т.к. токен из локальной БД, а не из БД на тестовом сервере. Но можно просто посмотреть, что шаблон есть.
2. Развернуть репозиторий с фронтом админки бота локально и открыть страницу вида "http://localhost:3000/admin/#/reset_password/some_token".

2024-09-20 05:18 UTC, closed without merging