Refactor notification endpoints 568
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #578
Opened 2024-06-29 21:45 UTC by ASTimch

При проверке api/messages и api/messages/{telegram_id} иметь ввиду, что при режиме settings.DEBUG=True авторизация не обязательна.

2024-07-05 10:11 UTC, gorskyolga requested changes

2024-07-05 10:11 UTC, gorskyolga commented on src/api/endpoints/notification.py
> +        Depends(fastapi_admin_users.current_user(optional=settings.DEBUG, superuser=True)),
Эндпоинт должен быть доступен всем админам, а не только суперюзерам.

2024-07-07 19:30 UTC, ASTimch commented on src/api/endpoints/notification.py
> +        Depends(fastapi_admin_users.current_user(optional=settings.DEBUG, superuser=True)),
А приглашение может отправить любой админ или только superuser?
+ наверное во все зависимости user предлагаю добавить аctive=True (чтоб можно было делать какую-то админку не активной и забирать полномочия)

2024-07-08 09:53 UTC, gorskyolga commented on src/api/endpoints/notification.py
> +        Depends(fastapi_admin_users.current_user(optional=settings.DEBUG, superuser=True)),
Приглашение может отправить только superuser.
superuser будет отличаться от обычного админа тем, что сможет приглашать / удалять админов и удалять сообщения.
С аctive=True - хорошая идея. Лучше это сделать отдельной задачей, чтобы тестировать проще было. Добавлю в бэклог.

2024-07-12 15:29 UTC, gorskyolga approved these changes

2024-07-13 16:36 UTC, Xalgina approved these changes
протестировано

2024-07-13 16:57 UTC, merged