Change indent
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #581
Opened 2024-07-03 11:57 UTC by gorskyolga

Исправлен отступ для корректного отображения текста.

2024-07-03 12:25 UTC, gorskyolga commented
@gorskyolga тест отправки письма

2024-07-05 18:53 UTC, Xalgina requested changes
баг-репорт

2024-07-05 18:59 UTC, Xalgina requested changes
оставила 2 комммента

2024-07-05 18:59 UTC, Xalgina commented on README.md
> -  Если тестовая база данных должна содержать только задания и не должна содержать таблицу пользователей, то необходимо выполнить команду:
коммент

2024-07-05 18:59 UTC, Xalgina commented on README.md
> +    Если тестовая база данных должна содержать только задания и не должна содержать таблицу пользователей, то необходимо выполнить команду:
++

2024-07-05 19:00 UTC, gorskyolga commented on README.md
> -  Если тестовая база данных должна содержать только задания и не должна содержать таблицу пользователей, то необходимо выполнить команду:
Решено

2024-07-05 19:02 UTC, Xalgina approved these changes
все ок

2024-07-05 19:39 UTC, merged