Рефакторинг Content модели и репозитория
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #583
Opened 2024-07-03 14:14 UTC by Genek91

### Что сделано

- `ContentBase` переименован в `ArchivableBase`.
- Создан репозиторий `ArchivableRepository`, в него перенесены методы `_add_archiveness_test_to_select`, `get_or_none` и `get`.
- Метод `_add_test_not_archived_to_select` заменён на `_add_archiveness_test_to_select`, в связи с этим были внесены поправки в методы которые связаны с архивированием внешнего пользователя.

### Как тестировал
Проверил работоспособность эндпоинтов:

- `/api/auth/external_user_registration/`
- `/api/auth/external_fund_registration/`
- `/api/auth/external_user_registration/{user_id}`

Через DBeaver проверял результат:
Обновлял данные пользователя, делал его архивным, получал ожидаемую ошибку при попытке изменить данные у пользователя который был в архиве и т.п.

2024-07-07 07:54 UTC, eugemos requested changes
В `UserRepository` есть метод `get_user_categories(self, user: User, with_archived=False)`, который напрашивается на рефакторинг по данному пути, но тогда его надо перенести в `CategoryRepository`, что, кстати, и без того выглядит довольно логично.
Может, это стоит сделать отдельной задачей, @gorskyolga ?

2024-07-07 07:54 UTC, eugemos commented on src/core/db/models.py
> +    """Базовый класс для архивных данных."""
Неудачный докстринг: речь ведь не об архивных данных, а о данных, которые можно заархивировать (и тогда они станут архивными).

2024-07-07 07:54 UTC, eugemos commented on src/core/db/repository/base.py
> +    """Абстрактный класс, для архивных данных."""
Неудачный докстринг: речь ведь не об архивных данных, а о данных, которые можно заархивировать (и тогда они станут архивными).

2024-07-07 11:30 UTC, gorskyolga commented
> В `UserRepository` есть метод `get_user_categories(self, user: User, with_archived=False)`, который напрашивается на рефакторинг по данному пути, но тогда его надо перенести в `CategoryRepository`, что, кстати, и без того выглядит довольно логично. Может, это стоит сделать отдельной задачей, @gorskyolga ?

Да, добавила задачу в бэклог.

2024-07-07 13:22 UTC, gorskyolga requested changes

2024-07-07 13:22 UTC, gorskyolga commented on src/core/db/repository/external_site_user.py
> +    async def get_by_id_hash(self, id_hash: str, archived: bool | None = None) -> ExternalSiteUser | None:
Так как меняется значение по умолчанию, это влияет на:
- get_by_id_hash в `src\bot\services\external_site_user.py`;
- decorated_handler в `src\bot\utils.py`.

В decorated_handler при помощи get_by_id_hash нужно получать только записи с is_archived = False.

2024-07-08 08:27 UTC, eugemos requested changes

2024-07-08 08:27 UTC, eugemos commented on src/core/db/repository/base.py
> +    """Абстрактный класс для данных, которые можно заархивировать."""
Лучше так: "Абстрактный класс для репозитория с данными, которые можно архивировать."

2024-07-08 08:27 UTC, eugemos commented on src/core/db/repository/external_site_user.py
> +    async def get_by_id_hash(self, id_hash: str, archived: bool | None = None) -> ExternalSiteUser | None:
1. В методах базового класса аналогичный параметр называется `is_archived`. С учётом того, что этот параметр вполне может передаваться как ключевой, надо сделать одинаковые имена.
2. Сомневаюсь я, хорошо ли мы сделали, выбрав значением по умолчанию `archived=None`. Получилось, что в большинстве случаев приходится явно задавать `False` и паттерн 'soft delete' стал непрозрачным, а по идее клиентскому коду не надо знать, как реализовано удаление, за исключением специальных случаев. Не лучше ли `archived=False`, @gorskyolga?

2024-07-08 08:52 UTC, eugemos commented
К стати, в описании PR сказано, что тестировались эндпойнты API, а про бот ничего не сказано. А ведь изменения и туда проникли.

2024-07-08 09:38 UTC, gorskyolga commented on src/core/db/repository/external_site_user.py
> +    async def get_by_id_hash(self, id_hash: str, archived: bool | None = None) -> ExternalSiteUser | None:
Да, лучше переделать значение по умолчанию, тогда нужно будет только в одном месте кода поменять (где Женя это изначально учёл). А в decorated_handler изменений не будет.

2024-07-09 13:04 UTC, eugemos requested changes

2024-07-09 13:04 UTC, eugemos commented on src/core/db/repository/external_site_user.py
> +        self, external_id: int, is_archived: bool | None = None
Тут значение по-умолчанию тоже надо исправить.

2024-07-09 13:04 UTC, eugemos commented on src/core/db/repository/external_site_user.py
> +    async def get_by_external_id(self, external_id: int, is_archived: bool | None = None) -> ExternalSiteUser:
Тут значение по-умолчанию тоже надо исправить.

2024-07-09 13:04 UTC, eugemos commented on src/core/db/repository/external_site_user.py
>      async def get_or_create_by_id_hash(self, id_hash: str) -> tuple[ExternalSiteUser, bool]:
Этот метод перестал быть правильным, так как не учитывает поле `is_archived`. К тому же, он используется одним единственным методом из `bot.services.external_site_user`, который, в свою очередь, никем не используется.
Предлагаю их оба удалить.

2024-07-09 13:04 UTC, eugemos commented on src/core/db/repository/base.py
> +
В строках 136 и 141 надо изменить значение по-умолчанию на False и, если требуется, учесть это изменение в использующем эти методы коде.

2024-07-10 12:25 UTC, Genek91 commented
Подскажите, а почему методы `get` и `get_or_none` из класса `ArchivableRepository` имеют двойное назначение (получение данных по id и получение данных по id + условия фильтрации True/False)? Не правильнее ли было разделить на get и get_by_filter или как то так... И вот это переопределение этих же методов из `AbstractRepository`, мне кажется только путает.

2024-07-10 12:44 UTC, eugemos commented
> Подскажите, а почему методы `get` и `get_or_none` из класса `ArchivableRepository` имеют двойное назначение (получение данных по id и получение данных по id + условия фильтрации True/False)? Не правильнее ли было разделить на get и get_by_filter или как то так... И вот это переопределение этих же методов из `AbstractRepository`, мне кажется только путает.

Тут всё дело в том, что поле `is_archived` не является атрибутом объекта. Это метаданные, показывающие, что объект удалён - так мы реализуем паттерн 'soft delete', о котором я упоминал ранее. Любой метод доступа (в том числе и  `get_by_filter`) по умолчанию должен игнорировать объекты, которые имеют `is_archived == True`. Но для специальных случаев, когда нам всё же нужно наличие в выборке ранее удалённых объектов (или только их), мы добавляем спец. параметр к методам доступа, который позволяет нам это задать. Его значение по умолчанию должно быть таким, чтобы обычный код мог ничего о нём не знать и работать нормально. Можно, конечно, сделать для этих случаев специальные методы доступа (типа `get_with_archived`), но тогда, возможно, придётся почти каждый метод доступа продублировать.

2024-07-12 12:09 UTC, eugemos requested changes

2024-07-12 12:09 UTC, eugemos commented on src/api/services/task.py
В строке 16 надо тоже исправить значение по умолчанию на False.

2024-07-12 12:09 UTC, eugemos commented on src/core/db/repository/external_site_user.py
Давай в строке 38 уберём второй параметр (False), чтобы паттерн 'soft delete' здесь не вылезал.
И аналогично надо исправить в `src/core/db/repository/task.py` в строке 71.

2024-07-14 12:48 UTC, gorskyolga requested changes

2024-07-14 12:48 UTC, gorskyolga commented on src/api/endpoints/tasks.py
> +    task_obj = await task_service.get_or_none(task.id, None)
В этом же файле нужно аналогично поменять вызов метода get в get_task_detail, т.к. изменяется значение по умолчанию.

2024-07-14 12:48 UTC, gorskyolga commented on src/api/services/task.py
> +    async def get_or_none(self, task_id: int, is_archived: bool | None = False) -> Task | None:
Я вмержила в ветку изменения из develop.
1. Добавлен такой же метод get_or_none в TaskService в `src\bot\services\task.py`. В нем нужно сделать аналогичные изменения.
2. Добавлено использование метода из п.1 в respond_to_task_callback в `src\bot\handlers\tasks.py` (87 строка). В нем нужно добавить None в вызов.

2024-07-15 12:16 UTC, eugemos commented on src/api/endpoints/tasks.py
> +    task_obj = await task_service.get_or_none(task.id, None)
Получается эндпойнт get_task_detail позволяет получить задачу даже если она заархивирована. Это так задумано?

2024-07-15 16:47 UTC, gorskyolga commented on src/api/endpoints/tasks.py
> +    task_obj = await task_service.get_or_none(task.id, None)
Да, так задумано. Мы в нем повторяли логику для get-запроса на "api/tasks". А в нем возвращаются списком все задания, и архивированные, и нет.

2024-07-15 16:48 UTC, gorskyolga commented on src/api/endpoints/tasks.py
> +    task_obj = await task_service.get_or_none(task.id, None)
Плюс для отрисовки вэб-аппа может быть полезно разделять архивированные задания от никогда не существовавших.

2024-07-15 17:47 UTC, eugemos approved these changes

2024-07-15 19:24 UTC, gorskyolga approved these changes

2024-07-15 19:25 UTC, Xalgina approved these changes

2024-07-15 19:31 UTC, merged