Refactored CustomFastAPIUsers
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #590
Opened 2024-07-11 16:13 UTC by StriderDunedain

### Что сделано
Убрал лишнюю логику из `CustomFastAPIUsers`, унаследовавшись от базового `FastAPIUsers`, а также удалил файл auth.py, так как он полностью (за исключением докстринга) совпадает с методом из коробки. Метод `get_register_router` убрать не получилось - в нем много кастомных изменений

2024-07-11 16:54 UTC, gorskyolga requested changes

2024-07-11 16:54 UTC, gorskyolga commented on src/api/fastapi_admin_users.py
> +class CustomFastAPIUsers(FastAPIUsers, Generic[models.UP, models.ID]):
Почитай, пожалуйста, параграф [Defining subclasses of generic classes](https://typing.readthedocs.io/en/latest/source/generics.html#defining-subclasses-of-generic-classes).

2024-07-11 16:54 UTC, gorskyolga commented on src/api/fastapi_admin_users.py
> -        return get_auth_router(
get_auth_router очень похож на стандартный метод из библиотеки, но имеет важное отличие от него. 
OAuth2PasswordRequestForm в нем переопределен.

2024-07-12 09:07 UTC, gorskyolga requested changes
Макс, подскажи, пожалуйста, как ты проверял, что код, который ты удаляешь, действительно ничего не переопределяет?
Здесь нужно проверить не то, что приложение запускается без удаленного кода, а аккуратно вычитать удаляемый код. Судя по удалению get_auth_router, тебе следует еще раз аккуратно всё проверить.

2024-07-12 09:07 UTC, gorskyolga commented on src/api/fastapi_admin_users.py
> -        return get_auth_router(
get_auth_router нельзя удалять из CustomFastAPIUsers, он должен переопределять стандартный метод.

2024-07-12 10:12 UTC, StriderDunedain commented
Да, упустил, что `get_auth_router` нужно оставить. Что-то последнее время какой-то несобранный. Наверное, из-за скорого переезда с универом 😓 Постараюсь более внимательно вычитывать, спасибо! Добавил `get_auth_router`, но как проверять, что все работает тип-топ, не уверен. Хотя, раз - теперь точно - убран только дублирующийся код, остальное должно работать как надо. Если нужна проверка, то у Халгины лучше получится протестить - ни постгрес, ни dbeaver, ни что-либо еще я пока так и не заставил работать. На всякий -  [Флоучарт для, в частности, FastAPIUsers](https://fastapi-users.github.io/fastapi-users/latest/configuration/overview/)

2024-07-12 17:30 UTC, gorskyolga commented
Макс, ты забыл запушить изменения;)

2024-07-14 17:48 UTC, Xalgina reviewed
/api/v1/auth/invitation

2024-07-14 17:59 UTC, gorskyolga commented
> /api/v1/auth/invitation возвращает 500, если поле is_superuser": null, при этом запись с токеном в таблице admin_token_requests на указанную почту уже существует.
> 
> Если передавать нормальные значения (True, False) несколько раз, то всё работает.
Спасибо!

Так как данное поведение наблюдается и в develop, то решать будем отдельной задачей.

2024-07-14 18:02 UTC, gorskyolga approved these changes

2024-07-14 18:12 UTC, Xalgina approved these changes

2024-07-14 18:19 UTC, merged