Users router - предварительный просмотр
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #597
Opened 2024-07-17 13:12 UTC by StriderDunedain

### Что сделано
Добавил схему `AdminUserUpdate`, добавил `get_users_router` и поменял `tags` у роутера `invitation_router`
### Что происходит сейчас
Жду ответа на вопросы программного бытия

2024-07-21 11:43 UTC, gorskyolga requested changes
Нужно добавить валидаторы, как мы обговаривали.

2024-07-21 11:43 UTC, gorskyolga commented on src/api/schemas/admin.py
> +    def validate_password(cls, value: str) -> str | Never:
Нужно переделать этот валидатор. Сейчас он падает, если проверяет значение null.
И нужно добавить валидатор для проверки, что в поле email не передано null.

2024-07-21 11:56 UTC, gorskyolga commented
У тебя не получилось оттестировать энпдоинты, кроме оканчивающихся на me/, скорее всего из-за того, что созданный админ не был суперюзером.

2024-07-23 13:33 UTC, Xalgina commented
Протестировала null в полях "password" и "email". Возвращается 400 с соответствующим текстом ошибки.

Но такой же баг появляется еще в трех полях в  PATCH /api/v1/admins/:id. См. ниже:

[BUG] 500 Internal Server Error в PATCH /api/v1/admins/:id при **null** в полях **"is_active", "is_superuser", "is_verified"**

ОР: 400 Bad Request
ФР: 500 Internal Server Error

На скрине для примера "is_active": null. Такое же поведение и в случаях "is_superuser": null или "is_verified": null
![image](https://github.com/user-attachments/assets/9746d90f-52e8-4337-a5b5-967e2d92d850)

2024-07-23 13:47 UTC, StriderDunedain commented
Хм, тестировал через документацию - все было норм. Вечером посмотрю через постман, спасибо!

2024-07-25 08:54 UTC, gorskyolga requested changes
Нужно добавить один общий валидатор для "is_active", "is_superuser", "is_verified" с проверкой, что при передаче этих полей их не передают как null.

2024-07-30 19:11 UTC, Xalgina approved these changes
Протестировано. ОК

2024-07-31 08:51 UTC, gorskyolga approved these changes

2024-07-31 08:55 UTC, merged