(#565) popup responses depend on user moderation status
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #598
Opened 2024-07-17 20:07 UTC by ASTimch

Как проверял:
 - вручную изменял статус модерации и признак is_archive задачи и отслеживал ответный popup.
 
 Замечен баг (подозреваю, что глобальный)
 - если в ходе общения с ботом поменять статус модерации пользователя в б/д, то значение поля site_user.moderation_status не изменяется. Повторное обращение к базе тоже почему-то успехом не увенчалось (надо повторить на других клиентах).
  Необходимо продумать в какой момент бот должен перечитывать / анализировать текущие статусы пользователя (is_archeved, а также статус модерации). Возможно, это следует делать при каждом нажатии на каждую кнопку.

2024-07-19 07:57 UTC, gorskyolga commented on src/bot/handlers/tasks.py
> +        await context.bot.answer_callback_query(query.id, text=popup_text, show_alert=True)
Кажется, после этой строки нужно добавить return, иначе в логах появляется ошибка "telegram.error.BadRequest: Message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message".

2024-07-19 08:11 UTC, gorskyolga requested changes

2024-07-19 08:11 UTC, gorskyolga commented on src/bot/handlers/tasks.py
> +    # site_user = await site_user_service.get_by_id(site_user.id)  # почему-то не работает :/
Этот комментарий нужно удалить.

2024-07-19 08:11 UTC, gorskyolga commented on src/bot/handlers/tasks.py
> +            # moderation_status: (None, NEW_VOL, NO_MODERATED, BLOCKED)
Мне кажется, лучше этот комментарий перенести в докстринг функции в формате "Волонтёр не может откликаться на задание, если от сайта приходит статус модерации NEW_VOL, NO_MODERATED, BLOCKED или отсутствует".

2024-07-30 19:02 UTC, ASTimch commented on src/bot/handlers/tasks.py
> +        await context.bot.answer_callback_query(query.id, text=popup_text, show_alert=True)
Модифицировал логику: теперь клавиатура перерисовывается только если изменился статус отклика.

2024-07-31 10:33 UTC, gorskyolga commented
@Xalgina , при тестировании нужно менять статус волонтера через post-запрос к "api/auth/external_user_registration/volunteer" или patch-запрос к "api/auth/external_user_registration/volunteer/{user_id}".
Актуальность задания (is_archeved) нужно переключать через delete-запрос к "api/task/{task_id}" и post-запрос к "api/task".

2024-08-01 19:35 UTC, Xalgina reviewed
[BUG] Не тот текст, когда Волонтер нажимает на кнопку "Отменить отклик" под заданием, которое стало неактуальным.

Предусловие:
1. Волонтер откликнулся на задание, в БД в таблице task_response_volunteer сохранен отклик

Шаги:
1. Переключить актуальность задания (is_archived), на которое откликнут волонтер, через delete-запрос к "api/task/{task_id}
2. В боте этим волонтером нажимаем на кнопку "Отменить отклик"

ОР: "Это задание уже в работе / в архиве."
ФР: "Задание больше не актуально, ты не можешь на него откликнуться."

2024-08-03 16:25 UTC, ASTimch commented
> [BUG] Не тот текст, когда Волонтер нажимает на кнопку "Отменить отклик" под заданием, которое стало неактуальным.
> 
> Предусловие:
> 
> 1. Волонтер откликнулся на задание, в БД в таблице task_response_volunteer сохранен отклик
> 
> Шаги:
> 
> 1. Переключить актуальность задания (is_archived), на которое откликнут волонтер, через delete-запрос к "api/task/{task_id}
> 2. В боте этим волонтером нажимаем на кнопку "Отменить отклик"
> 
> ОР: "Это задание уже в работе / в архиве." ФР: "Задание больше не актуально, ты не можешь на него откликнуться."

Fixed, прошу перепроверить

2024-08-05 15:27 UTC, gorskyolga requested changes

2024-08-05 15:27 UTC, gorskyolga commented on src/bot/handlers/tasks.py
> +                    status_changed = True
Во всех трех случаях, где сейчас `status_changed = True` нужно вынести эту строчку из условия, т.к. нужно, чтобы надпись на кнопке менялась.
Например, как здесь, если надпись на кнопке была "Откликнуться", то волонтер должен видеть поп-апп ("Фонд увидит отклик, когда твой профиль пройдет модерацию." или "Ты уже откликнулся на это задание.") и надпись на кнопке должна меняться на "Отменить отклик" в обоих случаях.

После такого изменения возможно будет лучше наоборот в начале задавать status_changed = True, а не False, а потом менять status_changed на False (таких случаев меньше).

2024-08-05 20:41 UTC, ASTimch commented on src/bot/handlers/tasks.py
> +                    status_changed = True
Fixed

2024-08-06 09:24 UTC, gorskyolga approved these changes

2024-08-06 09:24 UTC, merged

2024-08-22 12:49 UTC, Xalgina commented
Перепроверила, ок.