Добавление эндпоинтов для обновления информации о пользователях сайта
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #599
Opened 2024-07-18 13:54 UTC by Genek91

### Что сделано

1. Переименованы эндпоинты:

    - `api/auth/external_user_registration/volunteer`
    - `api/auth/external_user_registration/fund`

2. Для схем данных эндпоинтов были добавлены обязательные поля согласно условиям задачи.

3. Добавлены эндпоинты для patch-запросов:

    - `api/auth/external_user_registration/volunteer/{user_id}`
    - `api/auth/external_user_registration/fund/{user_id}`

### Как тестировал
Так как в процессе менялись схемы локально проверил все эндпоинты связанные с [`ExternalSiteUser`](http://localhost:8000/docs#/ExternalSiteUser).
Пробовал передавать разные варианты данных, результат проверял через DBeaver.

2024-07-25 10:14 UTC, gorskyolga requested changes

2024-07-25 10:14 UTC, gorskyolga commented on src/api/services/external_site_user.py
> +            if site_user.role == UserRoles.VOLUNTEER and site_user_schema.specializations:
Нужно переделать условие.
Сейчас если передать "specializations": [], то у external_site_user категории обнуляться, а y user нет.

2024-07-25 10:14 UTC, gorskyolga commented on src/api/services/external_site_user.py
> +        site_user = await self._site_user_repository.get_by_external_id(external_id, False)
Стоит добавить по аналогии с register:
```
if site_user.is_archived:
    raise BadRequestException("Пользователь удален. Обновление невозможно.")
```

Сайт может пытаться обновить данные пользователя, который не подключал бот и его нет в БД, и это нормальная ситуация.
А вот если сайт пытается обновить данные заархивированного пользователя, то значит где-то ошибка.
Так что лучше, если сайт будет иметь возможность отличать эти две ситуации.

2024-07-25 10:14 UTC, gorskyolga commented on src/api/schemas/external_site_user.py
>      def specializations_str_validation(cls, value: str) -> list[int] | None:
Если передать категории как "", то валидатор их не пропускает.
Раз уж можно передать категории и списком, и строкой, то и обнуление категорий должно быть возможно двумя вариантами ("[]" и "").

2024-07-30 18:00 UTC, Xalgina approved these changes
Протестировано.

2024-07-31 08:32 UTC, gorskyolga approved these changes

2024-07-31 08:36 UTC, merged