Feature/add bot lib
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #6
Opened 2023-04-08 16:49 UTC by albaranovsky

Подключение библиотеки Python-Telegram-Bot
[Task](https://www.notion.so/98018c6e8b1748d7b1809b75d0cfa7d3?p=960e36ae035645dbbf057584061ea142&pm=s)

2023-04-08 16:59 UTC, NiKuma0 commented on pyproject.toml
> +python-telegram-bot = "^20.2"
Сделай дамб в poetry.lock: `poetry update`

2023-04-08 16:59 UTC, NiKuma0 commented on src/bot/bot.py
> +    # TODO: Добавить хэндлеры
Где хендлер?

2023-04-08 17:26 UTC, albaranovsky commented on pyproject.toml
> +python-telegram-bot = "^20.2"
Готово

2023-04-08 17:28 UTC, albaranovsky commented on src/bot/bot.py
> +    # TODO: Добавить хэндлеры
Это коммент на будущее, что здесь надо будет добавлять хендлеры. Сами хендлеры в другой задаче.

2023-04-08 17:38 UTC, NiKuma0 approved these changes

2023-04-08 17:49 UTC, NiKuma0 requested changes

2023-04-08 17:49 UTC, NiKuma0 commented on src/bot/bot.py
> +async def start_bot() -> Application:
Добавь запуск бота в хендлер `on_startup` у FastAPI

2023-04-08 17:49 UTC, NiKuma0 commented on src/bot/bot.py
> +    await bot.initialize()
Добавь вебхук.

2023-04-09 09:55 UTC, AntonZelinsky commented on src/bot/bot.py
> +        await bot.updater.start_polling()
Кажется, что всё что выше, относится к созданию и инициализации экземпляра бота, а не в старту.

2023-04-09 09:55 UTC, AntonZelinsky commented on src/bot/bot.py
> +    # TODO: Добавить хэндлеры
Если уже добавляешь обвязку для бота, то нужно добавить хотя бы один хендлер, Аля команды старт. Как ты вообще проверял работоспособность своего кожа, если ни разу его не запускал?

2023-04-09 09:55 UTC, AntonZelinsky commented on src/__init__.py
> +@app.on_event("startup")
Кажется, ты не проверял работоспособность своего кода.... 
Арр - функция, а ни объект, который ты ожидал тут увидеть и у которого есть декоратор.
Может конечно оно и будет работать, но я очень сомневаюсь

2023-04-09 18:00 UTC, NiKuma0 requested changes

2023-04-09 19:17 UTC, albaranovsky commented on src/__init__.py
> +app = create_app()
Создание инстанса app тоже перенести? Это не моя идея была, другой разработчик так реализовал.

2023-04-09 20:03 UTC, NiKuma0 commented on src/__init__.py
> +app = create_app()
Не нужно, оставь как было. Тут все хорошо работает по команде `uvicorn src:app`

2023-04-10 09:17 UTC, albaranovsky commented on src/__init__.py
> +app = create_app()
Возникает конфликт импорта: `__init__.py` импортирует `application.py`, а чтобы перенести функцию, нужно в application.py импортировать инстанс `app` из `__init__.py`. Как лучше поступить?

2023-04-10 10:06 UTC, NiKuma0 approved these changes

2023-04-10 10:37 UTC, NiKuma0 approved these changes

2023-04-10 10:37 UTC, merged