Переопределение метода delete для AdminUser
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #626
Opened 2024-08-07 14:29 UTC by Genek91

### Что сделано
Переопределён метод `delete` в `UserManager` для `AdminUser`. Теперь вместо удаления админа в поле `is_active` устанавливается значение `False`.
### Как тестировал

1. Проверил работоспособность эндпоинта `DELETE:api/admins/{user_id}` (Swagger, DBeaver).
2. Для админа с is_active = False не доступны эндпоинты указанные в условии задачи, там где необходимо добавил зависимость (is_active_user).
3. `DELETE:api/admins/{user_id}` доступен только админу-суперюзеру с is_active=True.

2024-08-08 09:49 UTC, gorskyolga commented on src/api/endpoints/analytics.py
> +)
Вроде должно работать и без добавления зависимостей сюда.
Евгений их перенес в `src\api\endpoints\admin\__init__.py`.
Теперь в admin_router подключаются analytic_router, notification_router_by_admin и user_router. И уже для admin_router добавляется зависимость.

2024-08-09 10:36 UTC, Genek91 commented on src/api/endpoints/analytics.py
> +)
Теперь увидел, спасибо.

2024-08-09 18:14 UTC, gorskyolga requested changes

2024-08-09 18:14 UTC, gorskyolga commented on src/api/endpoints/notification.py
> +notification_router_by_admin = APIRouter(
Здесь тоже не нужно добавлять зависимость.

2024-08-09 18:14 UTC, gorskyolga commented on src/api/endpoints/users.py
> +user_router = APIRouter(
И здесь;)

2024-08-13 17:33 UTC, Xalgina approved these changes
Протестировано. ОК

2024-08-13 21:02 UTC, gorskyolga approved these changes

2024-08-13 21:08 UTC, merged