Split POST and PATCH methods in tasks
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #633
Opened 2024-08-11 19:38 UTC by StriderDunedain

2024-08-15 09:25 UTC, gorskyolga commented
1. Судя по документации, при создании ветки ты наследуешься от старой версии ветки develop. Перед созданием новой ветки нужно подтягивать изменения в базовую ветку.
2. Попробуй протестировать работу эндпоинта на patch-запрос через документацию. Сейчас task_id передается в теле запроса, а должно извлекаться из url.
3. После реализации задачи при тестировании нужно убедиться, что:
- случай, когда передан несуществующий task_id, обрабатывается соответствующе;
- в тело запроса можно передать только часть полей по заданию.

2024-08-15 09:26 UTC, gorskyolga requested changes
1. Судя по документации, при создании ветки ты наследуешься от старой версии ветки develop. Перед созданием новой ветки нужно подтягивать изменения в базовую ветку.
2. Попробуй протестировать работу эндпоинта на patch-запрос через документацию. Сейчас task_id передается в теле запроса, а должно извлекаться из url.
3. После реализации задачи при тестировании нужно убедиться, что:
- случай, когда передан несуществующий task_id, обрабатывается соответствующе;
- в тело запроса можно передать только часть полей по заданию.

2024-08-24 12:12 UTC, gorskyolga commented
Для того, чтобы убрать лишние файлы из изменений, нужно было смержить изменения из develop в свою ветку. Сделала это через интерфейс GitHub (кнопка Update). Тебе нужно будет обновить локальную ветку, если нужно продолжить в ней работать.

2024-08-27 15:02 UTC, gorskyolga commented
Макс, пересоздай, пожалуйста, PR. Сейчас файл [в изменениях](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/pull/633/files) выглядит так, как будто ты полностью удалил файл и создал его заново. Очень тяжело смотреть изменения.

2024-08-27 16:03 UTC, closed without merging

2024-08-27 16:05 UTC, StriderDunedain commented
PR закрыт из-за непонятного diff'а, продолжение [здесь](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/pull/664)