Add check tg user doesn't exist
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #635
Opened 2024-08-11 20:25 UTC by StriderDunedain

2024-08-12 12:56 UTC, gorskyolga requested changes
Макс, PR не прошел проверки из-за конфликтов с базовой веткой. Подтяни, пожалуйста, изменения в develop в локальный репозиторий.

2024-08-12 12:56 UTC, gorskyolga commented on src/api/endpoints/users.py
> +    if user := await user_service.get_by_telegram_id(telegram_id):
Обрати внимание, как используется NotFoundException во всех остальных случаях в проекте. Эта ошибка везде вызывается на уровне репозиториев.
Здесь тоже лучше сделать также.

2024-08-14 17:21 UTC, gorskyolga requested changes

2024-08-14 17:21 UTC, gorskyolga commented on src/core/db/repository/user.py
> +        """Возвращает пользователя (или None) по telegram_id."""
Нужно исправить докстринги функций.
Этот докстринг относится к get_by_telegram_id_or_none.
А для get_by_telegram_id подойдет что-то вроде "Возвращает пользователя по telegram_id, а в случае его отсутствия вызывает исключение NotFoundException."

2024-08-14 18:13 UTC, gorskyolga commented
Такая реализация приводит к ошибкам.
В проекте есть два UserService в `src\api\services\users.py` и в `src\bot\services\user.py`. Они оба используют один и тот же метод репозитория get_by_telegram_id.
Все возможные места, где этот метод используется, не проверяла, но как минимум появляется ошибка в регистрации. При попытке нового пользователя Телеграм добавиться в бот возникает ошибка.
В общем просто так переименовывать get_by_telegram_id в get_by_telegram_id_or_none нельзя.

2024-08-15 17:04 UTC, gorskyolga commented
Правильно будет переопределить get_by_telegram_id для UserService в `src\api\endpoints\users.py`.

2024-08-24 11:57 UTC, gorskyolga requested changes
Если переносить проверку в BaseUserService, то она также наследуется UserService в `src\bot\services\user.py`. Это приводит к ошибкам.
get_by_telegram_id из UserService в `src\bot\services\user.py` используется в on_chat_member_update. Если заблокировать / разблокировать бот пользователем Телеграм, которого нет в БД, то в логах появляется NotFoundException.
К тому же нельзя гарантировать, что не появится других случаев, где нужно будет использовать get_by_telegram_id при несуществующем юзере. Значит в этих случаях тоже придется обходить это исключение.

Давай откатимся к первой реализации, когда проверка была в `src/api/endpoints/users.py`. Умеешь откатываться к старому коммиту?

2024-08-26 19:20 UTC, Xalgina approved these changes
Протестировано, ОК

2024-08-26 20:18 UTC, gorskyolga approved these changes

2024-08-26 20:21 UTC, merged