Добавление скрипта для приглашения первого супер-админа
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #637
Opened 2024-08-16 14:29 UTC by Genek91

### Что сделано
Добавил скрипт для приглашения первого супер-админа после запуска приложения.

### Как тестировал
Проверил, что при старте создаётся токен и приходит письмо с приглашением. После регистрации и перезапуска приложения, новый токен не создаётся и письмо не отправляется, согласно условию задачи.

2024-08-17 11:38 UTC, gorskyolga requested changes

2024-08-17 11:38 UTC, gorskyolga commented on src/api/utils.py
> +async def create_token_for_super_user() -> None:
Попробовала переиспользовать методы, которые используются для api/auth/invitation. Ругается на цикличные импорты Depends, Provide и Container.
Поэтому не стал их использовать?

2024-08-17 11:38 UTC, gorskyolga commented on src/api/utils.py
> +        if admin is None:
Тут лучше перевернуть условие, чтобы уменьшить вложенность.

2024-08-17 11:38 UTC, gorskyolga commented on src/api/utils.py
> +            admin_token = AdminTokenRequest(
Перед созданием токена нужно проверять, есть ли в таблице admin_token_requests запись для указанной почты.
Если есть, то обновлять её, чтобы не множились записи с токенами для одной почты.

2024-08-17 19:06 UTC, Genek91 commented on src/api/utils.py
> +async def create_token_for_super_user() -> None:
У меня был план... Переделал создание токена по аналогии с `email_provider`, но я просто не уверен, что так делать правильно. Изначально хотел сделать как в `fill_db.py`.

2024-08-17 19:41 UTC, Genek91 commented on src/api/utils.py
> +        if admin is None:
Не совсем понял по поводу вложенности.

2024-08-18 08:17 UTC, gorskyolga commented on src/api/utils.py
> +        if admin is None:
Я имела в виду, что можно сделать "if admin: return" и уменьшить отступ у остального кода.

2024-08-18 08:40 UTC, gorskyolga commented on src/api/utils.py
> +        if admin is None:
В текущей реализации, думаю, это можно уже не делать, т.к. блок кода после условия стал меньше.

2024-08-19 18:34 UTC, Xalgina commented
Протестировано. ОК

2024-08-19 18:49 UTC, Xalgina approved these changes
ОК

2024-08-22 11:44 UTC, gorskyolga commented
PR не проходит проверку "Check app" из-за отсутствия настроек почтового сервера в `.github/workflows/healthcheck.yaml`. Можно было бы их туда и передавать, но аналогичная проблема возникает при запуске бота локально без этих настроек. Если не прописывать настройки почтового сервера в .env, то приложение не будет запускаться локально.

Чтобы у разработчиков осталась возможность запускать бот локально без настроек почтового сервера, нужно в create_token_for_super_user перед инициализацией EmailProvider и отправкой письма предусмотреть проверку, что настройки почтового сервера заданы.
Можно проверять, что в settings переменные MAIL_SERVER, MAIL_LOGIN и MAIL_PASSWORD не пустые.

2024-08-22 11:45 UTC, gorskyolga requested changes

2024-08-22 11:45 UTC, gorskyolga commented on src/api/utils.py
> +async def create_token_for_super_user() -> None:
Лучше переименовать эту функцию в create_token_for_main_admin, так будет понятнее, что она делает.

2024-08-22 11:45 UTC, gorskyolga commented on src/api/utils.py
> +        email_provider = EmailProvider(session, settings)
Здесь нужно добавить условие, проверяющее наличие настроек почтового сервера.

2024-09-20 07:52 UTC, gorskyolga approved these changes

2024-09-20 07:52 UTC, merged