(#636): send messaage after bot unblock
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #650
Opened 2024-08-24 10:53 UTC by ASTimch

2024-08-25 12:34 UTC, gorskyolga requested changes

2024-08-25 12:34 UTC, gorskyolga commented on src/bot/handlers/registration.py
> +    await context.bot.send_message(
Бот пытается отправить это сообщение и при блокировке бота. Из-за этого в логах появляется ошибка "telegram.error.Forbidden: Forbidden: bot was blocked by the user".
Нужно отправлять сообщение, только если бот был разблокирован.

2024-08-25 12:34 UTC, gorskyolga commented on src/bot/handlers/registration.py
> +    await procharity_api.send_user_bot_status(user)
Условия были построены таким образом на случай, если on_chat_member_update "слушает" не только блокировку / разблокировку бота.
Сейчас он вроде бы ничего другого не слушает. Но для перестраховки (на случай изменений в Telegram) лучше procharity_api.send_user_bot_status(user) выполнять внутри if.

2024-08-27 05:39 UTC, ASTimch commented on src/bot/handlers/registration.py
> +    await procharity_api.send_user_bot_status(user)
Исправлено.

2024-08-27 15:44 UTC, Xalgina approved these changes
протестировано, ок

2024-08-29 09:07 UTC, gorskyolga approved these changes

2024-08-29 09:08 UTC, merged