Добавление эндпоинтов для технических сообщений от бота
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #653
Opened 2024-08-24 12:34 UTC by Genek91

### Что сделано
Добавлены эндпоинты:

```
GET: api/tech_messages
GET: api/tech_messages/{message_id}
PATCH: api/tech_messages/{message_id}
DELETE: api/tech_messages/{message_id}
```
GET и PATCH доступны авторизованному пользователю, DELETE - главному администратору.
Методы для пагинации и фильтрации сделал по аналогии с `Users`.
Фильтрация доступна по полю `was_read` - `True`, `False` или `None`.
В `ArchivableRepository` добавил метод `archive` (возможно нужен рефакторинг так-как метод дублируется).

### Как тестировал
Локально через документацию вызывал ендпоинты и проверял результат, в т.ч. и через DBeaver. Проверял с разными правами доступа.

2024-08-27 12:16 UTC, gorskyolga requested changes
Нужно немного переделать подключение роутера в связи с новой логикой подключения роутеров админки. Написала в комментариях.

Рефакторинг archive сделаем отдельной задачей после мержа этой.

2024-08-27 12:16 UTC, gorskyolga commented on src/api/endpoints/tech_messages.py
> +tech_message_router = APIRouter(dependencies=[Depends(is_active_user)])
Лучше сделать по аналогии с другими энпдоинтами админки. Например, как user_router.
Нужно подключить tech_message_router к admin_router в `src\api\endpoints\admin\__init__.py`, а здесь удалить эту зависимость.

2024-08-27 12:16 UTC, gorskyolga commented on src/api/router.py
> +api_router.include_router(tech_message_router, prefix="/tech_messages", tags=["Tech messages"])
Эту строчку нужно перенести в `src\api\endpoints\admin\__init__.py` и подключить tech_message_router к admin_router.

2024-08-29 17:50 UTC, Xalgina approved these changes
Протестировано - ок

2024-08-29 19:37 UTC, gorskyolga approved these changes

2024-08-29 19:37 UTC, merged