feature: add-job-handler
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #66
Opened 2023-06-05 09:40 UTC by Eltimccc

1. Добавил class TaskService в bot/services/task.py
2. Добавил view_task_callback в bot/handlers.py

Теперь при нажатии из меню на кнопку "Посмотреть открытые задания"
выводятся 3 задачи без фильтра:

```
ProCharity Bot
От фонда: Название фонда
Категория: Дизайн и верстка
Срок: 06.02.23
Бонусы: [💎💎](https://help.procharity.ru/article/10053) 
```

2023-06-05 10:55 UTC, NiKuma0 commented on src/bot/handlers.py
> +        )
Давай перенесём это в отдельную функцию. Отрисовка задач пригодится и в других местах.

2023-06-05 10:55 UTC, NiKuma0 commented on src/bot/handlers.py
> +            f"{bot_name}\n\n"
Это не нужно. В сообщении итак видно отправителя.

2023-06-05 10:55 UTC, NiKuma0 commented on src/bot/handlers.py
> +    for task in tasks[:3]:
Давай перенесём лимит в запрос в БД.

2023-06-05 10:55 UTC, NiKuma0 commented on src/bot/services/task.py
> +            tasks_list = [task for task in tasks.scalars().all()]
Это зачем? Тут не нужен генератор...

2023-06-05 10:55 UTC, NiKuma0 commented on src/bot/services/task.py
> +    async def get_user_tasks(self) -> List[Task]:
На версии 3.11 это выглядит иначе 
```suggestion
    async def get_user_tasks(self) -> list[Task]:
```

2023-06-05 10:55 UTC, NiKuma0 commented on src/bot/services/task.py
> +            tasks = await session.execute(select(Task).options(joinedload(Task.category)).limit(3))
Перенеси лимит в аргументы функции.

2023-06-05 13:24 UTC, Eltimccc commented on src/bot/services/task.py
> +    async def get_user_tasks(self) -> List[Task]:
Поправил, но тут не от версии питона же List?
Просто в учебных использовали List ане list в аннотации.
Хотя from typing import List есть в прошлом боте =)
> На версии 3.11 это выглядит иначе

2023-06-06 11:12 UTC, NiKuma0 requested changes

2023-06-06 19:03 UTC, NiKuma0 reviewed
Выглядит хорошо. Расскажи как тестировал.

2023-06-06 19:03 UTC, NiKuma0 commented on src/bot/bot.py
> +    bot.add_handler(CommandHandler("start", start_command))
Тут плохо смержил. У тебя тут повторяющиеся хендлеры. Оставь как сейчас в develop-е

2023-06-07 05:21 UTC, Eltimccc commented
> Выглядит хорошо. Расскажи как тестировал.

Ну прям тесты не делал. Я просто добавил через dbeaver несколько задач, перешел в боте в меню и там нажимал посмотреть открытые задачи.

2023-06-07 13:23 UTC, NiKuma0 commented on src/bot/services/formatter.py
> +def display_tasks(task):
Лучше перемести в `src/core/utils.py`

2023-06-07 13:24 UTC, NiKuma0 commented on pyproject.toml
> +pyngrok = "^6.0.0"
Это не нужно тут. Постарайся не менять pyproject.toml

2023-06-07 13:26 UTC, Eltimccc commented on pyproject.toml
> +pyngrok = "^6.0.0"
Так я и не менял..

2023-06-07 14:25 UTC, NiKuma0 commented on src/core/utils.py
> +locale.setlocale(locale.LC_ALL, "ru_RU.UTF-8")
Воспользуйся просто цифрами, у нас в контейнере нет таких локалок
![image](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/78080842/8950adea-58b1-4f54-8465-481c5a2691d5)

2023-06-07 15:36 UTC, NiKuma0 approved these changes

2023-06-07 15:39 UTC, merged