Добавление полей для настроек уведомлений в эндпоинты ExternalSiteUser
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #667
Opened 2024-08-31 19:50 UTC by Genek91

### Что сделано
Добавил:
1. Новые поля в схему `BaseExternalSiteUser`.
2. `Alias` для поля `external_id`.
3. Методы `get_role` для определения роли.
4. Изменение состояния поля `user.has_mailing` в зависимости от `site_user.has_mailing_new_tasks`.
5. Немного изменил метод `register` в `ExternalSiteUserService`. Мне кажется этот метод можно разделить (для волонтёров и фондов отдельно).

### Как тестировал
Проверил работоспособность эндпоинтов через документацию:
```
post "/api/auth/external_user_registration/volunteer"
post "/api/auth/external_user_registration/fund"
patch "/api/auth/external_user_registration/volunteer/{user_id}"
patch "/api/auth/external_user_registration/fund/{user_id}"
```
Если в новые поля передать `Null`, то это никак не повлияет на значения этих полей в БД.

2024-09-05 19:34 UTC, gorskyolga requested changes
Нашла баг. Описала его в комментариях.
Также нашла ошибку у себя в описании задачи: поле has_mailing_new_tasks должно быть только у волонтеров, т.к. фонды не могут подписываться на рассылку о новых заданиях.

2024-09-05 19:34 UTC, gorskyolga commented on src/api/services/external_site_user.py
> +            user.has_mailing = site_user.has_mailing_new_tasks
Если создать пользователя сайта, не передавая новых полей, затем привязать к нему юзера Телеграм и обновить пользователя сайта, снова не передавая новые поля, то получается ошибка "asyncpg.exceptions.NotNullViolationError: null value in column "has_mailing" of relation "users" violates not-null constraint".

2024-09-05 19:41 UTC, gorskyolga commented
По поводу разделения методов register в ExternalSiteUserService (отдельно для волонтёров и фондов) не уверена.
Это не приведет наоборот к дублированию кода?

2024-09-05 21:08 UTC, Genek91 commented
> По поводу разделения методов register в ExternalSiteUserService (отдельно для волонтёров и фондов) не уверена. Это не приведет наоборот к дублированию кода?

Хотел узнать экспертное мнение, да из-за дублирования, наверное, лучше всё в одном.

2024-09-12 16:19 UTC, Xalgina reviewed
[BUG] Значение поля has_mailing_new_tasks=false не записывается в связанного user в поле has_mailing (галочка в поле has_mailing в user остается включенной)

Шаги:
1. Создать пользователя POST /api/v1/auth/external_user_registration/volunteer - в поле "has_mailing_new_tasks" передать "true"
2. Связать телеграм юзера с созданным внешним юзером
3. Обновить внешнего юзера  POST (PATCH) /api/v1/auth/external_user_registration/volunteer. При этом в поле "has_mailing_new_tasks" передать "false"
4. Обновить таблицу user

ОР: В таблице user снимется галочка в поле has_mailing. В боте при вызове меню будет кнопка "Подписаться на задания"
ФР: В таблице user не снимается галочка в поле has_mailing. В боте при вызове меню кнопка "Отписаться от заданий"

![image](https://github.com/user-attachments/assets/937b2bcf-fa8b-44aa-9872-c13ec22c3fb1)

![image](https://github.com/user-attachments/assets/e5bc18fd-c023-4ca2-b4be-cb6eaebfdae1)

![image](https://github.com/user-attachments/assets/ff7b7365-2c0a-4c18-b648-eeb0d20d9660)

2024-09-12 17:50 UTC, Xalgina reviewed
[BUG] 200 ОК при передаче null в полях для настроек уведомлений

Шаги:
1. Передать
has_mailing_new_tasks=null,
has_mailing_profile=null,
has_mailing_my_tasks=null,
has_mailing_procharity=null

в эндпоинтах:

post-запрос к "/api/auth/external_user_registration/volunteer";
post-запрос к "/api/auth/external_user_registration/fund";
patch-запрос к "/api/auth/external_user_registration/volunteer/{user_id}";
patch-запрос к "/api/auth/external_user_registration/fund/{user_id}".

ОР: 422
ФР: 200

![image](https://github.com/user-attachments/assets/de895262-6aab-4bb3-9d7e-7e035957a924)

2024-09-13 10:32 UTC, Xalgina approved these changes

2024-09-13 11:51 UTC, gorskyolga approved these changes

2024-09-13 11:55 UTC, merged