Feature/mailing settings menu 660
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #679
Opened 2024-09-08 15:39 UTC by ASTimch

Для активизации меню настроек и тестирования, необходимо в настройках (src/settings.py) изменить 
SHOW_NOTIFICATION_SETTINGS_MENU = True

2024-09-13 14:12 UTC, gorskyolga requested changes

2024-09-13 14:12 UTC, gorskyolga commented on src/bot/services/external_site_user.py
> +                print(f"after step1 {site_user.has_mailing_profile}")
Осталось два принта после тестирования.

2024-09-13 14:12 UTC, gorskyolga commented on src/bot/handlers/notifications.py
> +    await procharity_api.send_user_bot_status(user)
Волонтер может не нажать кнопку "Готово", тогда в БД бота будут сохранены новые категории, но на сайт эта информация передана не будет.
Нужно перенести отправку данных по эндпоинту сайта в notification_field_callback.

2024-09-14 11:32 UTC, ASTimch commented on src/bot/handlers/notifications.py
> +    await procharity_api.send_user_bot_status(user)
Исправлено

2024-09-14 11:32 UTC, ASTimch commented on src/bot/services/external_site_user.py
> +                print(f"after step1 {site_user.has_mailing_profile}")
Исправлено

2024-09-20 09:06 UTC, Xalgina approved these changes

2024-09-20 13:39 UTC, gorskyolga approved these changes

2024-09-20 13:39 UTC, merged