Passwort reset logic v2.0
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #695
Opened 2024-09-20 05:33 UTC by StriderDunedain

### Что сделано?
Наследовался от актуальной версии `develop` и написал ту же логику, что и была раньше (но в новом pr - прошлый сложновато реанимировать)

### Что теперь?
Жду ревью

2024-09-20 08:29 UTC, gorskyolga requested changes

2024-09-20 08:29 UTC, gorskyolga commented on src/api/fastapi_admin_users.py
> +class CustomFastAPIUsers(Generic[models.UP, models.ID], FastAPIUsers[models.UP, models.ID]):
Здесь Generic[models.UP, models.ID] не нужен.
Почитай еще раз здесь:
https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/pull/590#discussion_r1674350361

2024-09-20 18:44 UTC, gorskyolga requested changes

2024-09-20 18:44 UTC, gorskyolga commented on src/api/endpoints/admin/__init__.py
> +admin_user_router.include_router(fastapi_admin_users.get_reset_password_router(), prefix="", tags=["Reset Password"])
Так новые эндпоинты находятся в [Admins](http://127.0.0.1:8000/docs#/Admins), а должны быть в [AdminAuth](http://127.0.0.1:8000/docs#/AdminAuth). Нужны подключать к admin_auth_router.

2024-09-20 19:30 UTC, gorskyolga commented
Тестировала сейчас и обнаружила, что можно установить новый пароль, состоящий из одного знака.
Посмотрела, что происходит в get_reset_password_router. Нужно в UserManager переопределить validate_password. У нас есть валидатор с таким же именем в `src\api\schemas\admin.py`, в нем проверка на соответствие PASSWORD_POLICY. Нужно такую же проверку в validate_password в UserManager сделать.

2024-09-26 09:06 UTC, Xalgina approved these changes
Протестировано, ок

2024-09-26 13:35 UTC, gorskyolga approved these changes

2024-09-26 13:36 UTC, merged