Исправление бага: при привязке к другой учетке частично остается связь с первой учеткой
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #699
Opened 2024-09-22 12:15 UTC by gorskyolga

Во всех местах, где возникали баги, использовался user.external_user. Проблема была в том, что после привязки к другому пользователю сайта user.external_user оставался не обновленным и продолжал ссылаться на первого пользователя сайта.
При передаче external_id=ext_site_user.id в _update_or_create происходило обновление только user.external_id, но не user.external_user.
В исправленном варианте в _update_or_create передается external_user=ext_site_user. В результате обновляется и user.external_id, и user.external_user.

### Что сделано
1. Исправлено обновление external_user у user при привязке пользователя Телеграм к другой учетке внешнего сайта.
2. Исправлено обнуление связи другого пользователя Телеграм и учетки внешнего сайта при привязке первого пользователя Телеграм к учетке внешнего сайта, к которой был привязан другой пользователь Телеграм.

### Как проверяла
1. Добавила печать user.external_user.external_id, user.external_id, ext_site_user.external_id, user.first_name, user.external_user, чтобы смотреть, как меняются значения при привязке к другой учетке.
**Для удобства тестирования оставила в коде принты и старую версию кода. Перед мержем удалю их.**

2. На примере отображения настроек уведомлений по кнопке "Изменить настройку уведомлений" (пункт 3 в описании задачи):
- изменила SHOW_NOTIFICATION_SETTINGS_MENU: bool = True;
- создала несколько пользователей сайта с разным набором true / false в has_mailing_profile, has_mailing_my_tasks, has_mailing_procharity;
- привязывалась к разным пользователям сайта и проверяла изменение галочек.

2024-09-23 08:41 UTC, Xalgina approved these changes
Протестировано. Ок

2024-09-24 08:52 UTC, eugemos requested changes
С кодом согласен.
Но в описании PR, надо написать, в чем, по твоему мнению, была ошибка или чем было вызвано неверное поведение (лучше самым первым абзацем). Иначе действия по исправлению будут казаться просто шаманством для тех, кто не так погружен в тему (наших приемников, например).

2024-09-24 09:02 UTC, eugemos commented
@gorskyolga Замечание по поводу отладочного кода, который ты удалила: вместо `print("variable", variable)` лучше писать `print(f"{variable=}")`, такая возможность появилась в Python 3.8.

2024-09-24 15:00 UTC, gorskyolga commented
> С кодом согласен. Но в описании PR, надо написать, в чем, по твоему мнению, была ошибка или чем было вызвано неверное поведение (лучше самым первым абзацем). Иначе действия по исправлению будут казаться просто шаманством для тех, кто не так погружен в тему (наших приемников, например).

Обновила описание.

2024-09-24 17:31 UTC, eugemos approved these changes

2024-09-24 19:01 UTC, merged