Feat/last interaction 684
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #700
Opened 2024-09-22 17:48 UTC by ASTimch

Добавлено формирование поля last_interaction при взаимодействии пользователя с ботом.
! Добавилась миграция.

2024-09-25 09:53 UTC, gorskyolga requested changes

2024-09-25 09:53 UTC, gorskyolga commented on src/bot/utils.py
> +            await ext_site_user_service.update_last_interaction(ext_site_user)
Нужно добавить сохранение времени взаимодействия для пользователя Телеграм при неудачной авторизации.

Сейчас при наличии связи с пользователем сайта оба столбца обновляются вместе внутри ext_site_user_service.update_last_interaction. Можно вынести оттуда обновление столбца для user, а здесь добавить поиск user по telegram_id и обновление столбца last_interaction, если user найден.

2024-10-11 10:37 UTC, gorskyolga requested changes
После добавления отдельного user_service.update_last_interaction в декоратор появились ошибки в некоторых местах, где он используется:
1. кнопка "Изменить" - AttributeError: 'Provide' object has no attribute 'get_user_categories_with_parents':
- команда start, кнопка "Проверить компетенции", затем кнопка "Изменить";
- ИЛИ команда menu, кнопка "Изменить компетенции", затем кнопка "Изменить".
2. кнопка "Написать в службу поддержки" в меню - AttributeError: 'Provide' object has no attribute 'get_by_telegram_id'.
3. кнопка "Подписаться на задания" / "Отписаться от заданий" в меню - AttributeError: 'Provide' object has no attribute 'get_by_telegram_id'.
4. все кнопки кроме "Готово" при изменении настроек уведомлений по кнопке "Изменить настройку уведомлений в меню" (в settings.py должно быть SHOW_NOTIFICATION_SETTINGS_MENU: bool = True ) - AttributeError: 'Provide' object has no attribute 'get_by_telegram_id'.

2024-10-14 18:49 UTC, Xalgina approved these changes
Протестировано. Ок

2024-10-15 10:53 UTC, gorskyolga approved these changes

2024-10-15 10:53 UTC, merged