send notifications ver 0.1
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #92
Opened 2023-06-18 20:33 UTC by Andrey-Kugubaev

add send notifications

2023-06-23 15:00 UTC, NiKuma0 commented on src/api/endpoints/tasks.py
> +    await notifications_services.send_messages(display_tasks, User)
А это вообще работает? Раскажи как тестировал.

2023-06-28 15:57 UTC, Andrey-Kugubaev commented on src/api/endpoints/tasks.py
> +    await notifications_services.send_messages(display_tasks, User)
Исправил. убрал эту строчку

2023-06-29 09:55 UTC, NiKuma0 requested changes

2023-06-29 09:55 UTC, NiKuma0 commented on src/api/endpoints/tasks.py
> +    await notifications_services.send_notification(display_tasks)
Зачем новый хендлер добавлять? К тому же они на одном паттерне - какой из них теперь запускается, оба или только один? 

Оставь как было. Я не думаю что можно получить объект TelegramNotification с помощью Depends - для этого нужно его немного поменять.

2023-07-11 10:36 UTC, NiKuma0 requested changes

2023-07-11 10:36 UTC, NiKuma0 commented on src/core/services/notification.py
> +            self.__send_message(user.telegram_id, message)
Тут два одинаковых метода.

2023-07-11 10:36 UTC, NiKuma0 commented on src/api/endpoints/tasks.py
> +    notifications_services: TelegramNotification = Depends(create_bot),
Это всё еще не работает
![image](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/assets/78080842/4b09ba68-5b62-41b8-981a-e2b5158abe71)

2023-07-30 11:36 UTC, closed without merging