Tasks pagination added
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #94
Opened 2023-06-20 19:47 UTC by SabMorgan

Задача https://www.notion.so/98018c6e8b1748d7b1809b75d0cfa7d3?p=38ea03dc53c54167a77fc55ba500a331&pm=s

2023-06-21 09:35 UTC, NiKuma0 commented on src/bot/handlers/tasks.py
> +
Вот эту всю логику нужно перенести в сервис.

2023-06-21 09:35 UTC, NiKuma0 commented on src/bot/handlers/tasks.py
> +        buttons = [[InlineKeyboardButton(text="Открыть меню", callback_data=callback_data.MENU)]]
Все кнопки/клавиотуры должны лежать в отдельном файле `keyboards.py`

2023-06-23 14:52 UTC, NiKuma0 requested changes

2023-06-23 14:52 UTC, NiKuma0 commented on src/bot/services/task.py
> +        tasks_to_show = tasks[start:finish]
Так делать не надо. Можно сделать лимит и оффсет прям в запросе в БД чтобы не подгружать огромное кол-во тасков.

2023-06-23 14:52 UTC, NiKuma0 commented on src/bot/services/task.py
> +    async def get_user_tasks_by_page(self, tasks, context, limit: int):
Этой функции не нужен весь context - не нужно его передавать.

2023-07-01 14:30 UTC, NiKuma0 commented on src/bot/handlers/tasks.py
> +    offset = (page_number - 1) * limit
Это в сервис перенеси - функция называется `get_user_tasks_by_page`, а передаешь туда не номер страницы, а limit и offset.

2023-07-01 14:30 UTC, NiKuma0 commented on src/bot/handlers/tasks.py
> +    remaining_tasks = total_tasks - (offset + limit)
Любая логика, не относящиеся в отрисовке, должна быть в сервисах.

2023-07-01 20:38 UTC, SabMorgan commented on src/bot/handlers/tasks.py
> +    offset = (page_number - 1) * limit
Я не могу передать оффсет в качестве параметра, я же его отдельно формулой прописываю

2023-07-02 10:58 UTC, NiKuma0 commented on src/bot/handlers/tasks.py
> +    tasks_to_show, offset, page_number = await task_service.get_user_tasks_by_page(user_data, limit)
Зачем сюда user_data передавать?
```suggestion
    tasks_to_show, offset, page_number = await task_service.get_user_tasks_by_page(user_data.get("page_number", 1), limit)
```

2023-07-04 10:27 UTC, NiKuma0 approved these changes

2023-07-04 10:46 UTC, merged