Feature/send message to group of users
Studio-Yandex-Practicum/ProCharity_back_2.0 pull request #98
Opened 2023-06-26 15:14 UTC by VadimVolkovsky

Таска
https://www.notion.so/d8599b22e9aa48f0832fccc58c333a3f?pvs=4

- Описал схему запроса `TelegramNotificationRequest`
Реализовал через вспомогательный StrEnum класс, чтобы был фиксированный выбор групп пользователей.
По идее в доке (/docs) должен появится выпадающий список с выбором категорий пользователей для рассылки, но почему-то он не хочет появляться... мб где-то в настройках проекта это заблокировано.

- Написал view класс `send_telegram_notification`

- Создал класс описывающий функционал передачи сообщения определенному пользователю `class TelegramNotificationService`.
Здесь не смог разобраться как применить принцип repository, поэтому пока обратился к модели User напрямую.
При реализации с repository по аналогии с task_service вылетает ошибка `fastapi.exceptions.FastAPIError: Invalid args for response field!` - причину установить пока не смог

- Добавил роут `users_group_notification_router`

2023-06-28 08:15 UTC, NiKuma0 requested changes

2023-06-28 19:12 UTC, NiKuma0 commented on src/api/services/messages.py
> +        users = users.scalars().all()
Можно просто `session.scalars(<query>)` вместо `session.execute(<query>).scalars().all()`

2023-06-28 19:12 UTC, NiKuma0 commented on src/api/services/messages.py
> +        telegram_notification = TelegramNotification(create_bot())
Это тоже нужно запихнуть в DI, на уровень метода init.

2023-06-29 08:37 UTC, VadimVolkovsky commented on src/api/services/messages.py
> +        telegram_notification = TelegramNotification(create_bot())
Не могу понять как в DI реализовать создание экземпляра TelegramNotification - как ни крутил, все равно возвращается объект Application (от create_bot)

Пока сделал в DI только create_bot

2023-06-29 10:26 UTC, NiKuma0 approved these changes

2023-06-29 10:26 UTC, merged